import json, math, sys
import numpy as np
import morie.fn as F
from morie.fn import km042
assert "/src/morie/fn/" in km042.__file__
A={}
def rec(k,v): A[k]=v
g=lambda n: getattr(F,n)
rec("km129",g("kamath_ch9_modality_encoder")("img",lambda i: np.array([[3.0,4.0]]))["estimate"])
rec("km130",g("kamath_ch9_input_alignment_loss")(np.array([[[1.0,2.0]],[[0.0,0.0]]]),"ft","t",llm=lambda p,f: float(np.sum(p)),loss_fn=lambda pr,t: abs(pr-1.0))["estimate"])
o=g("kamath_ch9_input_projector")([[1.0,2.0]],in_align=[[1.0,0.0],[0.0,2.0]]); rec("km131",[o["prompts"],o["estimate"]])
o=g("kamath_ch9_llm_signal_tokens")("p","f",llm=lambda p,f:("hello",[1,2,3])); rec("km132",[o["estimate"],o["text"]])
V=[[1.0,0.0],[0.0,1.0]]; L=[[1.0,0.0],[0.0,1.0]]
o=g("kamath_ch9_clip_image_to_text")(V,L,0.5); rec("km133",[o["estimate"],o["per_pair"]])
rec("km134",g("kamath_ch9_clip_text_to_image")(L,V,0.5)["estimate"])
rec("km135",g("kamath_ch9_clip_contrastive_total")(0.5,0.25)["estimate"])
o=g("kamath_ch9_mml_vlm_loss")([0.5,0.25],[0.5]); rec("km136",[o["estimate"],o["positive_loss"]])
rec("km137",g("kamath_ch9_itm_hard_negative")([0.5,0.25],[0.5])["estimate"])
o=g("kamath_ch9_simvlm_mlm")(None,[0.5,0.25,0.5],[[1.0,2.0]],[0,2]); rec("km138",[o["estimate"],o["n_image_regions"]])
o=g("kamath_ch9_simvlm_prefixlm")(None,[[0.5,0.5,0.25],[0.5,0.25,0.5]],1); rec("km139",[o["estimate"],o["per_sequence"]])
o=g("kamath_ch9_moc_loss")(None,None,None,[[0.7,0.3],[0.2,0.8]],labels=[0,1]); rec("km140",[o["estimate"],o["as_printed"]])
o=g("kamath_ch9_itm_loss")([0.9,0.2],None,None,[1,0]); rec("km141",[o["estimate"],o["per_pair"]])
rec("km145",g("kamath_ch9_mmllm_autoregressive")([0.5,0.25],None)["estimate"])
rec("km142",g("kamath_ch9_itg_loss")(None,[[0.5,0.25],[0.5]])["estimate"])
o=g("kamath_ch9_fom_loss")([0,1],[1,0],P=[[0.2,0.8],[0.6,0.4]]); rec("km143",[o["estimate"],o["per_frame"]])
rec("km144",g("kamath_ch9_mm_instr_predict")("I","M",lambda I,M: "ans")["estimate"])
o=g("kamath_ch9_output_projector_mse")(np.array([[[1.0,2.0]],[[0.0,0.0]]]),[[1.0,1.0]],"t"); rec("km146",[o["estimate"],o["argmin"],o["losses"]])
rec("km147",g("kamath_ch9_output_alignment")([[1.0,2.0]],out_align=[[1.0,0.0],[0.0,2.0]])["features"])
o=g("kamath_ch9_ldm_loss")(np.array([[1.0,2.0],[0.0,1.0]]),None,None,eps_net=np.array([[1.0,1.0],[0.0,0.0]])); rec("km148",[o["estimate"],o["per_sample"]])
o=g("kamath_ch9_flamingo_factorized")([0.5,0.25]); rec("km149",[o["estimate"],o["nll"]])
rec("km150",g("kamath_ch9_flamingo_dataset_mix")([[[0.5,0.25]],[[0.5]]],[1.0,2.0])["estimate"])
# named
rec("km3h",g("kamath_3h_alignment")([1.0,0.0],[0.5,0.5],[0.0,1.0])["score"])
o=g("kamath_adalora_rank_allocation")([[1.0,0.0],[0.0,1.0]],[3.0,1.0],[[1.0,0.0],[0.0,1.0]],target_rank=1)
rec("kmadal",[o["Delta_W"],o["kept"],o["estimate"]])
o=g("kamath_houlsby_adapter")([[1.0,2.0,3.0]],[[1.0,0.0,0.0]],[[1.0],[0.0],[0.0]])
rec("kmadap",[o["h_adapted"],o["bottleneck"],o["estimate"]])
o=g("kamath_alibi_bias")([[1.0,0.0]],[[1.0,0.0],[0.0,1.0]],[[1.0,0.0],[0.0,1.0]],[1.0])
rec("kmalbi",[o["output"][0],o["bias"]])
o=g("kamath_autoprompt_gradient_search")([None,"x",None],"D",lambda t,d: float(sum(len(str(s)) for s in t)),vocab=["aa","b"])
rec("kmap",[o["estimate"],o["trigger_tokens"],o["positions"]])
rec("kmarel",g("kamath_ragas_answer_relevance")("ans",[1.0,1.0],lambda a: [[1.0,0.0],[0.0,1.0]])["estimate"])
rec("kmbleu",g("kamath_bleu_score")(["a","b","c","d"],[["a","b","c","e"]],max_n=2)["estimate"])
rec("kmbm25",g("kamath_bm25_score")(["cat","dog"],["cat","cat","fish"],{"cat":1.5,"dog":2.0},3.0)["estimate"])
o=g("kamath_best_of_n_sampling")(["a","b","c"],rewards=[0.1,0.9,0.4]); rec("kmbon",[o["estimate"],o["best"],o["best_index"]])
rec("kmbrad",g("kamath_bradley_terry_preference")([2.0,0.0],[0.5,1.0])["p_pref"])
rec("kmbsco",g("kamath_bertscore")(["a","b"],["a","c"],{"a":[1.0,0.0],"b":[0.0,1.0],"c":[1.0,1.0]})["estimate"])
o=g("kamath_constitutional_ai_loop")("r0",["p1","p2"],lambda st,p,y,c: f"{st}:{p}:{y}")
rec("kmcai",o["revised_response"])
o=g("kamath_expert_capacity_factor")(100,8,1.25); rec("kmcap",[o["estimate"],o["slots"],o["min_dropped"]])
o=g("kamath_christiano_deep_rl_feedback")([("w1","l1"),("w2","l2")],lambda s: 2.0 if s.startswith("w") else 0.5)
rec("kmcchr",[o["estimate"],o["mean_loss"],o["pair_accuracy"]])
o=g("kamath_chinchilla_compute_optimal")(1.2e21); rec("kmchin",[o["N_opt"],o["D_opt"],o["compute_check"]])
o=g("kamath_chain_of_thought")("Q",lambda p: "step one. Answer: 42"); rec("kmcot",[o["answer"],o["reasoning"],o["prompt"]])
o=g("kamath_corrective_rag")("q",["d1","d2","d3"],lambda q,d: {"d1":0.9,"d2":0.5,"d3":0.1}[d],0.8,0.2)
rec("kmcrag",[o["estimate"],o["action"],o["ctx"]])
o=g("kamath_cross_encoder_rerank")("q",["a","b","c"],lambda q,d:{"a":0.1,"b":0.9,"c":0.9}[d])
rec("kmcrb",[o["ranking"],o["estimate"]])
rec("kmcrel",g("kamath_ragas_context_relevance")(["s1","s2","s3"],[1,0,1])["estimate"])
o=g("kamath_crowspairs_bias")([-1.0,-3.0,-2.0],[-2.0,-1.0,-2.0]); rec("kmcrwd",[o["estimate"],o["n_ties"]])
o=g("kamath_double_quantization")([0.5,-1.0,0.25]); rec("kmdbq",[o["scales_int8"],o["shared_const"],o["estimate"]])
o=g("kamath_differential_privacy")(0.5,0.01,p_D=[0.6,0.4],p_Dp=[0.5,0.5]); rec("kmdp",[o["estimate"],o["guarantee"],o["worst_event"]])
o=g("kamath_dpo_loss")([-0.5],[-1.5],[-1.0],[-1.0],0.5); rec("kmdpok",[o["estimate"],o["implicit_reward_w"]])
o=g("kamath_dense_passage_retrieval")([1.0,0.0],[[1.0,0.0],[0.5,0.5],[1.0,0.0]],2)
rec("kmdpr",[o["top_k_indices"],o["top_k_scores"]])
o=g("kamath_emergent_abilities")([1.0,10.0,100.0],[0.1,0.2,0.9],50.0); rec("kmemer",[o["estimate"],o["emergent_score"]])
o=g("kamath_memorization_exposure")(-2.0,[-1.0,-3.0,-4.0]); rec("kmexp",[o["estimate"],o["rank"]])
rec("kmfact",g("kamath_factscore")(["c1","c2","c3"],["c1","c3"])["estimate"])
o=g("kamath_few_shot_exemplar_selection")([[1.0,0.0],[0.0,1.0],[1.0,1.0]],[1.0,0.0],2)
rec("kmfew",[o["selected"],o["similarities"]])
o=g("kamath_fasttext_subword")("ab",{"<a":[1.0],"ab":[2.0],"b>":[3.0],"<ab>":[4.0]},2,2)
rec("kmfst",[o["vector"],o["ngrams"],o["n_known"]])
rec("kmgev",g("kamath_g_eval")("x","y",[1,2,3],lambda x,y,r: [0.0,1.0,0.0])["estimate"])
o=g("kamath_glove_cost")([[2.0,0.0],[1.0,3.0]],[[1.0],[0.0]],[[1.0],[1.0]],[0.0,0.0],[0.0,0.0],x_max=2.0,alpha=0.5)
rec("kmglv",[o["estimate"],o["n_nonzero"]])
rec("kmgrnd",g("kamath_groundedness_reward")(["A","b","c"],["a","b"])["estimate"])
o=g("kamath_hybrid_retrieval_fusion")([0.1,0.9],[0.8,0.2],0.25); rec("kmhyb",[o["scores"],o["ranking"]])
o=g("kamath_hyde_hypothetical_doc")("q",lambda q:[1.0,0.0],{"d1":[1.0,0.0],"d2":[0.0,1.0]},k=1)
rec("kmhyde",[o["retrieved"],o["estimate"]])
o=g("kamath_in_context_learning_prob")(["e1","e2"],"q",lambda p,a: 0.25); rec("kmicl",[o["estimate"],o["prompt"],o["log_prob"]])
o=g("kamath_instruction_tuning_loss")([[1.0,0.0],[0.0,1.0],[2.0,0.0]],[0,1,1],[0,1,0])
rec("kminst",[o["estimate"],o["perplexity"],o["n_response_tokens"]])
print(json.dumps(A))
