import json, math, sys
import numpy as np
import morie.fn as F
from morie.fn import km042
assert "/src/morie/fn/" in km042.__file__
A={}
def rec(k,v): A[k]=v
g=lambda n: getattr(F,n)
I=[[1.0,0.0],[0.0,1.0],[1.0,1.0]]; T=[[1.0,0.0],[0.0,1.0],[1.0,1.0]]
o=g("kamath_image_text_contrastive")(I,T,0.5); rec("kmitc",[o["estimate"],o["loss_i2t"]])
o=g("kamath_image_text_matching")([1.0,2.0],[3.0],[1.0,0.0,-1.0],0.5); rec("kmitm",[o["estimate"],o["logit"],o["fused"]])
o=g("kamath_kl_reward_shaping")([1.0,2.0],0.5,0.4); rec("kmklr",[o["estimate"],o["shaped"]])
o=g("kamath_moe_load_balance_loss")([0.7,0.3],[0.6,0.4],2,0.01); rec("kmlb",[o["estimate"],o["imbalance_ratio"]])
o=g("kamath_lora_weight_update")([[1.0,0.0],[0.0,1.0]],[[1.0,1.0]],[[2.0],[0.0]],4.0,1,[1.0,3.0])
rec("kmlora",[o["h"],o["scaling"],o["n_trainable"]])
o=g("kamath_llava_visual_instruction")("im",[[1.0,0.0],[0.0,1.0]],lambda i:[[1.0,2.0]],[[3.0,4.0]])
rec("kmlv",[o["visual_tokens"],o["inputs"],o["n_visual"]])
o=g("kamath_multimodal_mae")({"v":[0.0]},{"v":[1.0,2.0]},{"v":[True,False,True]},decoders={"v":lambda x,m:[0.5,1.0]})
rec("kmmae",[o["estimate"],o["n_masked"]])
o=g("kamath_mamba_ssm")([1.0,2.0],[-1.0,-2.0],[1.0,1.0],[1.0,1.0],0.5)
rec("kmmamb",[o["y"],o["states"]])
o=g("kamath_membership_inference")([0.1,0.9,0.3],0.5,labels=[1,0,0]); rec("kmmbi",[o["estimate"],o["tpr"],o["fpr"]])
o=g("kamath_medusa_heads")([1.0,2.0],[[[1.0,0.0],[0.0,1.0]],[[0.0,1.0],[1.0,0.0]]],2)
rec("kmmedu",[o["tokens"],o["probabilities"]])
o=g("kamath_moe_router_softmax")([1.0,0.0],[[1.0,0.0,2.0],[0.0,1.0,0.0]],[lambda x: x*1.0, lambda x: x*2.0, lambda x: x*3.0],2)
rec("kmmoe",[o["output"],o["gate_weights"],o["selected_experts"]])
H=[[0.0,0.0],[1.0,0.0]]; R=[[0.0,1.0],[1.0,1.0]]
o=g("kamath_moverscore")(H,R); rec("kmmsc",[o["estimate"],o["wmd"],o["normalizer"]])
o=g("kamath_nf4_datatype")(4); rec("kmnf4",[o["levels"],o["normalized"],o["n_bits"]])
rec("kmngrm",g("kamath_ngram_language_model")(3,12)["estimate"])
o=g("kamath_nucleus_sampling")([2.0,1.0,0.0],0.7); rec("kmnuc",[o["probabilities"],o["kept"],o["n_kept"],o["kept_mass"]])
o=g("kamath_nextgpt_any2any")({"img":1,"txt":2},{"img":lambda v:v*10,"txt":lambda v:v*100},lambda f: sum(f.values()),{"aud":lambda s: s+1})
rec("kmnxtg",[o["outputs"],o["llm_state"],o["input_modalities"]])
o=g("kamath_p_tuning_v2")([([[1.0,1.0]],[[2.0,2.0]])],[([[3.0,3.0]],[[4.0,4.0]])])
rec("kmp2",[o["K"],o["n_trainable"]])
o=g("kamath_perplexity")([-1.0,-2.0]); rec("kmperp",[o["estimate"],o["bits_per_token"]])
o=g("kamath_pet_loss")([1.0,0.0],0,[[1.0,0.0],[0.0,2.0]],[0,-100],0.5)
rec("kmpet",[o["estimate"],o["loss_ce"],o["loss_mlm"]])
att=lambda v: v*0.5; ffn=lambda v: v*0.25
o=g("kamath_post_ln_transformer")([[1.0,2.0,3.0]],att,ffn); rec("kmpoln",[o["output"],o["after_attention"]])
o=g("kamath_pre_ln_transformer")([[1.0,2.0,3.0]],att,ffn); rec("kmprln",[o["output"],o["after_attention"]])
o=g("kamath_ppo_rlhf_objective")([1.0,2.0],[-1.0,-2.0],[-1.5,-1.5],0.5); rec("kmppok",[o["estimate"],o["kl_estimate"]])
o=g("kamath_prefix_tuning")([[1.0,0.0]],[[0.0,1.0]],[[0.0,1.0]],[[1.0,1.0]],Q=[[1.0,0.0]])
rec("kmpref",[o["K"],o["estimate"],o["prefix_attention_mass"]])
o=g("kamath_prompt_tuning")([[1.0,2.0]],[[3.0,4.0],[5.0,6.0]]); rec("kmptun",[o["X_aug"],o["n_trainable"]])
o=g("kamath_q_former")([[1.0,0.0]],[[1.0,0.0],[0.0,1.0]]); rec("kmqfrm",[o["Z"],o["compression"]])
o=g("kamath_qlora_4bit")({"codes":[[0,3],[1,2]],"absmax":2.0},[[1.0,0.0]],[[1.0],[0.0]],2.0,1,[1.0,1.0])
rec("kmqlor",[o["W0_dequantized"],o["h"]])
o=g("kamath_retnet_retention")([[1.0,0.0],[0.0,1.0]],[[1.0,0.0],[0.0,1.0]],[[1.0,2.0],[3.0,4.0]],0.5)
rec("kmret",[o["output"],o["recurrent_output"],o["decay"]])
o=g("kamath_rlhf_pipeline")(["d"],[("a","b")],"pi0",sft=lambda p,d:"sft",train_rm=lambda p:(lambda y:1.0),ppo=lambda p,r,ref:"rlhf")
rec("kmrhf",[o["policy"],o["policy_sft"],o["kl_reference_is_sft"]])
o=g("kamath_rlaif_objective")([("a","b"),("b","c"),("c","a"),("a","c")])
rec("kmrlaif",[o["items"],o["strengths"],o["estimate"],o["accuracy"]])
o=g("kamath_reward_model_training_loss")([2.0,1.0],[0.5,1.5]); rec("kmrmloss",[o["estimate"],o["accuracy"],o["mean_margin"]])
o=g("kamath_rms_norm")([3.0,4.0]); rec("kmrmsn",[o["y"],o["rms"]])
o=g("kamath_rotary_positional_embedding")([[1.0,0.0,0.0,1.0],[1.0,1.0,1.0,1.0]])
rec("kmrope",[o["y"],o["theta"],o["angles"]])
o=g("kamath_rouge_n")(["a","b","c","a"],["a","b","d"],n=1); rec("kmroug",[o["recall"],o["precision"],o["f1"]])
o=g("kamath_reciprocal_rank_fusion")([["a","b","c"],["b","a"]],k=1)
rec("kmrrf",[o["ranking"],[o["scores"][d] for d in o["ranking"]]])
o=g("kamath_rejection_sampling_finetune")(["p1","p2"],[["a","b","c"],["d","e"]],[[0.1,0.9,0.5],[0.2,0.8]],2)
rec("kmrsft",[[list(t) for t in o["retained"]],o["retained_rewards"],o["n_dropped"]])
o=g("kamath_rwkv_time_mix")([1.0,0.5,-0.5],[1.0,2.0,3.0],0.5,0.25); rec("kmrwkv",o["wkv"])
o=g("kamath_self_consistency")(["a","b","a","c"]); rec("kmsc",[o["answer"],o["votes"],o["agreement"],o["tie"]])
o=g("kamath_scaling_laws")([1e6,1e8],1e10,0.5,0.1); rec("kmscal",[o["loss"],o["reducible"]])
o=g("kamath_sentencepiece_tokenizer")(["abab","abc"],5,max_piece_len=3)
rec("kmsp",[sorted(o["probs"].keys()),o["vocab_size"],round(o["log_likelihood"],9)])
o=g("kamath_speculative_decoding")([0.6,0.3,0.1],[0.3,0.5,0.2],proposed=0)
rec("kmspd",[o["estimate"],o["ratio"],o["residual"],o["rejection_rate"]])
o=g("kamath_t5_span_corruption")(list("abcdefghijklmnop"),mean_span_len=2.0,corruption_rate=0.25,seed=7)
rec("kmspn",[o["input"],o["target"],o["span_lengths"],o["n_spans"]])
o=g("kamath_self_rag")("ctx",lambda c,q: "[Retrieve] [Relevant] [Utility:4]")
rec("kmsrag",[o["tokens"],o["retrieve"],o["relevant"],o["utility"],o["estimate"]])
o=g("kamath_step_back_prompting")("what year did X happen",lambda q:"history of X",retrieve=lambda q: ["d1","d2"] if q=="history of X" else ["d2","d3"])
rec("kmstb",[o["step_back_query"],o["context"],o["n_context"]])
o=g("kamath_summarize_from_feedback")([(2.0,1.0),(1.0,2.0)],[1.0,2.0],[-1.0,-2.0],[-1.5,-1.5],0.5)
rec("kmstgn",[o["loss_rm"],o["rm_accuracy"],o["objective"]])
o=g("kamath_stereoset_bias")([0.6,0.4,0.5],[0.5,0.5,0.5]); rec("kmstst",[o["estimate"],o["n_ties"],o["bias_magnitude"]])
o=g("kamath_swiglu_activation")([1.0,2.0],[[1.0,0.0],[0.0,1.0]],[[0.0,1.0],[1.0,0.0]])
rec("kmswig",[o["output"],o["gate"],o["linear"]])
o=g("kamath_temperature_sampling")([2.0,1.0,0.0],0.5); rec("kmtemp",[o["probabilities"],o["entropy"]])
o=g("kamath_moe_top_k_gating")([0.1,0.5,0.4],2); rec("kmtopk",[o["weights"],o["selected_experts"],o["kept_mass"]])
o=g("kamath_tree_of_thoughts")("root",2,2,lambda s,b: [(s+"a",1.0),(s+"b",2.0)],beam=1)
rec("kmtot",[o["best_state"],o["best_path"],o["best_score"],o["n_expanded"]])
o=g("kamath_toxigen_score")("t",lambda t: (0.3,0.7)); rec("kmtoxg",[o["estimate"],o["toxic"]])
o=g("kamath_unigram_lm_tokenizer")(["abab"],["a","b","ab"],max_iter=20)
rec("kmuni",[sorted(o["probs"].items()),round(o["log_likelihood"],9),o["segmentations"]])
o=g("kamath_vera_adapter")([[1.0,0.0],[0.0,1.0]],[[1.0,1.0]],[[1.0],[2.0]],[2.0,3.0],[5.0],[1.0,2.0])
rec("kmvera",[o["h"],o["n_trainable"]])
o=g("kamath_verbalizer_mapping")([1.0,0.0,2.0],["gr","te","ok"],{"pos":["gr","ok"],"neg":["te"]})
rec("kmverb",[o["probabilities"],o["normalized"],o["prediction"],o["mass_outside"]])
o=g("kamath_word2vec_skipgram")([0,1],[1,0],[[1.0,0.0],[0.0,1.0]],[[1.0,0.0],[0.0,1.0]])
rec("kmw2v",[o["log_likelihood"],o["per_pair"]])
o=g("kamath_yarn_context_extrapolation")(10000.0,4.0,8)
rec("kmyarn",[o["theta"],o["theta_new"],o["scale_factors"]])
o=g("kamath_yarn_context_extrapolation")(10000.0,4.0,8,ramp=(1,3))
rec("kmyarn_ramp",o["theta_new"])
rec("kmpask",[g("kamath_pass_at_k")(10,3,2)["estimate"],g("kamath_pass_at_k")(5,0,2)["estimate"]])
print(json.dumps(A))
