#!/usr/bin/env python3
"""Emit full-precision cross-language anchors for the TMLE/CATE shelf.

The fixture is generated by a linear congruential generator using ONLY
exact integer arithmetic and division by a power of two. Every
intermediate stays below 2^53, so R doubles and Python ints produce
bit-identical values. Deliberately no ``qnorm``: R's Wichura AS241 and
Python's Acklam inverse-normal disagree in the last ulp, which is
enough to break a ten-significant-digit anchor.

Run from the repository root:
    PYTHONPATH=src python3 scripts/audit/gen_cate_parity_anchors.py
"""

import sys

import numpy as np

sys.path.insert(0, "src")

from morie.fn._cforest import CausalForest          # noqa: E402
from morie.fn._tmle import tmle_ate                 # noqa: E402

SEED = 20260728
N = 300


def lcg(seed=SEED):
    s = seed
    while True:
        s = (1664525 * s + 1013904223) % 4294967296
        yield (s + 0.5) / 4294967296.0


def fixture(n=N):
    u = lcg()
    w1 = np.empty(n)
    w2 = np.empty(n)
    a = np.empty(n)
    y = np.empty(n)
    for i in range(n):
        w1[i] = 2.0 * next(u) - 1.0
        w2[i] = 2.0 * next(u) - 1.0
        g = 0.5 + 0.3 * w1[i]
        a[i] = 1.0 if next(u) < g else 0.0
        e = next(u) - 0.5
        y[i] = (1.0 + 0.5 * w1[i] + 0.8 * w2[i]
                + (1.0 + 0.6 * w1[i]) * a[i] + 0.4 * e)
    return y, a, np.column_stack([w1, w2])


def main():
    y, a, W = fixture()
    out = tmle_ate(y, a, W)
    f = CausalForest(n_trees=60, min_leaf=10, max_depth=4, seed=0)
    f.fit(W, y, a)
    tau = f.predict()

    print("# fixture checksums (arithmetic only, must match R exactly)")
    for name, v in (("sum_y", y.sum()), ("sum_a", a.sum()),
                    ("sum_w1", W[:, 0].sum()), ("sum_w2", W[:, 1].sum())):
        print("%-10s %.17g" % (name, v))
    print()
    print("# morie_tmle_ate anchors (deterministic -- exact parity expected)")
    for k in ("ate", "se", "epsilon", "ey1", "ey0"):
        print("%-10s %.17g" % (k, out[k]))
    print("eif_mean   %.17g" % float(np.mean(out["eif"])))
    print()
    print("# causal forest (RNG differs between languages -- NOT exact)")
    print("ate        %.17g" % float(np.mean(tau)))
    print("sd         %.17g" % float(np.std(tau, ddof=1)))


if __name__ == "__main__":
    main()
