source("r-package/morie/R/wasserman_native.R")
ok <- 0L; bad <- 0L
tryCatch({ eval(parse(text = "morie_wasserman_variance(c(1, 2, 3, 4))$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_variance:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_chebyshev_ineq(2)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_chebyshev_ineq:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_empirical_cdf(2.5, c(1, 2, 3, 4))$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_empirical_cdf:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "g <- seq(0, 1, length.out = 1001)
round(morie_wasserman_expectation(g, rep(1, 1001))$estimate, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_expectation:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_covariance(c(1, 2, 3), c(2, 4, 6))$correlation")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_covariance:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_markov_ineq(1, 4)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_markov_ineq:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_hoeffding(100, 0.1, 0, 1)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_hoeffding:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_mgf(c(1, 2), 0)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_mgf:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_char_fn(c(1, 2, 3), 0)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_char_fn:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_clt(c(1, 2, 3, 4))$mean")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_clt:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_lln(c(2, 4, 6))$running_means")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_lln:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_delta_method(3, 0.5, 6)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_delta_method:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_empirical_quantile(c(3, 1, 4, 2), 0.5)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_empirical_quantile:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_dkw_cb(c(1, 2, 5), 0.05)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_dkw_cb:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_nonparametric_boot(c(1, 2, 3, 4), NULL, 50)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_nonparametric_boot:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_bootstrap_percentile(c(1, 2, 3, 4), NULL, 50, 0.1)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_bootstrap_percentile:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_bootstrap_pivotal(c(1, 2, 3, 4), NULL, 50, 0.1)$lower")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_bootstrap_pivotal:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_parametric_boot(c(1, 2, 3, 4), NULL, NULL, 50)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_parametric_boot:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_influence_function(c(1, 2, 3, 4), NULL)$influence")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_influence_function:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_likelihood(c(1, 2), NULL, 1)$log_likelihood, 12)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_likelihood:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_log_likelihood(c(1, 2), NULL, 1)$per_observation")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_log_likelihood:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_cramer_rao(0, 25, 0.25)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_cramer_rao:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_fisher_info(NULL, 2)$estimate, 4)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_fisher_info:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_mle_asymptotic(1:100, NULL, 2)$se, 4)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_mle_asymptotic:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "X <- cbind(1, rep(c(-1, 1), 4)); y <- X %*% c(1, 2) + rep(c(0.5, -0.5, -0.5, 0.5), 2)
round(morie_wasserman_white_huber(X, y)$beta, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_white_huber:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "x <- c(0, 0.1, -0.1, 0.05, 10, 10.1, 9.9, 10.05)
round(morie_wasserman_em_algorithm(x, c(0.5, -1, 11, 1, 1))$mu1, 4)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_em_algorithm:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_chi_sq_gof(c(10, 20, 30), c(20, 20, 20))$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_chi_sq_gof:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "g <- seq(-5, 5, length.out = 2001)
round(morie_wasserman_posterior(c(1, 0.5, 1.5), NULL, list(g, rep(1, 2001)))$estimate, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_posterior:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "g <- seq(0, 1, length.out = 10001)
round(morie_wasserman_credible_interval(list(g, rep(1, 10001)), 0.1)$lower, 4)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_credible_interval:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "g <- seq(0, 1, length.out = 10001)
round(morie_wasserman_posterior_mean(list(g, rep(1, 10001)))$estimate, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_posterior_mean:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "d <- seq(-1, 1, length.out = 2001)
round(morie_bayes_factor_savage_dickey(d, 1 / 6, 0)$estimate, 3)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_bayes_factor_savage_dickey:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_entropy(c(0.5, 0.5))$bits, 12)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_entropy:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_kullback_leibler(c(0.5, 0.5), c(0.25, 0.75))$estimate, 12)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_kullback_leibler:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_mutual_info(c(0, 0, 1, 1), c(0, 0, 1, 1))$bits, 12)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_mutual_info:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_odds_ratio(rbind(c(30, 10), c(15, 45)))$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_odds_ratio:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_relative_risk(rbind(c(30, 70), c(10, 90)))$estimate, 12)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_relative_risk:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_density(rbind(c(0, 1, 0), c(1, 0, 1), c(0, 1, 0)))$n_edges")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_density:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_sgt_closeness_centrality(rbind(c(0, 1, 0), c(1, 0, 1), c(0, 1, 0)))$closeness")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_sgt_closeness_centrality:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "X <- cbind(1, c(0, 1, 2)); morie_wasserman_least_squares(X, c(1, 3, 5))$beta")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_least_squares:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "X <- cbind(1, c(0, 1, 2)); morie_wasserman_ridge(X, c(1, 3, 5), 0.5)$beta")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_ridge:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_lasso(diag(2), c(3, -1), 0.5)$beta")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_lasso:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_logistic_regression(matrix(1, 4, 1), c(1, 1, 1, 0))$beta, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_logistic_regression:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_poisson_regression(matrix(1, 4, 1), c(1, 2, 3, 2))$beta, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_poisson_regression:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_aic(-100, 3)$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_aic:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_bic(-100, 3, 50)$estimate, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_bic:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "X <- cbind(1, 0:7); round(morie_wasserman_kfold_cv(X, 1 + 2 * (0:7), NULL, 4)$estimate, 10)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_kfold_cv:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_kernel_regression(0, c(-1, 1), c(2, 4), 1e6)$estimate, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_kernel_regression:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_local_polynomial(1.5, 0:3, c(1, 3, 5, 7), 0.7, 1)$estimate, 8)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_local_polynomial:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_smoothing_spline(0:3, c(0, 2, 0, 2), 1)$effective_df, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_smoothing_spline:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_pca(rbind(c(-1, -1), c(0, 0), c(1, 1)), 1)$estimate, 12)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_pca:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_kmeans(matrix(c(0, 0.2, -0.2, 10, 10.2, 9.8), ncol = 1), 2)$labels")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_kmeans:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "x <- c(0, 0.1, -0.1, 0.05, 10, 10.1, 9.9, 10.05)
round(morie_wasserman_gmm_em(x, 2)$weights, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_gmm_em:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "A <- rbind(c(0.7, 0.3), c(0.4, 0.6)); B <- rbind(c(0.9, 0.1), c(0.2, 0.8))
round(morie_wasserman_hmm_forward(c(0, 1, 0), A, B, c(0.6, 0.4))$estimate, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_hmm_forward:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "A <- rbind(c(0.7, 0.3), c(0.4, 0.6)); B <- rbind(c(0.9, 0.1), c(0.2, 0.8))
morie_wasserman_viterbi(c(0, 1, 0), A, B, c(0.6, 0.4))$path")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_viterbi:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_gibbs_sampler(0.9, c(0, 0), 200)$estimate, 3)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_gibbs_sampler:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "p <- function(x) exp(-0.5 * x^2)
round(morie_wasserman_mcmc_metropolis(p, 1, 0, 200)$acceptance_rate, 3)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_mcmc_metropolis:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "dag <- list(list(parents = integer(0), cpt = list(0.3)),
            list(parents = 0L, cpt = list(`0` = 0.2, `1` = 0.9)))
round(morie_wasserman_directed_graph(dag, c(1, 1))$estimate, 12)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_directed_graph:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "agree <- function(t) if (t[1] == t[2]) 2 else 1
morie_wasserman_undirected_graph(list(2, list(c(0, 1))), list(agree))$estimate")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_undirected_graph:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "agree <- function(t) if (t[1] == t[2]) 2 else 1
morie_wasserman_graphical_model(list(2, list(c(0, 1))), list(agree))$mode")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_graphical_model:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_log_linear(rbind(c(30, 10), c(15, 45)))$estimate, 6)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_log_linear:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "morie_wasserman_boosting(matrix(0:3, ncol = 1), c(1, -1, 1, -1), NULL, 5)$rounds_used")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_boosting:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "round(morie_wasserman_svm(rbind(c(-1, -1), c(1, 1)), c(-1, 1))$w, 8)")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_svm:", conditionMessage(e), "\n") })
tryCatch({ eval(parse(text = "R <- rbind(c(1, 4), c(2, 2), c(3, 1))
morie_wasserman_minimax(R, c(\"T1\", \"T2\", \"T3\"), c(\"F1\", \"F2\"))$minimax_estimator")); ok <- ok + 1L }, error = function(e) { bad <<- bad + 1L; cat("EXAMPLE FAILS: morie_wasserman_minimax:", conditionMessage(e), "\n") })
cat(sprintf("examples ok %d, failing %d\n", ok, bad))
