source("r-package/morie/R/wasserman_native.R")
source("r-package/morie/tests/testthat/helper-wasserman-anchors.R")
FAIL <- 0L; N <- 0L
eqn <- function(a, b) {
  N <<- N + 1L
  a <- as.numeric(a); b <- as.numeric(b)
  ok <- length(a) == length(b) && all(is.na(a) == is.na(b)) &&
        all(abs(a[!is.na(a)] - b[!is.na(b)]) <= 1e-9 * pmax(1, abs(b[!is.na(b)])))
  if (!isTRUE(ok)) { FAIL <<- FAIL + 1L; cat("MISMATCH:", deparse(sys.call(-1)), "\n  got:", a, "\n  exp:", b, "\n") }
}
p <- W$wsmvar; r <- morie_wasserman_variance(c(1,2,3,4))
eqn(r$estimate, p$estimate); eqn(r$sample_variance, p$sample_variance); eqn(r$sd, p$sd)
p <- W$wsmcby; r <- morie_wasserman_chebyshev_ineq(c(2, 0.5))
eqn(r$bounds, p$bounds); eqn(r$raw_bounds, p$raw_bounds)
p <- W$wsmcdf; r <- morie_wasserman_empirical_cdf(c(2.5,2,0), c(1,2,3,4))
eqn(r$values, p$values)
p <- W$wsmexp; g <- seq(0, 1, length.out = 1001)
r <- morie_wasserman_expectation(g, rep(1, 1001))
eqn(r$estimate, p$estimate); eqn(r$density_mass, p$density_mass)
p <- W$wsmcov; r <- morie_wasserman_covariance(c(1,2,3), c(2,4,6))
eqn(r$estimate, p$estimate); eqn(r$correlation, p$correlation)
p <- W$wsmmrk; r <- morie_wasserman_markov_ineq(3, 2); eqn(r$estimate, p$estimate); eqn(r$raw_bound, p$raw_bound)
p <- W$wsmhfd; r <- morie_wasserman_hoeffding(100, 0.1, 0, 1); eqn(r$estimate, p$estimate)
p <- W$wsmmgf; r <- morie_wasserman_mgf(c(0,1,2), c(0,0.5,1)); eqn(r$values, p$values)
p <- W$wsmcfn; r <- morie_wasserman_char_fn(c(0.3,-2,5.5), c(0.5,1.5)); eqn(r$real, p$real); eqn(r$imag, p$imag)
p <- W$wsmclt; r <- morie_wasserman_clt(c(1,2,3,4)); eqn(r$estimate, p$estimate); eqn(r$sd, p$sd)
p <- W$wsmlln; r <- morie_wasserman_lln(c(2,4,6,1)); eqn(r$running_means, p$running_means); eqn(r$last_gap, p$last_gap)
p <- W$wsmdlm; r <- morie_wasserman_delta_method(3, 0.5, 6); eqn(r$estimate, p$estimate)
p <- W$wsmqtl; r <- morie_wasserman_empirical_quantile(c(3,1,4,2), c(0.25,0.5,0.51,1)); eqn(r$values, p$values)
p <- W$wsmcb; r <- morie_wasserman_dkw_cb(c(1,2,5), 0.05); eqn(r$estimate, p$estimate); eqn(r$lower, p$lower); eqn(r$upper, p$upper)

p <- W$wsmnpb; r <- morie_wasserman_nonparametric_boot(c(1,2,3,4), NULL, 50)
eqn(r$estimate, p$estimate); eqn(r$se, p$se); eqn(r$se_unbiased, p$se_unbiased); eqn(r$replicates_mean, p$replicates_mean)
p <- W$wsmbpc; r <- morie_wasserman_bootstrap_percentile(c(1,2,3,4), NULL, 50, 0.10)
eqn(r$lower, p$lower); eqn(r$upper, p$upper)
p <- W$wsmbpv; r <- morie_wasserman_bootstrap_pivotal(c(1,2,3,4), NULL, 50, 0.10)
eqn(r$lower, p$lower); eqn(r$upper, p$upper)
p <- W$wsmprb; r <- morie_wasserman_parametric_boot(c(1,2,3,4), NULL, NULL, 50)
eqn(r$estimate, p$estimate); eqn(r$se, p$se); eqn(r$replicates_mean, p$replicates_mean)
p <- W$wsmifn; r <- morie_wasserman_influence_function(c(1,2,3,4), NULL)
eqn(r$influence, p$influence); eqn(r$epsilon, p$epsilon)

p <- W$wsmlik; r <- morie_wasserman_likelihood(c(1,2), NULL, 2)
eqn(r$estimate, p$estimate); eqn(r$log_likelihood, p$log_likelihood)
p <- W$wsmllk; r <- morie_wasserman_log_likelihood(c(1,2), NULL, 2)
eqn(r$estimate, p$estimate); eqn(r$per_observation, p$per_observation)
p <- W$wsmcrl; r <- morie_wasserman_cramer_rao(0, 25, 0.25); eqn(r$estimate, p$estimate); eqn(r$se_bound, p$se_bound)
p <- W$wsmfis; r <- morie_wasserman_fisher_info(NULL, 2); eqn(r$estimate, p$estimate); eqn(r$se_one_obs, p$se_one_obs)
p <- W$wsmasm; r <- morie_wasserman_mle_asymptotic(0:99, NULL, 2)
eqn(r$se, p$se); eqn(r$ci_lower, p$ci_lower); eqn(r$ci_upper, p$ci_upper)

p <- W$wsmwhz
Xw <- cbind(1, rep(c(-1, 1), 50)); ew <- rep(c(0.5, -0.5, -0.5, 0.5), 25)
yw <- as.numeric(Xw %*% c(1, 2)) + ew
r <- morie_wasserman_white_huber(Xw, yw)
eqn(r$beta, p$beta); eqn(r$robust_se, p$robust_se); eqn(r$covariance, p$covariance)
p <- W$wsmemt
r <- morie_wasserman_em_algorithm(c(0,0.1,-0.1,0.05,10,10.1,9.9,10.05), c(0.5,-1,11,1,1))
eqn(r$pi, p$pi); eqn(r$mu1, p$mu1); eqn(r$mu2, p$mu2); eqn(r$log_likelihood, p$log_likelihood)
eqn(r$iterations, p$iterations)
p <- W$wsmchi; r <- morie_wasserman_chi_sq_gof(c(10,20,30), c(20,20,20))
eqn(r$estimate, p$estimate); eqn(r$p_value, p$p_value); eqn(r$per_cell, p$per_cell)

p <- W$wsmbay; g <- seq(-5, 5, length.out = 2001)
r <- morie_wasserman_posterior(c(1,0.5,1.5), NULL, list(g, rep(1, 2001)))
eqn(r$estimate, p$estimate); eqn(r$map_theta, p$map_theta); eqn(r$evidence, p$evidence)
p <- W$wsmbcr; g2 <- seq(0, 1, length.out = 10001)
r <- morie_wasserman_credible_interval(list(g2, rep(1, 10001)), 0.10)
eqn(r$lower, p$lower); eqn(r$upper, p$upper); eqn(r$estimate, p$estimate)
p <- W$wsmpst1; r <- morie_wasserman_posterior_mean(list(g2, rep(1, 10001)))
eqn(r$estimate, p$estimate); eqn(r$posterior_sd, p$posterior_sd)
p <- W$bfsd; d <- seq(-3, 3, length.out = 2001) / 3
r <- morie_bayes_factor_savage_dickey(d, 1/6, 0)
eqn(r$estimate, p$estimate); eqn(r$bandwidth, p$bandwidth); eqn(r$posterior_density_at_null, p$posterior_density_at_null)

p <- W$wsment; r <- morie_wasserman_entropy(c(0.5,0.25,0.25)); eqn(r$estimate, p$estimate); eqn(r$bits, p$bits)
p <- W$wsmkbk; r <- morie_wasserman_kullback_leibler(c(0.5,0.5), c(0.25,0.75))
eqn(r$estimate, p$estimate); eqn(r$reverse, p$reverse)
p <- W$wsmmtl; r <- morie_wasserman_mutual_info(c(0,0,1,1), c(0,0,1,1)); eqn(r$estimate, p$estimate); eqn(r$bits, p$bits)
p <- W$wsmodd; r <- morie_wasserman_odds_ratio(rbind(c(30,10), c(15,45)))
eqn(r$estimate, p$estimate); eqn(r$se, p$se); eqn(r$ci_lower, p$ci_lower); eqn(r$ci_upper, p$ci_upper)
p <- W$wsmrrr; r <- morie_wasserman_relative_risk(rbind(c(30,70), c(10,90)))
eqn(r$estimate, p$estimate); eqn(r$se, p$se); eqn(r$ci_upper, p$ci_upper)
p <- W$densty; r <- morie_density(rbind(c(0,1,0), c(1,0,1), c(0,1,0)))
eqn(r$estimate, p$estimate); eqn(r$n_edges, p$n_edges)
p <- W$sgtclo; r <- morie_sgt_closeness_centrality(rbind(c(0,1,0), c(1,0,1), c(0,1,0)))
eqn(r$closeness, p$closeness); eqn(r$argmax, p$argmax)

p <- W$wsmlsr; Xl <- cbind(1, c(0,1,2,4))
r <- morie_wasserman_least_squares(Xl, c(1,3.2,4.9,9.1))
eqn(r$beta, p$beta); eqn(r$se, p$se); eqn(r$rss, p$rss); eqn(r$r_squared, p$r_squared)
p <- W$wsmrgr; r <- morie_wasserman_ridge(cbind(1, c(0,1,2)), c(1,3,5), 0.5)
eqn(r$beta, p$beta); eqn(r$effective_df, p$effective_df); eqn(r$rss, p$rss)
p <- W$wsmlas; r <- morie_wasserman_lasso(diag(2), c(3,-1), 0.5)
eqn(r$beta, p$beta); eqn(r$objective, p$objective); eqn(r$n_nonzero, p$n_nonzero)
p <- W$wsmlgr; r <- morie_wasserman_logistic_regression(matrix(1,4,1), c(1,1,1,0))
eqn(r$beta, p$beta); eqn(r$se, p$se); eqn(r$log_likelihood, p$log_likelihood)
p <- W$wsmpsr; r <- morie_wasserman_poisson_regression(matrix(1,4,1), c(1,2,3,2))
eqn(r$beta, p$beta); eqn(r$se, p$se); eqn(r$log_likelihood, p$log_likelihood); eqn(r$deviance, p$deviance)
p <- W$wsmaic; r <- morie_wasserman_aic(-100, 3); eqn(r$estimate, p$estimate); eqn(r$aic_wasserman, p$aic_wasserman)
p <- W$wsmbic; r <- morie_wasserman_bic(-100, 3, 50); eqn(r$estimate, p$estimate); eqn(r$bic_wasserman, p$bic_wasserman)
p <- W$wsmcvr; Xc <- cbind(1, 0:7); yc <- 1 + 2*(0:7) + rep(c(-0.1, 0.1), 4)
r <- morie_wasserman_kfold_cv(Xc, yc, NULL, 4)
eqn(r$estimate, p$estimate); eqn(r$fold_mse, p$fold_mse); eqn(r$fold_sizes, p$fold_sizes)

p <- W$wsmcrk; r <- morie_wasserman_kernel_regression(c(1.5, 0), c(0,1,2,3), c(1,3,5,7), 0.7)
eqn(r$values, p$values); eqn(r$effective_n, p$effective_n)
p <- W$wsmlpr; r <- morie_wasserman_local_polynomial(1.5, c(0,1,2,3), c(1,3.1,4.8,7.2), 0.7, 1)
eqn(r$values, p$values); eqn(r$derivatives, p$derivatives)
p <- W$wsmsmp; r <- morie_wasserman_smoothing_spline(c(0,1,2,3), c(0,2,0,2), 1)
eqn(r$estimate, p$estimate); eqn(r$effective_df, p$effective_df); eqn(r$rss, p$rss)
p <- W$wsmpca; r <- morie_wasserman_pca(rbind(c(-1,-1), c(0,0), c(1,1.5)), 2)
eqn(r$eigenvalues, p$eigenvalues); eqn(r$components, p$components); eqn(r$scores, p$scores)
p <- W$wsmkmn; r <- morie_wasserman_kmeans(matrix(c(0,0.2,-0.2,10,10.2,9.8), ncol=1), 2)
eqn(r$estimate, p$estimate); eqn(r$labels, p$labels); eqn(sort(r$centers), sort(p$centers))
p <- W$wsmgmm; r <- morie_wasserman_gmm_em(c(0,0.1,-0.1,0.05,10,10.1,9.9,10.05), 2)
eqn(r$estimate, p$estimate); eqn(r$weights, p$weights); eqn(r$means, p$means)

Ah <- rbind(c(0.7,0.3), c(0.4,0.6)); Bh <- rbind(c(0.9,0.1), c(0.2,0.8))
p <- W$wsmhmm; r <- morie_wasserman_hmm_forward(c(0,1,0), Ah, Bh, c(0.6,0.4))
eqn(r$estimate, p$estimate); eqn(r$filtered, p$filtered)
p <- W$wsmvit; r <- morie_wasserman_viterbi(c(0,1,0), Ah, Bh, c(0.6,0.4))
eqn(r$estimate, p$estimate); eqn(r$path, p$path)
p <- W$wsmgib; r <- morie_wasserman_gibbs_sampler(0.9, c(0,0), 200)
eqn(r$estimate, p$estimate); eqn(r$mean_x, p$mean_x); eqn(r$mean_y, p$mean_y)
p <- W$wsmmcm; r <- morie_wasserman_mcmc_metropolis(function(x) exp(-0.5*x*x), 1, 0, 200)
eqn(r$estimate, p$estimate); eqn(r$acceptance_rate, p$acceptance_rate)
p <- W$wsmdir
dag <- list(list(parents = integer(0), cpt = list(0.3)),
            list(parents = 0L, cpt = list(`0` = 0.2, `1` = 0.9)))
r <- morie_wasserman_directed_graph(dag, c(1,1))
eqn(r$estimate, p$estimate); eqn(r$factors, p$factors)
agree <- function(t) if (t[1] == t[2]) 2 else 1
p <- W$wsmund; r <- morie_wasserman_undirected_graph(list(2, list(c(0,1))), list(agree))
eqn(r$estimate, p$estimate); eqn(r$probabilities, p$probabilities)
p <- W$wsmgrp; r <- morie_wasserman_graphical_model(list(2, list(c(0,1))), list(agree))
eqn(r$estimate, p$estimate); eqn(r$mode, p$mode)
p <- W$wsmlgc; r <- morie_wasserman_log_linear(rbind(c(30,10), c(15,45)))
eqn(r$estimate, p$estimate); eqn(r$lambda_int, p$lambda_int); eqn(r$independence_fit, p$independence_fit)
p <- W$wsmbst; r <- morie_wasserman_boosting(matrix(0:3, ncol=1), c(1,-1,1,-1), NULL, 5)
eqn(r$estimate, p$estimate); eqn(r$prediction, p$prediction); eqn(r$rounds_used, p$rounds_used)
p <- W$wsmsvm; r <- morie_wasserman_svm(rbind(c(-2,0), c(-1,0), c(1,0), c(2,0)), c(-1,-1,1,1))
eqn(r$w, p$w); eqn(r$b, p$b); eqn(r$estimate, p$estimate); eqn(r$support_vectors, p$support_vectors)
p <- W$wsmmin; r <- morie_wasserman_minimax(rbind(c(1,4), c(2,2), c(3,1)), c("T1","T2","T3"), c("F1","F2"))
eqn(r$estimate, p$estimate); eqn(r$worst_case, p$worst_case); eqn(r$maximin, p$maximin)
cat(sprintf("%d assertions, %d mismatches\n", N, FAIL)); if (FAIL > 0) quit(status = 1)
