"""Sphinx extension for auto-documenting R functions from Roxygen2 .Rd files.

This extension provides the ``.. r:function::`` directive that reads parsed
.Rd (R Documentation) files generated by ``roxygen2::roxygenise()`` and
renders them as restructuredText inside the Sphinx build.

Usage in .rst files::

    .. r:function:: estimate_ate

The directive looks up ``estimate_ate.Rd`` in the R package's ``man/``
directory, parses the Rd markup, and emits a formatted function
documentation block.

If the .Rd file is not found (e.g. Roxygen2 has not been run), a warning
is emitted and a placeholder note is rendered instead.
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from docutils import nodes
from docutils.parsers.rst import Directive, directives
from docutils.statemachine import StringList
from sphinx.application import Sphinx
from sphinx.domains import Domain
from sphinx.util.docutils import SphinxDirective

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Rd parser — extract sections from Roxygen2-generated .Rd files
# ---------------------------------------------------------------------------

# Regex for top-level Rd sections:  \name{...}, \title{...}, etc.
_SECTION_RE = re.compile(
    r"\\(\w+)\{",
)

# Rd macro for \item{argname}{description}
# NOTE: This simple regex is kept as a fast-path for items without nested braces.
# For items with nested braces, _parse_items_brace_aware() is used instead.
_ITEM_RE = re.compile(r"\\item\{([^}]*)\}\{([^}]*)\}")

# Rd inline markup — NOTE: \eqn and \deqn are handled separately by
# _convert_rd_math() because they require brace-aware parsing for nested
# LaTeX commands like \hat{\mu}, \widehat{ATE}, etc.
_INLINE_SUBS: List[Tuple[re.Pattern, str]] = [
    (re.compile(r"\\code\{([^}]*)\}"), r"``\1``"),
    (re.compile(r"\\emph\{([^}]*)\}"), r"*\1*"),
    (re.compile(r"\\bold\{([^}]*)\}"), r"**\1**"),
    # \eqn and \deqn REMOVED — handled by _convert_rd_math() below
    (re.compile(r"\\link\[=([^\]]*)\]\{([^}]*)\}"), r"``\2``"),
    (re.compile(r"\\link\{([^}]*)\}"), r"``\1``"),
    (re.compile(r"\\href\{([^}]*)\}\{([^}]*)\}"), r"`\2 <\1>`_"),
    (re.compile(r"\\dQuote\{([^}]*)\}"), r'"\1"'),
    (re.compile(r"\\sQuote\{([^}]*)\}"), r"'\1'"),
    (re.compile(r"\\dots"), "..."),
    (re.compile(r"\\ldots"), "..."),
    (re.compile(r"\\R"), "R"),
    (re.compile(r"\\%"), "%"),
    (re.compile(r"\\\\"), r"\\"),
]


def _convert_rd_math(text: str) -> str:
    """Convert \\eqn{} and \\deqn{} to Sphinx math using brace-aware parsing.

    This replaces the old regex approach that broke on nested braces like
    ``\\eqn{\\hat{\\mu}_1(X_i)}``.  Uses :func:`_extract_brace_content`
    to correctly match nested ``{...}`` groups.
    """
    result: list[str] = []
    i = 0
    while i < len(text):
        # Check for \deqn{ first (longer prefix)
        if text[i:].startswith("\\deqn{"):
            content, end = _extract_brace_content(text, i + 5)
            # \deqn{latex}{text-fallback} — skip optional second arg
            if end < len(text) and text[end] == "{":
                _, end = _extract_brace_content(text, end)
            result.append(f"\n\n.. math::\n\n   {content}\n\n")
            i = end
        elif text[i:].startswith("\\eqn{"):
            content, end = _extract_brace_content(text, i + 4)
            # \eqn{latex}{text-fallback} — skip optional second arg
            if end < len(text) and text[end] == "{":
                _, end = _extract_brace_content(text, end)
            result.append(f":math:`{content}`")
            i = end
        else:
            result.append(text[i])
            i += 1
    return "".join(result)


def _clean_rd_text(text: str) -> str:
    """Apply Rd-to-reST inline substitutions.

    Math conversion (``\\eqn``, ``\\deqn``) runs first with brace-aware
    parsing, then simpler regex substitutions handle the rest.
    """
    # First pass: convert LaTeX math with proper nested-brace handling.
    text = _convert_rd_math(text)
    # Second pass: apply remaining inline markup conversions.
    for pattern, replacement in _INLINE_SUBS:
        text = pattern.sub(replacement, text)
    return text.strip()


def _extract_brace_content(text: str, start: int) -> Tuple[str, int]:
    """Extract content from matched braces starting at ``text[start] == '{'``.

    Returns (content, end_index) where end_index is position after closing '}'.
    Handles nested braces.
    """
    if start >= len(text) or text[start] != "{":
        return ("", start)
    depth = 0
    i = start
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return (text[start + 1 : i], i + 1)
        i += 1
    # Unmatched brace — return what we have
    return (text[start + 1 :], len(text))


def parse_rd_file(path: Path) -> Dict[str, Any]:
    """Parse a .Rd file and return a dict of sections.

    Returns a dict with keys like ``name``, ``title``, ``description``,
    ``usage``, ``arguments`` (list of (name, desc) tuples), ``value``,
    ``details``, ``examples``, ``references``, ``seealso``.
    """
    raw = path.read_text(encoding="utf-8", errors="replace")
    result: Dict[str, Any] = {
        "name": "",
        "alias": [],
        "title": "",
        "description": "",
        "usage": "",
        "arguments": [],
        "value": "",
        "details": "",
        "examples": "",
        "references": "",
        "seealso": "",
        "section": {},
    }

    # Walk through the file extracting top-level \section{content}
    i = 0
    while i < len(raw):
        m = _SECTION_RE.search(raw, i)
        if m is None:
            break
        tag = m.group(1)
        content, end = _extract_brace_content(raw, m.end() - 1)
        i = end

        if tag == "name":
            result["name"] = content.strip()
        elif tag == "alias":
            result["alias"].append(content.strip())
        elif tag == "title":
            result["title"] = content.strip()
        elif tag == "description":
            result["description"] = content.strip()
        elif tag == "usage":
            result["usage"] = content.strip()
        elif tag == "arguments":
            # Parse \item{name}{desc} with brace-aware extraction to handle
            # nested braces in descriptions (e.g., \item{x}{A \code{data.frame}}).
            j = 0
            while j < len(content):
                item_start = content.find("\\item{", j)
                if item_start == -1:
                    break
                arg_name, after_name = _extract_brace_content(content, item_start + 5)
                if after_name < len(content) and content[after_name] == "{":
                    arg_desc, after_desc = _extract_brace_content(content, after_name)
                    result["arguments"].append(
                        (arg_name.strip(), arg_desc.strip())
                    )
                    j = after_desc
                else:
                    result["arguments"].append((arg_name.strip(), ""))
                    j = after_name
        elif tag == "value":
            result["value"] = content.strip()
        elif tag == "details":
            result["details"] = content.strip()
        elif tag == "examples":
            result["examples"] = content.strip()
        elif tag == "references":
            result["references"] = content.strip()
        elif tag == "seealso":
            result["seealso"] = content.strip()
        elif tag == "section":
            # Named sub-section: \section{SectionName}{content}
            sec_content, end2 = _extract_brace_content(raw, end)
            result["section"][content.strip()] = sec_content.strip()
            i = end2

    return result


# ---------------------------------------------------------------------------
# Sphinx directive: .. r:function:: function_name
# ---------------------------------------------------------------------------


class RFunctionDirective(SphinxDirective):
    """Render documentation for an R function from its .Rd file.

    Usage::

        .. r:function:: estimate_ate

    Options:

    - ``:no-examples:`` — suppress the Examples section
    - ``:no-value:`` — suppress the Value/Returns section
    """

    has_content = False
    required_arguments = 1
    optional_arguments = 0
    option_spec = {
        "no-examples": directives.flag,
        "no-value": directives.flag,
    }

    def run(self) -> List[nodes.Node]:
        func_name = self.arguments[0].strip()
        env = self.state.document.settings.env
        config = env.config

        # Resolve the man/ directory
        man_dir = Path(config.r_man_dir) if config.r_man_dir else None
        if man_dir is None or not man_dir.is_dir():
            warning = self.state_machine.reporter.warning(
                f"R man/ directory not found at {man_dir}; "
                f"cannot render documentation for {func_name}(). "
                f"Run 'Rscript -e \"devtools::document()\"' in the R package directory.",
                line=self.lineno,
            )
            return [warning]

        rd_path = man_dir / f"{func_name}.Rd"
        if not rd_path.is_file():
            # Try to find it via alias scanning — sometimes Rd filenames
            # differ from function names
            rd_path = _find_rd_by_alias(man_dir, func_name)

        if rd_path is None or not rd_path.is_file():
            note = nodes.note()
            note += nodes.paragraph(
                text=f"Documentation for R function {func_name}() is pending. "
                f"Run roxygen2 to generate the .Rd file."
            )
            return [note]

        parsed = parse_rd_file(rd_path)
        rst_lines = self._render_rst(func_name, parsed)

        # Parse the generated RST through Sphinx's state machine
        vl = StringList(rst_lines, source=str(rd_path))
        node = nodes.section()
        node.document = self.state.document
        self.state.nested_parse(vl, self.content_offset, node)
        return node.children

    def _render_rst(
        self, func_name: str, parsed: Dict[str, Any]
    ) -> List[str]:
        """Convert parsed Rd data to RST lines."""
        lines: List[str] = []

        # Section anchor
        lines.append(f".. _r-{func_name}:")
        lines.append("")

        # Title
        title = _clean_rd_text(parsed.get("title", func_name))
        lines.append(f"``{func_name}()``")
        lines.append("~" * (len(func_name) + 4))
        lines.append("")

        # Description — split into lines so RST directives (.. math::) are parsed.
        desc = _clean_rd_text(parsed.get("description", ""))
        if desc:
            for dline in desc.splitlines():
                lines.append(dline)
            lines.append("")

        # Usage
        usage = parsed.get("usage", "")
        if usage:
            lines.append("**Usage**")
            lines.append("")
            lines.append(".. code-block:: r")
            lines.append("")
            for uline in usage.splitlines():
                lines.append(f"   {uline}")
            lines.append("")

        # Arguments
        args = parsed.get("arguments", [])
        if args:
            lines.append("**Arguments**")
            lines.append("")
            for arg_name, arg_desc in args:
                clean_desc = _clean_rd_text(arg_desc)
                lines.append(f"``{arg_name}``")
                lines.append(f"   {clean_desc}")
                lines.append("")

        # Value / Returns
        if "no-value" not in self.options:
            value = _clean_rd_text(parsed.get("value", ""))
            if value:
                lines.append("**Returns**")
                lines.append("")
                lines.append(f"   {value}")
                lines.append("")

        # Details
        details = _clean_rd_text(parsed.get("details", ""))
        if details:
            lines.append("**Details**")
            lines.append("")
            for dline in details.splitlines():
                lines.append(dline)
            lines.append("")

        # References
        refs = _clean_rd_text(parsed.get("references", ""))
        if refs:
            lines.append("**References**")
            lines.append("")
            lines.append(refs)
            lines.append("")

        # Examples
        if "no-examples" not in self.options:
            examples = parsed.get("examples", "")
            if examples:
                lines.append("**Examples**")
                lines.append("")
                lines.append(".. code-block:: r")
                lines.append("")
                for eline in examples.splitlines():
                    lines.append(f"   {eline}")
                lines.append("")

        return lines


def _find_rd_by_alias(man_dir: Path, func_name: str) -> Optional[Path]:
    """Scan .Rd files in man_dir for one that declares func_name as an alias."""
    for rd_file in man_dir.glob("*.Rd"):
        try:
            text = rd_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if re.search(rf"\\alias\{{{re.escape(func_name)}\}}", text):
            return rd_file
    return None


# ---------------------------------------------------------------------------
# Category classification for auto-grouping R functions
# ---------------------------------------------------------------------------

# Map function name prefixes/patterns to display categories.
# Order matters — first match wins.
_CATEGORY_RULES: List[Tuple[re.Pattern, str]] = [
    (re.compile(r"^estimate_(propensity|ate|att|atc|aipw|gate|cate|late|irm|g_comp)"), "Causal Inference"),
    (re.compile(r"^(sensitivity_rosenbaum|e_value)$"), "Causal Inference"),
    (re.compile(r"^(two_sample_t|one_sample_t|paired_t|chi_square|fisher_exact|anova|kruskal|mann_whitney|wilcoxon|shapiro|levene)"), "Frequentist Inference"),
    (re.compile(r"^(proportion_ci|odds_ratio|risk_ratio|risk_difference)"), "Frequentist Inference"),
    (re.compile(r"^(cohens_d|hedges_g|eta_squared|omega_squared|cramers_v|spearman|kendall|point_biserial)"), "Frequentist Inference"),
    (re.compile(r"^(power_|sample_size_)"), "Frequentist Inference"),
    (re.compile(r"^(simple_random|stratified_sample|cluster_sample|pps_sample|bootstrap|jackknife|effective_sample|design_effect|compute_design|calibration)"), "Sampling Design"),
    (re.compile(r"^(list_moirais|run_moirais|run_pipeline|canonicalize_cpads|load_cpads)"), "Module Runners"),
    (re.compile(r"^(read_outputs|build_outputs|validate_outputs|audit_public|summarize_output)"), "Manifest and Audit"),
    (re.compile(r"^(run_workflow|default_workflow)"), "Workflow"),
    (re.compile(r"^(validate_cpads|cpads_contract)"), "CPADS Data"),
    (re.compile(r"^(generate_synthetic|write_synthetic|default_synthetic)"), "Synthetic Data"),
    (re.compile(r"^run_(propensity_ipw|ebac_selection)"), "IPW Helpers"),
    (re.compile(r"^(moirais_paths|epiml_paths|find_project)"), "Paths and Project"),
    (re.compile(r"^(moirais_assistant|build_assistant)"), "Assistant Bridge"),
]

# Preferred display order for categories.
_CATEGORY_ORDER = [
    "Causal Inference",
    "Frequentist Inference",
    "Sampling Design",
    "Module Runners",
    "Manifest and Audit",
    "Workflow",
    "CPADS Data",
    "Synthetic Data",
    "IPW Helpers",
    "Paths and Project",
    "Assistant Bridge",
]


def _classify_function(func_name: str) -> str:
    """Return the display category for a function name."""
    for pattern, category in _CATEGORY_RULES:
        if pattern.search(func_name):
            return category
    return "Other"


# ---------------------------------------------------------------------------
# Sphinx directive: .. r:autopackage::
# ---------------------------------------------------------------------------


class RAutoPackageDirective(SphinxDirective):
    """Auto-document all R functions from the package's man/ directory.

    Scans every ``.Rd`` file, groups functions by category, and renders
    them in a structured layout.  No manual function listing needed.

    Usage::

        .. r:autopackage::

    Options:

    - ``:no-examples:`` — suppress Examples sections globally
    - ``:no-internal:`` — skip functions marked ``\\keyword{internal}``
    """

    has_content = False
    required_arguments = 0
    optional_arguments = 0
    option_spec = {
        "no-examples": directives.flag,
        "no-internal": directives.flag,
    }

    def run(self) -> List[nodes.Node]:
        env = self.state.document.settings.env
        config = env.config

        man_dir = Path(config.r_man_dir) if config.r_man_dir else None
        if man_dir is None or not man_dir.is_dir():
            warning = self.state_machine.reporter.warning(
                f"R man/ directory not found at {man_dir}; "
                f"cannot auto-document R package. "
                f"Run 'Rscript -e \"devtools::document()\"' first.",
                line=self.lineno,
            )
            return [warning]

        # Collect all .Rd files
        rd_files = sorted(man_dir.glob("*.Rd"))
        if not rd_files:
            note = nodes.note()
            note += nodes.paragraph(
                text="No .Rd files found in man/. "
                "Run roxygen2 to generate R documentation."
            )
            return [note]

        skip_internal = "no-internal" in self.options
        suppress_examples = "no-examples" in self.options

        # Parse and categorise
        categorised: Dict[str, List[Tuple[str, Dict[str, Any]]]] = {}
        for rd_path in rd_files:
            parsed = parse_rd_file(rd_path)
            func_name = parsed.get("name", rd_path.stem)
            if not func_name:
                func_name = rd_path.stem

            # Skip internal functions if requested
            if skip_internal:
                keywords_section = parsed.get("section", {})
                raw_text = rd_path.read_text(encoding="utf-8", errors="replace")
                if "\\keyword{internal}" in raw_text:
                    continue

            category = _classify_function(func_name)
            categorised.setdefault(category, []).append((func_name, parsed))

        # Build RST output in category order
        rst_lines: List[str] = []

        # Ordered categories first, then any extras alphabetically
        ordered_cats = [c for c in _CATEGORY_ORDER if c in categorised]
        extra_cats = sorted(set(categorised) - set(_CATEGORY_ORDER))
        all_cats = ordered_cats + extra_cats

        for cat in all_cats:
            funcs = categorised[cat]
            # Sort functions alphabetically within each category
            funcs.sort(key=lambda x: x[0])

            rst_lines.append("")
            rst_lines.append("----")
            rst_lines.append("")
            rst_lines.append(cat)
            rst_lines.append("-" * len(cat))
            rst_lines.append("")

            for func_name, parsed in funcs:
                func_rst = self._render_function(func_name, parsed, suppress_examples)
                rst_lines.extend(func_rst)

        # Parse through Sphinx state machine
        vl = StringList(rst_lines, source="r:autopackage")
        node = nodes.section()
        node.document = self.state.document
        self.state.nested_parse(vl, self.content_offset, node)
        return node.children

    def _render_function(
        self, func_name: str, parsed: Dict[str, Any], suppress_examples: bool
    ) -> List[str]:
        """Render a single function's RST (reuses RFunctionDirective logic)."""
        lines: List[str] = []

        # Section anchor
        lines.append(f".. _r-{func_name}:")
        lines.append("")

        # Title
        lines.append(f"``{func_name}()``")
        lines.append("~" * (len(func_name) + 4))
        lines.append("")

        # Description — split into lines so RST directives (.. math::) are parsed.
        desc = _clean_rd_text(parsed.get("description", ""))
        if desc:
            for dline in desc.splitlines():
                lines.append(dline)
            lines.append("")

        # Usage
        usage = parsed.get("usage", "")
        if usage:
            lines.append("**Usage**")
            lines.append("")
            lines.append(".. code-block:: r")
            lines.append("")
            for uline in usage.splitlines():
                lines.append(f"   {uline}")
            lines.append("")

        # Arguments
        args = parsed.get("arguments", [])
        if args:
            lines.append("**Arguments**")
            lines.append("")
            for arg_name, arg_desc in args:
                clean_desc = _clean_rd_text(arg_desc)
                lines.append(f"``{arg_name}``")
                lines.append(f"   {clean_desc}")
                lines.append("")

        # Value / Returns
        value = _clean_rd_text(parsed.get("value", ""))
        if value:
            lines.append("**Returns**")
            lines.append("")
            lines.append(f"   {value}")
            lines.append("")

        # Details
        details = _clean_rd_text(parsed.get("details", ""))
        if details:
            lines.append("**Details**")
            lines.append("")
            for dline in details.splitlines():
                lines.append(dline)
            lines.append("")

        # References
        refs = _clean_rd_text(parsed.get("references", ""))
        if refs:
            lines.append("**References**")
            lines.append("")
            lines.append(refs)
            lines.append("")

        # Examples
        if not suppress_examples:
            examples = parsed.get("examples", "")
            if examples:
                lines.append("**Examples**")
                lines.append("")
                lines.append(".. code-block:: r")
                lines.append("")
                for eline in examples.splitlines():
                    lines.append(f"   {eline}")
                lines.append("")

        return lines


# ---------------------------------------------------------------------------
# Pre-build hook: run roxygen2 to regenerate .Rd files
# ---------------------------------------------------------------------------


def _run_roxygen_prebuild(app: Sphinx) -> None:
    """Run ``Rscript -e 'devtools::document()'`` before Sphinx builds.

    This ensures .Rd files in man/ are up-to-date with Roxygen2 comments.
    Fails gracefully (warning only) if R or devtools is unavailable.
    """
    r_pkg_dir = app.config.r_package_dir
    if not r_pkg_dir:
        logger.info("r_package_dir not set; skipping Roxygen2 pre-build.")
        return

    r_pkg_path = Path(r_pkg_dir)
    if not r_pkg_path.is_dir():
        logger.warning("R package directory %s does not exist.", r_pkg_dir)
        return

    # Check if DESCRIPTION exists (required for devtools::document)
    if not (r_pkg_path / "DESCRIPTION").is_file():
        logger.warning(
            "No DESCRIPTION file in %s; skipping Roxygen2.", r_pkg_dir
        )
        return

    logger.info("Running Roxygen2 on %s ...", r_pkg_dir)
    try:
        result = subprocess.run(
            [
                "Rscript",
                "-e",
                f'devtools::document("{r_pkg_path.as_posix()}")',
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0:
            logger.info("Roxygen2 completed successfully.")
            if result.stderr:
                # Roxygen2 writes progress to stderr
                for line in result.stderr.strip().splitlines():
                    logger.debug("  roxygen2: %s", line)
        else:
            logger.warning(
                "Roxygen2 returned non-zero exit code %d. "
                "R API documentation may be stale.\n"
                "stderr: %s",
                result.returncode,
                result.stderr[:500],
            )
    except FileNotFoundError:
        logger.warning(
            "Rscript not found on PATH. "
            "Install R and devtools to auto-generate R API documentation. "
            "Sphinx build will continue with existing .Rd files (if any)."
        )
    except subprocess.TimeoutExpired:
        logger.warning("Roxygen2 timed out after 120 seconds; skipping.")
    except Exception as exc:
        logger.warning("Roxygen2 pre-build failed: %s", exc)


# ---------------------------------------------------------------------------
# Sphinx extension setup
# ---------------------------------------------------------------------------


def setup(app: Sphinx) -> Dict[str, Any]:
    """Register the r_autodoc extension with Sphinx."""

    # Configuration values
    app.add_config_value("r_package_dir", default="", rebuild="html")
    app.add_config_value("r_man_dir", default="", rebuild="html")

    # Register the directives via a proper Sphinx domain so the
    # ``r:`` prefix is recognized at parse time. (Plain
    # app.add_directive("r:autopackage", ...) is treated as a single
    # directive name with a colon, which Sphinx's parser interprets
    # as a domain reference and therefore can't find.)
    class _RDomain(Domain):
        name = "r"
        label = "R"
        directives = {
            "function": RFunctionDirective,
            "autopackage": RAutoPackageDirective,
        }
        roles: dict = {}
        initial_data: dict = {}

    app.add_domain(_RDomain)

    # Pre-build hook
    app.connect("builder-inited", _run_roxygen_prebuild)

    return {
        "version": "0.1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
