"""Regionalization: SKATER (spdep::skater), REDCAP, constrained hierarchical clustering, AZP and max-p."""

import math

from morie.fn._regcore import ssd
from morie.fn._rng import random_uniform
from morie.fn.azpreg import automatic_zoning
from morie.fn.maxpreg import max_p_regions
from morie.fn.redcap import redcap
from morie.fn.schcreg import constrained_hierarchical
from morie.fn.skater import skater

PINS = {
    "skater": {
        "2_1": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
        ],
        "2_5": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
        ],
        "4_1": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            2,
            2,
            2,
            1,
            1,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
        ],
        "4_5": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            2,
            2,
            2,
            1,
            1,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
        ],
        "6_1": [
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            2,
            2,
            2,
            1,
            4,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            5,
            5,
            5,
            5,
            1,
            3,
            3,
            5,
            5,
            5,
            5,
            1,
            3,
            3,
        ],
        "6_5": [
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            2,
            2,
            2,
            1,
            1,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            5,
            5,
            5,
            5,
            1,
            3,
            3,
            5,
            5,
            5,
            5,
            1,
            3,
            3,
        ],
    },
    "redcap": {
        "single": [
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            0,
            0,
            0,
            4,
            4,
            4,
            0,
            0,
            0,
            0,
            4,
            4,
            3,
            0,
            2,
            2,
            2,
            1,
            4,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
            2,
            2,
            2,
            2,
            1,
            3,
            3,
        ],
        "complete": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            3,
            0,
            2,
            2,
            2,
            1,
            1,
            3,
            2,
            2,
            2,
            2,
            4,
            4,
            3,
            2,
            2,
            2,
            2,
            4,
            4,
            4,
            2,
            2,
            2,
            2,
            4,
            4,
            4,
        ],
        "average": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            3,
            0,
            2,
            2,
            2,
            1,
            1,
            3,
            2,
            2,
            2,
            2,
            4,
            4,
            3,
            2,
            2,
            2,
            2,
            4,
            4,
            4,
            2,
            2,
            2,
            2,
            4,
            4,
            4,
        ],
        "ward": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            4,
            0,
            2,
            2,
            2,
            1,
            1,
            4,
            2,
            2,
            2,
            2,
            3,
            3,
            4,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
            2,
            2,
            2,
            2,
            3,
            3,
            3,
        ],
    },
    "first": [
        0,
        0,
        0,
        0,
        4,
        4,
        4,
        0,
        0,
        0,
        0,
        4,
        4,
        4,
        0,
        0,
        0,
        0,
        4,
        4,
        3,
        0,
        2,
        2,
        2,
        1,
        4,
        3,
        2,
        2,
        2,
        2,
        1,
        3,
        3,
        2,
        2,
        2,
        2,
        1,
        3,
        3,
        2,
        2,
        2,
        2,
        1,
        3,
        3,
    ],
    "schc": {
        "single": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            2,
            0,
            0,
            0,
            0,
            3,
            1,
            2,
            0,
            0,
            0,
            0,
            3,
            4,
            2,
            0,
            0,
            0,
            0,
            3,
            4,
            4,
            0,
            0,
            0,
            0,
            3,
            4,
            4,
        ],
        "complete": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            2,
            0,
            3,
            3,
            3,
            4,
            4,
            2,
            3,
            3,
            3,
            3,
            4,
            4,
            2,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
        ],
        "average": [
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            1,
            1,
            2,
            0,
            3,
            3,
            3,
            1,
            1,
            2,
            3,
            3,
            3,
            3,
            1,
            4,
            2,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
        ],
        "ward": [
            0,
            0,
            0,
            0,
            1,
            2,
            2,
            0,
            0,
            0,
            0,
            1,
            2,
            2,
            0,
            0,
            0,
            0,
            1,
            2,
            2,
            0,
            3,
            3,
            3,
            1,
            1,
            2,
            3,
            3,
            3,
            3,
            1,
            4,
            2,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
        ],
    },
    "azp": {
        "0": [
            0,
            0,
            0,
            0,
            2,
            2,
            2,
            0,
            0,
            0,
            0,
            2,
            2,
            2,
            0,
            0,
            0,
            0,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            1,
            2,
            2,
            3,
            3,
            3,
            3,
            1,
            1,
            1,
            4,
            4,
            4,
            4,
            1,
            1,
            1,
            4,
            4,
            4,
            4,
            1,
            1,
            1,
        ],
        "1": [
            0,
            2,
            2,
            2,
            1,
            1,
            1,
            0,
            2,
            2,
            2,
            1,
            1,
            1,
            0,
            0,
            2,
            2,
            1,
            1,
            1,
            0,
            4,
            4,
            4,
            3,
            1,
            1,
            4,
            4,
            4,
            4,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            3,
            3,
            3,
        ],
    },
    "balance": [
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        0,
        0,
        2,
        2,
        2,
        1,
        1,
        0,
        0,
        2,
        2,
        2,
        2,
        1,
        0,
        4,
        4,
        4,
        2,
        1,
        1,
        0,
        4,
        4,
        4,
        2,
        1,
        1,
        4,
        4,
        3,
        4,
        3,
        3,
        3,
        4,
        3,
        3,
        3,
        3,
        3,
        3,
    ],
    "maxp": {
        "10": [
            1,
            4,
            4,
            4,
            3,
            8,
            8,
            1,
            1,
            4,
            5,
            3,
            8,
            8,
            1,
            5,
            5,
            5,
            3,
            8,
            10,
            11,
            7,
            7,
            7,
            3,
            3,
            10,
            11,
            11,
            7,
            7,
            9,
            0,
            10,
            11,
            6,
            6,
            6,
            9,
            0,
            0,
            2,
            2,
            2,
            2,
            9,
            0,
            0,
        ],
        "20": [
            0,
            0,
            0,
            0,
            3,
            3,
            3,
            5,
            0,
            0,
            0,
            3,
            3,
            3,
            5,
            5,
            0,
            0,
            3,
            3,
            3,
            5,
            5,
            1,
            1,
            3,
            3,
            3,
            5,
            4,
            1,
            1,
            1,
            2,
            2,
            4,
            4,
            1,
            4,
            2,
            2,
            2,
            4,
            4,
            4,
            4,
            2,
            2,
            2,
        ],
    },
}


def lattice():
    nr, n = 7, 49
    U = [float(u) for u in random_uniform(3 * n, seed=21, stream=0)]
    X = [
        [
            math.sin((i % nr + 1) / 2) + 0.3 * U[3 * i],
            math.cos((i // nr + 1) / 3) + 0.3 * U[3 * i + 1],
            (1.5 if i % nr + 1 > 4 else 0.0) + 0.2 * U[3 * i + 2],
        ]
        for i in range(n)
    ]
    nb = []
    for i in range(n):
        r = [i - 1] if i % nr else []
        r += [i + 1] if i % nr != nr - 1 else []
        r += [i - nr] if i >= nr else []
        r += [i + nr] if i + nr < n else []
        nb.append(sorted(r))
    return X, nb, [1 + (i * 7) % 5 for i in range(n)]


def contiguous(labels, nb):
    for r in set(labels):
        mem = [i for i in range(len(labels)) if labels[i] == r]
        seen, stack = {mem[0]}, [mem[0]]
        while stack:
            u = stack.pop()
            for v in nb[u]:
                if labels[v] == r and v not in seen:
                    seen.add(v)
                    stack.append(v)
        if len(seen) != len(mem):
            return False
    return True


def test_skater_matches_spdep_and_is_contiguous():
    X, nb, _ = lattice()
    for k in (2, 4, 6):
        for ms in (1, 5):
            r = skater(X, nb, k, min_size=ms)
            assert r["labels"] == PINS["skater"][f"{k}_{ms}"]  # identical to spdep::skater (R test)
            assert contiguous(r["labels"], nb) and r["n_regions"] == k
            assert min(r["labels"].count(g) for g in range(k)) >= ms
            assert all(a >= b for a, b in zip(r["ssw"], r["ssw"][1:]))
    sq = skater(X, nb, 4, squared=True)
    tot = sum(ssd(X, [i for i in range(49) if sq["labels"][i] == g]) for g in range(4))
    assert abs(sq["ssw"][-1] - tot) < 1e-12


def test_redcap_and_constrained_hierarchical():
    X, nb, _ = lattice()
    for lk in ("single", "complete", "average", "ward"):
        r = redcap(X, nb, 5, linkage=lk)
        assert r["labels"] == PINS["redcap"][lk] and contiguous(r["labels"], nb) and len(r["tree"]) == 48
        assert abs(r["ssd"][-1] - sum(ssd(X, [i for i in range(49) if r["labels"][i] == g]) for g in range(5))) < 1e-12
        s = constrained_hierarchical(X, nb, 5, linkage=lk)
        assert s["labels"] == PINS["schc"][lk] and contiguous(s["labels"], nb) and len(set(s["labels"])) == 5
    first = redcap(X, nb, 5, linkage="single", order="first")
    assert first["labels"] == PINS["first"]
    tree = first["tree"]  # first-order single linkage builds the minimum spanning tree
    w = sum(math.dist(X[a], X[b]) ** 2 for a, b in tree)
    assert len(tree) == 48 and w <= sum(math.dist(X[a], X[b]) ** 2 for a, b in skater(X, nb, 1)["mst"]) + 1e-12


def test_azp_improves_and_balances():
    X, nb, pop = lattice()
    for sd in (0, 1):
        r = automatic_zoning(X, nb, 5, seed=sd)
        assert r["labels"] == PINS["azp"][str(sd)] and contiguous(r["labels"], nb) and len(set(r["labels"])) == 5
        start = sum(ssd(X, [i for i in range(49) if r["initial"][i] == g]) for g in range(5))
        assert (
            r["objective"] <= start
            and abs(r["objective"] - sum(ssd(X, [i for i in range(49) if r["labels"][i] == g]) for g in range(5)))
            < 1e-12
        )
    b = automatic_zoning(X, nb, 5, objective="balance", weights=pop, seed=1)
    assert b["labels"] == PINS["balance"] and contiguous(b["labels"], nb)
    tots = sorted(sum(pop[i] for i in range(49) if b["labels"][i] == g) for g in range(5))
    assert tots == [28, 28, 30, 30, 30] and abs(b["objective"] - 4.8) < 1e-12


def test_max_p_regions_meet_the_threshold():
    X, nb, pop = lattice()
    for th, p in ((10, 12), (20, 6)):
        r = max_p_regions(X, nb, pop, th, n_construct=20, seed=2)
        assert (
            r["labels"] == PINS["maxp"][str(th)]
            and r["p"] == p
            and min(r["region_weights"]) >= th
            and contiguous(r["labels"], nb)
        )
    grid = [
        [
            j
            for j in (
                i - 1 if i % 3 else None,
                i + 1 if i % 3 != 2 else None,
                i - 3 if i >= 3 else None,
                i + 3 if i < 6 else None,
            )
            if j is not None
        ]
        for i in range(9)
    ]
    assert max_p_regions([[float(i)] for i in range(9)], grid, [1] * 9, 2)["p"] == 4  # 9 units, 2 per region: at most 4


def test_redcap_respects_region_floors():
    X, nb, pop = lattice()
    free = redcap(X, nb, 6, linkage="ward")["labels"]
    assert min(free.count(g) for g in range(6)) == 3
    r = redcap(X, nb, 6, linkage="ward", min_size=5)["labels"]
    assert min(r.count(g) for g in range(6)) >= 5 and contiguous(r, nb)
    r = redcap(X, nb, 6, linkage="ward", weights=pop, min_weight=12)["labels"]
    assert min(sum(pop[i] for i in range(49) if r[i] == g) for g in range(6)) >= 12
    assert redcap(X, nb, 8, linkage="ward", min_size=5)["n_regions"] == 7  # no further cut keeps both sides at 5
