# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.morie_sha256_impl <- function(data) {
    .Call(`_morie_morie_crypto_sha256_native`, data)
}

.morie_sha256_hex_impl <- function(data) {
    .Call(`_morie_morie_crypto_sha256_hex_native`, data)
}

.morie_hmac_sha256_impl <- function(key, msg) {
    .Call(`_morie_morie_crypto_hmac_sha256_native`, key, msg)
}

.morie_pbkdf2_sha256_impl <- function(password, salt, iterations, dklen) {
    .Call(`_morie_morie_crypto_pbkdf2_sha256_native`, password, salt, iterations, dklen)
}

.morie_blake2b_impl <- function(data, outlen, key = NULL) {
    .Call(`_morie_morie_crypto_blake2b_native`, data, outlen, key)
}

.morie_argon2_impl <- function(password, salt, memory, passes, parallelism, tag_length, variant, secret = NULL, associated = NULL) {
    .Call(`_morie_morie_crypto_argon2_native`, password, salt, memory, passes, parallelism, tag_length, variant, secret, associated)
}

.morie_crypto_liboqs_available <- function() {
    .Call(`_morie_morie_crypto_liboqs_available`)
}

.morie_crypto_liboqs_version <- function() {
    .Call(`_morie_morie_crypto_liboqs_version`)
}

.morie_crypto_mlkem768_keygen <- function() {
    .Call(`_morie_morie_crypto_mlkem768_keygen`)
}

.morie_crypto_mlkem768_encaps <- function(pk_sxp) {
    .Call(`_morie_morie_crypto_mlkem768_encaps`, pk_sxp)
}

.morie_crypto_mlkem768_decaps <- function(sk_sxp, ct_sxp) {
    .Call(`_morie_morie_crypto_mlkem768_decaps`, sk_sxp, ct_sxp)
}

.morie_crypto_mldsa65_keygen <- function() {
    .Call(`_morie_morie_crypto_mldsa65_keygen`)
}

.morie_crypto_mldsa65_sign <- function(sk_sxp, message_sxp) {
    .Call(`_morie_morie_crypto_mldsa65_sign`, sk_sxp, message_sxp)
}

.morie_crypto_mldsa65_verify <- function(pk_sxp, message_sxp, signature_sxp) {
    .Call(`_morie_morie_crypto_mldsa65_verify`, pk_sxp, message_sxp, signature_sxp)
}

.morie_slhdsa128s_keygen_impl <- function() {
    .Call(`_morie_morie_crypto_slhdsa128s_keygen`)
}

.morie_slhdsa128s_sign_impl <- function(sk_sxp, message_sxp) {
    .Call(`_morie_morie_crypto_slhdsa128s_sign`, sk_sxp, message_sxp)
}

.morie_slhdsa128s_verify_impl <- function(pk_sxp, message_sxp, signature_sxp) {
    .Call(`_morie_morie_crypto_slhdsa128s_verify`, pk_sxp, message_sxp, signature_sxp)
}

.morie_hqc128_keygen_impl <- function() {
    .Call(`_morie_morie_crypto_hqc128_keygen`)
}

.morie_hqc128_encaps_impl <- function(pk_sxp) {
    .Call(`_morie_morie_crypto_hqc128_encaps`, pk_sxp)
}

.morie_hqc128_decaps_impl <- function(sk_sxp, ct_sxp) {
    .Call(`_morie_morie_crypto_hqc128_decaps`, sk_sxp, ct_sxp)
}

.morie_crypto_sodium_available <- function() {
    .Call(`_morie_morie_crypto_sodium_available`)
}

.morie_crypto_sodium_version <- function() {
    .Call(`_morie_morie_crypto_sodium_version`)
}

.morie_chacha20poly1305_encrypt_impl <- function(key_sxp, nonce_sxp, plaintext_sxp, aad_sxp) {
    .Call(`_morie_morie_crypto_chacha20poly1305_encrypt`, key_sxp, nonce_sxp, plaintext_sxp, aad_sxp)
}

.morie_chacha20poly1305_decrypt_impl <- function(key_sxp, nonce_sxp, ct_with_tag_sxp, aad_sxp) {
    .Call(`_morie_morie_crypto_chacha20poly1305_decrypt`, key_sxp, nonce_sxp, ct_with_tag_sxp, aad_sxp)
}

.morie_crypto_hkdf_sha256 <- function(ikm_sxp, length_sxp, salt_sxp, info_sxp) {
    .Call(`_morie_morie_crypto_hkdf_sha256`, ikm_sxp, length_sxp, salt_sxp, info_sxp)
}

.morie_crypto_random_bytes <- function(n) {
    .Call(`_morie_morie_crypto_random_bytes`, n)
}

.morie_twfe_demean_cpp <- function(M, g1, g2, K1, K2, tol = 1e-11, max_iter = 500L) {
    .Call(`_morie_morie_twfe_demean_cpp`, M, g1, g2, K1, K2, tol, max_iter)
}

morie_dsp_lms_cpp <- function(x, d, order, mu) {
    .Call(`_morie_morie_dsp_lms_cpp`, x, d, order, mu)
}

morie_dsp_nlms_cpp <- function(x, d, order, mu, eps) {
    .Call(`_morie_morie_dsp_nlms_cpp`, x, d, order, mu, eps)
}

morie_dsp_rls_cpp <- function(x, d, order, lam, delta) {
    .Call(`_morie_morie_dsp_rls_cpp`, x, d, order, lam, delta)
}

morie_dsp_cross_correlation_cpp <- function(x, y, max_lag) {
    .Call(`_morie_morie_dsp_cross_correlation_cpp`, x, y, max_lag)
}

morie_dsp_median_filter_cpp <- function(x, kernel_size) {
    .Call(`_morie_morie_dsp_median_filter_cpp`, x, kernel_size)
}

morie_normal_pdf_cpp <- function(x, mean, sd) {
    .Call(`_morie_morie_normal_pdf_cpp`, x, mean, sd)
}

morie_mean_cpp <- function(x) {
    .Call(`_morie_morie_mean_cpp`, x)
}

morie_var_cpp <- function(x, ddof = 1L) {
    .Call(`_morie_morie_var_cpp`, x, ddof)
}

morie_cor_pearson_cpp <- function(x, y) {
    .Call(`_morie_morie_cor_pearson_cpp`, x, y)
}

morie_hawkes_ll_exp_const_cpp <- function(t, T_horizon, a0, eta, beta) {
    .Call(`_morie_morie_hawkes_ll_exp_const_cpp`, t, T_horizon, a0, eta, beta)
}

morie_hawkes_ll_weibull_const_cpp <- function(t, T_horizon, a0, eta, alpha, lam) {
    .Call(`_morie_morie_hawkes_ll_weibull_const_cpp`, t, T_horizon, a0, eta, alpha, lam)
}

morie_hawkes_ll_lomax_const_cpp <- function(t, T_horizon, a0, eta, alpha, c) {
    .Call(`_morie_morie_hawkes_ll_lomax_const_cpp`, t, T_horizon, a0, eta, alpha, c)
}

morie_hawkes_ll_gamma_const_cpp <- function(t, T_horizon, a0, eta, alpha, beta) {
    .Call(`_morie_morie_hawkes_ll_gamma_const_cpp`, t, T_horizon, a0, eta, alpha, beta)
}

morie_hawkes_kernel_density_cpp <- function(u, kind, psi) {
    .Call(`_morie_morie_hawkes_kernel_density_cpp`, u, kind, psi)
}

morie_hawkes_kernel_cdf_cpp <- function(u, kind, psi) {
    .Call(`_morie_morie_hawkes_kernel_cdf_cpp`, u, kind, psi)
}

morie_hawkes_pair_excitation_sum_cpp <- function(t, eta, kind, psi) {
    .Call(`_morie_morie_hawkes_pair_excitation_sum_cpp`, t, eta, kind, psi)
}

morie_hawkes_baseline_integral_cpp <- function(T_horizon, alpha, n_grid = 0L) {
    .Call(`_morie_morie_hawkes_baseline_integral_cpp`, T_horizon, alpha, n_grid)
}

.morie_http_get <- function(url, timeout_s = 60L, headers = as.character( c()), user_agent = "", follow_redirects = TRUE) {
    .Call(`_morie_morie_http_get_`, url, timeout_s, headers, user_agent, follow_redirects)
}

.morie_http_get_bytes <- function(url, timeout_s = 60L, headers = as.character( c()), user_agent = "", follow_redirects = TRUE) {
    .Call(`_morie_morie_http_get_bytes_`, url, timeout_s, headers, user_agent, follow_redirects)
}

.morie_http_post <- function(url, body, content_type = "application/json", timeout_s = 60L, headers = as.character( c()), user_agent = "", follow_redirects = TRUE) {
    .Call(`_morie_morie_http_post_`, url, body, content_type, timeout_s, headers, user_agent, follow_redirects)
}

.morie_http_get_with_status <- function(url, timeout_s = 60L, headers = as.character( c()), user_agent = "", follow_redirects = TRUE) {
    .Call(`_morie_morie_http_get_with_status_`, url, timeout_s, headers, user_agent, follow_redirects)
}

.morie_http_post_with_status <- function(url, body, content_type = "application/json", timeout_s = 60L, headers = as.character( c()), user_agent = "", follow_redirects = TRUE) {
    .Call(`_morie_morie_http_post_with_status_`, url, body, content_type, timeout_s, headers, user_agent, follow_redirects)
}

.morie_http_curl_version <- function() {
    .Call(`_morie_morie_http_curl_version_`)
}

morie_matching_mahalanobis_pairs_cpp <- function(X_t, X_c, S_inv) {
    .Call(`_morie_morie_matching_mahalanobis_pairs_cpp`, X_t, X_c, S_inv)
}

morie_matching_euclidean_pairs_cpp <- function(X_t, X_c) {
    .Call(`_morie_morie_matching_euclidean_pairs_cpp`, X_t, X_c)
}

morie_matching_nn_select_cpp <- function(D, with_replacement, caliper, n_neighbors) {
    .Call(`_morie_morie_matching_nn_select_cpp`, D, with_replacement, caliper, n_neighbors)
}

morie_matching_cem_strata_cpp <- function(X_binned) {
    .Call(`_morie_morie_matching_cem_strata_cpp`, X_binned)
}

morie_matching_abadie_imbens_kernel_cpp <- function(y, t, treated_pos, control_pos) {
    .Call(`_morie_morie_matching_abadie_imbens_kernel_cpp`, y, t, treated_pos, control_pos)
}

.morie_match_greedy_kd_cpp <- function(treated, control, ratio, caliper_dist, replace) {
    .Call(`_morie_morie_match_greedy_kd_cpp`, treated, control, ratio, caliper_dist, replace)
}

.morie_match_greedy_1d_cpp <- function(treated_val, control_val, ratio, caliper_width, replace) {
    .Call(`_morie_morie_match_greedy_1d_cpp`, treated_val, control_val, ratio, caliper_width, replace)
}

.morie_match_optimal_1d_cpp <- function(treated_val, control_val) {
    .Call(`_morie_morie_match_optimal_1d_cpp`, treated_val, control_val)
}

.morie_match_optimal_assign_cpp <- function(treated, control) {
    .Call(`_morie_morie_match_optimal_assign_cpp`, treated, control)
}

.morie_rlearner_forest_cpp <- function(X, pseudo, weight, Xpred, n_trees, max_depth, min_node, subsample, seed) {
    .Call(`_morie_morie_rlearner_forest_cpp`, X, pseudo, weight, Xpred, n_trees, max_depth, min_node, subsample, seed)
}

.morie_rlm_cpp <- function(X, y, k, maxit, acc) {
    .Call(`_morie_morie_rlm_cpp`, X, y, k, maxit, acc)
}

.morie_sobol_cpp <- function(n, d) {
    .Call(`_morie_morie_sobol_cpp`, n, d)
}

.morie_knn_index_cpp <- function(coords, k) {
    .Call(`_morie_morie_knn_index_cpp`, coords, k)
}

.morie_coord_descent_cpp <- function(Xs, yc, alpha, lambda, max_iter, tol, warm) {
    .Call(`_morie_morie_coord_descent_cpp`, Xs, yc, alpha, lambda, max_iter, tol, warm)
}

.morie_tsne_descent_cpp <- function(P, Y, n_iter, eta) {
    .Call(`_morie_morie_tsne_descent_cpp`, P, Y, n_iter, eta)
}

morie_spatial_nominate_iterate_cpp <- function(votes, X, w, nv, mid, beta, max_iter) {
    .Call(`_morie_morie_spatial_nominate_iterate_cpp`, votes, X, w, nv, mid, beta, max_iter)
}

morie_spatial_emirt_theta_update_cpp <- function(theta, a, d, votes) {
    .Call(`_morie_morie_spatial_emirt_theta_update_cpp`, theta, a, d, votes)
}

morie_spatial_smacof_step_cpp <- function(X, D, W) {
    .Call(`_morie_morie_spatial_smacof_step_cpp`, X, D, W)
}

morie_spatial_classical_mds_cpp <- function(D, n_dims) {
    .Call(`_morie_morie_spatial_classical_mds_cpp`, D, n_dims)
}

morie_spatial_wordfish_omega_update_cpp <- function(dtm, psi, alpha, beta, omega) {
    .Call(`_morie_morie_spatial_wordfish_omega_update_cpp`, dtm, psi, alpha, beta, omega)
}

morie_svc_train_cpp <- function(X, y, C, kernel_type, gamma, coef0, degree, tol, max_iter) {
    .Call(`_morie_morie_svc_train_cpp`, X, y, C, kernel_type, gamma, coef0, degree, tol, max_iter)
}

morie_svr_train_cpp <- function(X, z, C, epsilon, kernel_type, gamma, coef0, degree, tol, max_iter) {
    .Call(`_morie_morie_svr_train_cpp`, X, z, C, epsilon, kernel_type, gamma, coef0, degree, tol, max_iter)
}

morie_svm_decision_cpp <- function(SV, coef, rho, Xnew, kernel_type, gamma, coef0, degree) {
    .Call(`_morie_morie_svm_decision_cpp`, SV, coef, rho, Xnew, kernel_type, gamma, coef0, degree)
}

morie_tree_fit_cpp <- function(X, g, h, max_depth, min_node, mtry, lambda, alpha, gamma_pen) {
    .Call(`_morie_morie_tree_fit_cpp`, X, g, h, max_depth, min_node, mtry, lambda, alpha, gamma_pen)
}

morie_tree_predict_cpp <- function(tree, X) {
    .Call(`_morie_morie_tree_predict_cpp`, tree, X)
}

.siu_http_get <- function(url, timeout_s = 60L) {
    .Call(`_morie_siu_http_get`, url, timeout_s)
}

.siu_curl_version <- function() {
    .Call(`_morie_siu_curl_version`)
}

.siu_http_get_many <- function(urls, concurrency = 4L, timeout_s = 60L, rate_rps = 4.0, max_retries = 3L) {
    .Call(`_morie_siu_http_get_many`, urls, concurrency, timeout_s, rate_rps, max_retries)
}

.siu_http_get_many_with_status <- function(urls, concurrency = 4L, timeout_s = 60L, rate_rps = 4.0, max_retries = 3L) {
    .Call(`_morie_siu_http_get_many_with_status`, urls, concurrency, timeout_s, rate_rps, max_retries)
}

.siu_parse_report <- function(html, drid, url) {
    .Call(`_morie_siu_parse_report`, html, drid, url)
}

.siu_parse_news <- function(html, nrid, url) {
    .Call(`_morie_siu_parse_news`, html, nrid, url)
}

