# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

morie_normal_pdf_cpp <- function(x, mean, sd) {
    .Call(`_morie_morie_normal_pdf_cpp`, x, mean, sd)
}

morie_mean_cpp <- function(x) {
    .Call(`_morie_morie_mean_cpp`, x)
}

morie_var_cpp <- function(x, ddof = 1L) {
    .Call(`_morie_morie_var_cpp`, x, ddof)
}

morie_cor_pearson_cpp <- function(x, y) {
    .Call(`_morie_morie_cor_pearson_cpp`, x, y)
}

