# SPDX-License-Identifier: AGPL-3.0-or-later
# GENERATED by scripts/r_bridge_natives.R from tests/r_bridge_parity/*_adapters.R -- do not edit.
# The R bridge's adapters: each NATIVE[["r_x"]] calls morie's own R functions (M is the namespace
# of rmorie or morie). No reference package is used here; tests/r_bridge_parity checks the numbers
# against them.
NATIVE <- list()
`%||%` <- function(a, b) if (is.null(a)) b else a

# ---- from causal_adapters.R
.cz_rhs_columns <- function(f, data) {
  rhs <- stats::delete.response(stats::terms(f, data = data))
  plain <- attr(rhs, "term.labels")
  if (all(plain %in% names(data)) && all(vapply(data[plain], is.numeric, TRUE))) {
    return(list(data = data, covariates = plain))
  }
  mm <- stats::model.matrix(rhs, data = stats::model.frame(rhs, data = data))
  mm <- mm[, colnames(mm) != "(Intercept)", drop = FALSE]
  nm <- make.names(paste0(".cz_", colnames(mm)), unique = TRUE)
  colnames(mm) <- nm
  list(data = cbind(data, as.data.frame(mm)), covariates = nm)
}
.cz_lhs_name <- function(f) {
  v <- all.vars(f[[2]])
  if (length(v) != 1L) stop("the left-hand side must be one column (the treatment)")
  v
}
.cz_binary <- function(x) {
  if (is.factor(x)) x <- as.integer(x) - 1L
  if (is.logical(x)) x <- as.integer(x)
  as.numeric(x)
}
.cz_ols_learner <- function(Xtr, ytr) {
  q <- qr(cbind(1, Xtr))
  b <- qr.coef(q, ytr)
  b[is.na(b)] <- 0
  function(Xn) as.numeric(cbind(1, Xn) %*% b)
}
.cz_iv_parts <- function(f) {
  rhs <- f[[3]]
  if (!(is.call(rhs) && identical(rhs[[1]], as.name("|"))))
    stop("formula must be y ~ exog + endog | exog + instruments")
  y <- all.vars(f[[2]])
  r1 <- all.vars(rhs[[2]]); r2 <- all.vars(rhs[[3]])
  list(y = y, endog = setdiff(r1, r2), instruments = setdiff(r2, r1), exog = intersect(r1, r2))
}
NATIVE[["r_matchit"]] <- function(a, M) {
  f <- a$formula; data <- as.data.frame(a$data)
  method <- a$method %||% "nearest"
  tr <- .cz_lhs_name(f)
  data[[tr]] <- .cz_binary(data[[tr]])
  if (identical(method, "exact")) {
    vars <- attr(stats::terms(f, data = data), "term.labels")
    return(M$morie_matching_exact(data, tr, vars))
  }
  r <- .cz_rhs_columns(f, data)
  switch(method,
    nearest = M$morie_matching_nearest_neighbor(r$data, tr, r$covariates,
                                                n_neighbors = a$ratio %||% 1L,
                                                caliper = a$caliper,
                                                replace = a$replace %||% FALSE),
    subclass = M$morie_matching_subclassify(r$data, tr, r$covariates,
                                            n_strata = a$subclass %||% 6L),
    cem = M$morie_matching_cem(r$data, tr, r$covariates, n_bins = NA_integer_),
    stop(sprintf("method '%s' has no native adapter (nearest, exact, subclass, cem)", method))
  )
}
NATIVE[["r_ipw"]] <- function(a, M) {
    f <- a$formula; data <- as.data.frame(a$data)
    tr <- .cz_lhs_name(f)
    data[[tr]] <- .cz_binary(data[[tr]])
    r <- .cz_rhs_columns(f, data)
    ps <- M$morie_estimate_propensity_scores(r$data, tr, r$covariates, trim = NULL)
    d <- data.frame(t = r$data[[tr]], ps = ps)
    w <- M$morie_calculate_ipw_weights(d, "t", "ps")
    print(summary(w))
    w
  }
NATIVE[["r_aipw"]] <- function(a, M) {
    w <- as.data.frame(a$w)
    names(w) <- make.names(paste0("w_", names(w) %||% seq_along(w)), unique = TRUE)
    df <- cbind(data.frame(.y = as.numeric(a$y), .a = .cz_binary(a$a)), w)
    r <- .cz_rhs_columns(stats::reformulate(names(w)), df)
    gb <- a$g.bound %||% 0.025
    M$morie_estimate_aipw(r$data, ".a", ".y", r$covariates,
                          trim = c(gb, 1 - gb), trim_type = "value",
                          outcome_fit = "pooled")
  }
NATIVE[["r_dml"]] <- function(a, M) {
    data <- as.data.frame(a$data)
    X <- stats::model.matrix(stats::reformulate(a$x), data = data)[, -1, drop = FALSE]
    r <- M$morie_caus_dml_partial_lin(as.numeric(data[[a$y]]), as.numeric(data[[a$d]]), X,
                                      n_folds = a$n_folds %||% 5L, learner = .cz_ols_learner,
                                      seed = a$seed %||% 0L)
    r[c("theta", "se", "ci", "n_folds", "first_stage_r2", "method")]
  }
NATIVE[["r_irm"]] <- function(a, M) {
    data <- as.data.frame(a$data)
    X <- stats::model.matrix(stats::reformulate(a$x), data = data)[, -1, drop = FALSE]
    df <- cbind(data.frame(.y = as.numeric(data[[a$y]]), .d = .cz_binary(data[[a$d]])), X)
    M$morie_estimate_irm(df, ".d", ".y", colnames(X),
                         n_folds = a$n_folds %||% 5L, random_state = a$seed %||% 42L)
  }
NATIVE[["r_rdrobust"]] <- function(a, M) {
    y <- as.numeric(a$y); x <- as.numeric(a$x); cc <- a$c %||% 0
    h <- a$h; b <- a$b
    if (is.null(h) || is.null(b)) {
      bw <- M$morie_rd_mserd_bandwidth(y, x, cutoff = cc, p = a$p %||% 1)  # rdrobust's mserd
      h <- h %||% bw$h; b <- b %||% bw$b
    }
    M$morie_causrddc(y, x, cutoff = cc, h = h, b = b, p = a$p %||% 1, kernel = a$kernel %||% "triangular")[
      c("estimate", "bias_corrected", "se_conventional", "se_robust", "ci_conventional",
        "ci_robust", "pvalue_robust", "h", "b", "n_left", "n_right", "method")]
  }
NATIVE[["r_ivreg"]] <- function(a, M) {
    p <- .cz_iv_parts(a$formula)
    M$morie_iv_tsls(as.data.frame(a$data), p$y, p$endog, p$instruments,
                    exogenous = if (length(p$exog)) p$exog else NULL,
                    robust = a$robust %||% FALSE)
  }
NATIVE[["r_synth"]] <- function(a, M) {
    x <- as.data.frame(a$data)
    tu <- a$treatment.identifier
    uv <- a$unit.variable; tv <- a$time.variable
    if (is.character(tu)) tu <- unique(x[[uv]][as.character(x[[a$unit.names.variable]]) == tu])
    ctrl <- a$controls.identifier
    if (is.character(ctrl)) ctrl <- unique(x[[uv]][as.character(x[[a$unit.names.variable]]) %in% ctrl])
    keep_t <- a$time.plot %||% sort(unique(x[[tv]]))
    x <- x[x[[uv]] %in% c(tu, ctrl) & x[[tv]] %in% keep_t, , drop = FALSE]
    ttime <- max(a$time.optimize.ssr) + 1
    M$morie_synth_control(x, a$dependent, uv, tv, treated_unit = tu,
                          treatment_time = ttime, predictors = a$predictors)
  }

# ---- from regression_adapters.R
.rg_coef_table <- function(est, se = NULL, stat_name = NULL, df = NULL) {
  out <- data.frame(Estimate = as.numeric(est), row.names = names(est))
  if (!is.null(se)) {
    out[["Std.Error"]] <- as.numeric(se)
    z <- as.numeric(est) / as.numeric(se)
    if (identical(stat_name, "t")) {
      out[["t value"]] <- z
      out[["Pr(>|t|)"]] <- 2 * stats::pt(abs(z), df, lower.tail = FALSE)
    } else if (identical(stat_name, "z")) {
      out[["z value"]] <- z
      out[["Pr(>|z|)"]] <- 2 * stats::pnorm(abs(z), lower.tail = FALSE)
    }
  }
  out
}
.rg_design <- function(formula, data) {
  mf <- stats::model.frame(formula, data)
  y <- stats::model.response(mf)
  X <- stats::model.matrix(attr(mf, "terms"), mf)
  list(y = y, X = X, mf = mf)
}
.rg_binary <- function(y) {
  if (is.factor(y)) return(as.numeric(y != levels(y)[1]))
  if (is.logical(y)) return(as.numeric(y))
  as.numeric(y)
}
.rg_family_name <- function(family) {
  if (is.null(family)) return("gaussian")
  if (is.function(family)) family <- family()
  if (inherits(family, "family")) {
    fam <- tolower(family$family); link <- family$link
  } else {
    fam <- tolower(as.character(family)[1])
    link <- switch(fam, binomial = "logit", poisson = "log", gaussian = "identity",
                   gamma = "inverse", quasibinomial = "logit", quasipoisson = "log", NA)
  }
  canon <- c(binomial = "logit", poisson = "log", gaussian = "identity", gamma = "log")
  if (!fam %in% names(canon))
    stop("morie_glm supports the binomial, poisson, gaussian and Gamma(log) families, not '", fam, "'",
         call. = FALSE)
  if (!identical(link, canon[[fam]]))
    stop(sprintf("morie_glm fits family '%s' with the %s link only (got link '%s')", fam,
                 canon[[fam]], link), call. = FALSE)
  fam
}
.rg_glm_native <- function(formula, data, family, M) {
  fam <- .rg_family_name(family)
  d <- .rg_design(formula, data)
  y <- if (fam == "binomial") .rg_binary(d$y) else as.numeric(d$y)
  # morie_glm's defaults (tol 1e-8 on the relative deviance change, 25 iterations) are glm's
  r <- M$morie_glm(y, d$X, family = fam, add_intercept = FALSE)
  names(r$coef) <- colnames(d$X)
  list(call = sprintf("morie_glm(family = \"%s\")", fam),
       coefficients = .rg_coef_table(setNames(r$coef, colnames(d$X)), r$se, r$statistic_name,
                                     r$df_residual),
       dispersion = r$dispersion, deviance = r$deviance, null_deviance = r$null_deviance,
       df_residual = r$df_residual, aic = r$aic, converged = r$converged, n = r$n)
}
NATIVE[["r_lm"]] <- function(a, M) {
    d <- .rg_design(a$formula, a$data)
    icpt <- attr(attr(d$mf, "terms"), "intercept") == 1L
    X <- if (icpt) d$X[, -1L, drop = FALSE] else d$X
    r <- M$morie_ols(as.numeric(d$y), X, add_intercept = icpt)
    beta <- setNames(r$coef, colnames(d$X))
    list(call = "morie_ols(y, model.matrix(formula, data))",
         coefficients = .rg_coef_table(beta, r$se, "t", r$df_resid),
         sigma = r$sigma, r.squared = r$r_squared, adj.r.squared = r$adj_r_squared,
         fstatistic = c(value = r$f_statistic, numdf = r$df_model, dendf = r$df_resid), n = r$n)
  }
NATIVE[["r_glm"]] <- function(a, M) .rg_glm_native(a$formula, a$data, a$family, M)
NATIVE[["r_logistic"]] <- function(a, M) .rg_glm_native(a$formula, a$data, "binomial", M)
NATIVE[["r_poisson"]] <- function(a, M) .rg_glm_native(a$formula, a$data, "poisson", M)
NATIVE[["r_robust"]] <- function(a, M) {
    fit <- M$morie_rlm(a$formula, a$data)
    s <- M$summary.morie_rlm(fit)
    list(call = "morie_rlm(formula, data)  # Huber M, k = 1.345, MAD scale",
         coefficients = as.data.frame(s$coefficients), scale = fit$s,
         converged = fit$converged, n_downweighted = fit$n_downweighted)
  }

# ---- from survival_effects_adapters.R
.se_lhs_value <- function(expr, data, env) {
  stats::model.frame(stats::as.formula(call("~", expr), env = env), data, na.action = stats::na.pass)[[1]]
}
.se_surv_parts <- function(f, data) {
  lhs <- f[[2]]
  if (!is.call(lhs) || !identical(as.character(lhs[[1]]), "Surv") &&
      !identical(deparse(lhs[[1]]), "survival::Surv"))
    stop("left-hand side must be Surv(time, event)")
  if (length(lhs) != 3L) stop("only right-censored Surv(time, event) is supported")
  env <- environment(f) %||% parent.frame()
  time <- as.numeric(.se_lhs_value(lhs[[2]], data, env))
  ev <- .se_lhs_value(lhs[[3]], data, env)
  ev <- as.numeric(ev)
  if (all(ev %in% c(1, 2)) && any(ev == 2)) ev <- ev - 1   # Surv's 1/2 coding
  rt <- stats::delete.response(stats::terms(f))
  mf <- stats::model.frame(rt, data)
  X <- stats::model.matrix(rt, mf)
  X <- X[, colnames(X) != "(Intercept)", drop = FALSE]
  grp <- if (ncol(mf) == 0L) factor(rep("all", length(time))) else {
    labs <- lapply(names(mf), function(v) paste0(v, "=", mf[[v]]))
    lv <- lapply(names(mf), function(v) {
      x <- mf[[v]]; paste0(v, "=", if (is.factor(x)) levels(x) else sort(unique(x)))
    })
    if (length(labs) == 1L) factor(labs[[1]], levels = lv[[1]])
    else interaction(lapply(seq_along(labs), function(i) factor(labs[[i]], levels = lv[[i]])),
                     sep = ", ", drop = TRUE, lex.order = TRUE)
  }
  list(time = time, event = ev, X = X, group = droplevels(grp), strata = ncol(mf) > 0L)
}
.se_yX <- function(f, data, intercept = FALSE) {
  mf <- stats::model.frame(f, data)
  y <- as.numeric(stats::model.response(mf))
  X <- stats::model.matrix(stats::terms(mf), mf)
  if (!intercept) X <- X[, colnames(X) != "(Intercept)", drop = FALSE]
  list(y = y, X = X)
}
NATIVE[["r_survfit"]] <- function(a, M) {
    s <- .se_surv_parts(a$formula, a$data)
    out <- lapply(levels(s$group), function(g) {
      i <- s$group == g
      k <- M$morie_kaplan_meier(s$time[i], s$event[i])
      data.frame(strata = if (s$strata) g else NA_character_, time = k$time,
                 n.risk = k$n_risk, n.event = k$n_event, surv = k$surv, std.err = k$se,
                 lower = k$lower, upper = k$upper, stringsAsFactors = FALSE)
    })
    out <- do.call(rbind, out)
    if (!s$strata) out$strata <- NULL
    rownames(out) <- NULL
    out
  }
NATIVE[["r_coxph"]] <- function(a, M) {
    s <- .se_surv_parts(a$formula, a$data)
    r <- M$morie_cox_ph(s$time, s$event, s$X, ties = a$ties %||% "efron")
    names(r$coef) <- names(r$se) <- names(r$z) <- names(r$p_value) <- names(r$hazard_ratio) <-
      colnames(s$X)
    r$table <- data.frame(coef = r$coef, `exp(coef)` = r$hazard_ratio, `se(coef)` = r$se,
                          z = r$z, p = r$p_value, check.names = FALSE)
    r
  }
NATIVE[["r_survdiff"]] <- function(a, M) {
    s <- .se_surv_parts(a$formula, a$data)
    M$morie_logrank_test(s$time, s$event, s$group)
  }
NATIVE[["r_aft"]] <- function(a, M) {
    s <- .se_surv_parts(a$formula, a$data)
    M$morie_aft(s$time, s$event, if (ncol(s$X)) s$X else NULL, dist = a$dist %||% "weibull")
  }
NATIVE[["r_p_adjust"]] <- function(a, M) {
    m <- a$method %||% "holm"
    if (identical(m, "none")) return(as.numeric(a$p))
    key <- switch(m, BH = , fdr = "bh", BY = "by", tolower(m))
    M$adjust_p_values(a$p, method = key)$adjusted
  }
NATIVE[["r_vif"]] <- function(a, M) {
    d <- .se_yX(a$formula, a$data)
    M$compute_vif(d$X, colnames(d$X))
  }
NATIVE[["r_durbinwatson"]] <- function(a, M) {
    d <- .se_yX(a$formula, a$data)
    M$morie_durbin_watson(M$morie_ols(d$y, d$X, add_intercept = TRUE))
  }
NATIVE[["r_bptest"]] <- function(a, M) {
    d <- .se_yX(a$formula, a$data)
    M$morie_breusch_pagan(M$morie_ols(d$y, d$X, add_intercept = TRUE))
  }
NATIVE[["r_resettest"]] <- function(a, M) {
    d <- .se_yX(a$formula, a$data, intercept = TRUE)
    M$ramsey_reset_test(d$y, d$X, powers = a$power %||% 2:3)
  }
NATIVE[["r_cohens_d"]] <- function(a, M) M$cohens_d(a$x, a$y)
NATIVE[["r_hedges_g"]] <- function(a, M) M$hedges_g(a$x, a$y)
NATIVE[["r_eta_sq"]] <- function(a, M) {
    # Type I (sequential) sums of squares, as effectsize reads them from an aov fit; partial
    # eta^2 per term = SS_term / (SS_term + SS_resid), effectsize's default partial = TRUE.
    tab <- stats::anova(stats::lm(a$formula, data = a$data))
    rn <- trimws(rownames(tab))
    ss_res <- tab[["Sum Sq"]][rn == "Residuals"]
    terms <- rn[rn != "Residuals"]
    partial <- a$partial %||% TRUE
    ss_tot <- sum(tab[["Sum Sq"]])
    est <- vapply(terms, function(t) {
      ss <- tab[["Sum Sq"]][rn == t]
      M$eta_squared(ss, if (partial) ss + ss_res else ss_tot)$estimate
    }, numeric(1))
    data.frame(Parameter = terms, Eta2 = unname(est), partial = partial)
  }
NATIVE[["r_cramers_v"]] <- function(a, M) {
    r <- M$cramers_v(table(a$x, a$y))
    # effectsize's default adjust = TRUE is Bergsma's bias correction, which morie returns as
    # extra$bias_corrected_v; report that as the headline unless adjust = FALSE.
    if (isTRUE(a$adjust %||% TRUE)) {
      r$extra$unadjusted_v <- r$estimate
      r$estimate <- r$extra$bias_corrected_v
      r$ci_lower <- r$ci_upper <- NA_real_
      r$measure <- "Cramer's V (adjusted)"
    }
    r
  }
NATIVE[["r_power_t"]] <- function(a, M) {
    alt <- switch(a$alternative %||% "two.sided", two.sided = "two-sided", "one-sided")
    if (!is.null(a$alternative) && a$alternative == "less") stop("alternative 'less' not mapped")
    typ <- switch(a$type %||% "two.sample", two.sample = "two-sample", one.sample = "one-sample",
                  paired = "paired")
    sol <- M$PowerTTest(n = a$n, delta = a$d, sd = 1, alpha = a$sig.level %||% 0.05,
                        power = a$power, alternative = alt, type = typ, strict = TRUE)
    out <- list(n = a$n, d = a$d, sig.level = a$sig.level %||% 0.05, power = a$power,
                alternative = a$alternative %||% "two.sided", type = typ)
    if (is.null(a$n)) out$n <- sol else if (is.null(a$power)) out$power <- sol else out$d <- sol
    out
  }
NATIVE[["r_power_anova"]] <- function(a, M) {
    sol <- M$PowerAnova(n = a$n, k = a$k, f = a$f, alpha = a$sig.level %||% 0.05, power = a$power)
    out <- list(k = a$k, n = a$n, f = a$f, sig.level = a$sig.level %||% 0.05, power = a$power)
    if (is.null(a$power)) out$power <- sol else if (is.null(a$n)) out$n <- sol
    else if (is.null(a$f)) out$f <- sol else out$k <- sol
    out
  }
NATIVE[["r_power_chisq"]] <- function(a, M) {
    sig <- if ("sig.level" %in% names(a)) a$sig.level else 0.05
    pw <- function(w, N, df, sig) {
      stats::pchisq(stats::qchisq(sig, df, lower.tail = FALSE), df, ncp = N * w^2, lower.tail = FALSE)
    }
    w <- a$w; N <- a$N; df <- a$df; power <- a$power
    if (is.null(df)) stop("df is required", call. = FALSE)
    unknown <- c(w = is.null(w), N = is.null(N), power = is.null(power), sig.level = is.null(sig))
    if (sum(unknown) != 1L) stop("leave exactly one of w, N, power, sig.level out (NULL)", call. = FALSE)
    solve <- function(f, lo, hi) stats::uniroot(f, c(lo, hi), tol = 1e-10, extendInt = "upX")$root
    if (unknown[["power"]]) power <- pw(w, N, df, sig)
    else if (unknown[["N"]]) N <- solve(function(n) pw(w, n, df, sig) - power, 2 + 1e-10, 1e7)
    else if (unknown[["w"]]) w <- solve(function(x) pw(x, N, df, sig) - power, 1e-10, 1e5)
    else sig <- stats::uniroot(function(s) pw(w, N, df, s) - power, c(1e-10, 1 - 1e-10), tol = 1e-10)$root
    structure(list(w = w, N = N, df = df, sig.level = sig, power = power,
                   method = "Chi squared power calculation", note = "N is the number of observations"),
              class = "power.htest")
  }
NATIVE[["r_power_prop"]] <- function(a, M) {
    # pwr.2p.test takes Cohen's h; PowerPropTest(method = "cohen_h") takes p1, p2 and computes
    # h = |2 asin(sqrt p1) - 2 asin(sqrt p2)|. Choose p1, p2 symmetric about 1/2 with that h.
    h <- abs(a$h)
    if (h > pi) stop("|h| must be <= pi")
    p1 <- sin((pi / 2 + h / 2) / 2)^2
    p2 <- sin((pi / 2 - h / 2) / 2)^2
    alt <- switch(a$alternative %||% "two.sided", two.sided = "two-sided", "one-sided")
    sol <- M$PowerPropTest(n = a$n, p1 = p1, p2 = p2, alpha = a$sig.level %||% 0.05,
                           power = a$power, alternative = alt, method = "cohen_h")
    out <- list(h = a$h, n = a$n, sig.level = a$sig.level %||% 0.05, power = a$power,
                alternative = a$alternative %||% "two.sided")
    if (is.null(a$power)) out$power <- sol else out$n <- sol
    out
  }

# ---- from tables_survey_misc_adapters.R
.tsm <- local({
  `%||%` <- function(a, b) if (is.null(a)) b else a

  # one-sided formula / column name / NULL -> column name(s)
  fvars <- function(f) {
    if (is.null(f)) return(NULL)
    if (is.character(f)) return(f)
    v <- all.vars(f)
    if (length(v) == 0L) NULL else v
  }

  # the bridge's statistic whitelist, as base functions
  stat_names <- c("mean", "median", "sd", "var", "min", "max", "IQR", "mad", "sum")
  stat_fun <- function(name) {
    if (!is.character(name) || !name %in% stat_names)
      stop("statistic must be one of: ", paste(stat_names, collapse = ", "), call. = FALSE)
    f <- if (name %in% c("median", "sd", "var", "IQR", "mad")) getExportedValue("stats", name)
         else get(name, envir = baseenv(), mode = "function")
    function(d, i) f(d[i])
  }

  # survey design from the bridge's ids=, weights=, strata=, data=
  design <- function(a, M) {
    data <- a$data
    w <- fvars(a$weights)
    if (is.null(w)) {
      data$.w_unit <- 1
      w <- ".w_unit"
    }
    ids <- fvars(a$ids)
    if (!is.null(ids) && length(ids) > 1L)
      stop("the native design takes one stage of clusters (ids = ~psu).", call. = FALSE)
    st <- fvars(a$strata)
    M$morie_survey_design(data, weights_col = w, strata_col = st, cluster_col = ids,
                          fpc_col = fvars(a$fpc), nest = isTRUE(a$nest))
  }

  # strip "12.3 (4.5)" / "12 (33.3%)" cells into numbers
  nums <- function(s) as.numeric(regmatches(s, gregexpr("-?[0-9]+\\.?[0-9]*(e-?[0-9]+)?", s))[[1]])

  # Kaplan-Meier pieces from Surv(time, status) ~ strata
  km_parts <- function(formula, data) {
    lhs <- formula[[2]]
    if (!is.call(lhs) || !identical(as.character(lhs[[1]]), "Surv") || length(lhs) != 3L)
      stop("formula must be Surv(time, status) ~ group (or ~ 1).", call. = FALSE)
    lhs_value <- function(expr) {
      stats::model.frame(stats::as.formula(call("~", expr), env = environment(formula)), data,
                         na.action = stats::na.pass)[[1]]
    }
    time <- as.numeric(lhs_value(lhs[[2]]))
    st <- lhs_value(lhs[[3]])
    st <- if (is.logical(st)) as.numeric(st) else as.numeric(st)
    if (all(st %in% c(1, 2)) && any(st == 2)) st <- st - 1  # Surv's 1/2 coding
    rhs <- all.vars(formula[[3]])
    grp <- if (length(rhs)) interaction(data[rhs], sep = ", ", drop = TRUE) else factor(rep("all", length(time)))
    list(time = time, event = st, group = grp, rhs = rhs)
  }

  environment()
})
.tsm$open_png <- function(a) {
  file <- a$file %||% tempfile("morie-plot-", fileext = ".png")
  grDevices::png(file, width = 1600, height = 1000, res = 150)
  file
}
NATIVE[["r_table1"]] <- function(a, M) {
    d <- a$data
    vars <- a$vars %||% setdiff(names(d), a$strata)
    is_num <- vapply(d[vars], is.numeric, logical(1))
    M$table1(d, group_col = a$strata, continuous_vars = vars[is_num],
             categorical_vars = vars[!is_num], digits = a$digits %||% 2L)
  }
NATIVE[["r_stargazer"]] <- function(a, M) {
    fit <- stats::lm(a$formula, data = a$data)
    M$regression_table(list(model = fit), digits = a$digits %||% 3L, show_ci = FALSE)
  }
NATIVE[["r_mice"]] <- function(a, M) {
    d <- a$data
    meth <- unique(a$method %||% "norm")
    meth <- meth[nzchar(meth)]
    if (length(meth) && !all(meth == "norm"))
      stop("the native MICE (morie_miord2) imputes with method = 'norm' (Bayesian linear ",
           "regression) only; got ", paste(meth, collapse = ", "), call. = FALSE)
    if (!all(vapply(d, is.numeric, logical(1))))
      stop("the native MICE imputes numeric columns only.", call. = FALSE)
    r <- M$morie_miord2(as.matrix(d), m = a$m %||% 5L, maxit = a$maxit %||% 5L, seed = a$seed %||% 0)
    imps <- lapply(r$imputations, function(x) { x <- as.data.frame(x); names(x) <- names(d); x })
    miss <- colSums(r$missing_mask)
    out <- data.frame(variable = names(d), n_missing = miss,
                      pooled_mean = colMeans(do.call(rbind, lapply(imps, colMeans))),
                      between_imp_sd = apply(do.call(rbind, lapply(imps, colMeans)), 2, stats::sd),
                      row.names = NULL)
    attr(out, "imputations") <- imps
    attr(out, "method") <- r$method
    out
  }
NATIVE[["r_amelia"]] <- function(a, M) {
    d <- a$x %||% a$data
    if (!all(vapply(d, is.numeric, logical(1))))
      stop("the native multivariate-normal imputation takes numeric columns only.", call. = FALSE)
    r <- M$morie_miord2(as.matrix(d), m = a$m %||% 5L, maxit = a$maxit %||% 10L, seed = a$seed %||% 0)
    imps <- lapply(r$imputations, function(x) { x <- as.data.frame(x); names(x) <- names(d); x })
    out <- data.frame(variable = names(d), n_missing = colSums(r$missing_mask),
                      pooled_mean = colMeans(do.call(rbind, lapply(imps, colMeans))),
                      row.names = NULL)
    attr(out, "imputations") <- imps
    attr(out, "method") <- "multivariate-normal MI by chained normal regressions (morie_miord2)"
    out
  }
NATIVE[["r_svydesign"]] <- function(a, M) {
    d <- .tsm$design(a, M)
    out <- data.frame(n = nrow(d$data), strata = length(unique(d$strata)),
                      psus = length(unique(d$cluster)), sum_weights = sum(d$weights))
    attr(out, "design") <- d
    out
  }
NATIVE[["r_svymean"]] <- function(a, M) {
    d <- .tsm$design(a, M)
    vars <- .tsm$fvars(a$x %||% a$formula)
    rows <- list()
    for (v in vars) {
      col <- d$data[[v]]
      if (is.numeric(col)) {
        r <- M$morie_survey_mean(d, v)
        rows[[length(rows) + 1L]] <- data.frame(term = v, mean = r$mean, SE = r$se)
      } else {
        # a factor: one proportion per level, as svymean does
        for (lv in levels(factor(col))) {
          nm <- paste0(v, lv)
          d$data[[nm]] <- as.numeric(col == lv)
          r <- M$morie_survey_mean(d, nm)
          rows[[length(rows) + 1L]] <- data.frame(term = nm, mean = r$mean, SE = r$se)
        }
      }
    }
    do.call(rbind, rows)
  }
NATIVE[["r_svytotal"]] <- function(a, M) {
    d <- .tsm$design(a, M)
    vars <- .tsm$fvars(a$x %||% a$formula)
    rows <- list()
    for (v in vars) {
      col <- d$data[[v]]
      cols <- if (is.numeric(col)) setNames(list(as.numeric(col)), v) else
        setNames(lapply(levels(factor(col)), function(lv) as.numeric(col == lv)),
                 paste0(v, levels(factor(col))))
      for (nm in names(cols)) {
        z <- d$weights * cols[[nm]]
        # .morie_svy_recvar is the design-variance engine behind morie_survey_mean / _glm
        se <- sqrt(M$.morie_svy_recvar(cbind(z), d)[1, 1])
        rows[[length(rows) + 1L]] <- data.frame(term = nm, total = sum(z), SE = se)
      }
    }
    do.call(rbind, rows)
  }
NATIVE[["r_svyglm"]] <- function(a, M) {
    d <- .tsm$design(a, M)
    fam <- a$family %||% "gaussian"
    if (is.character(fam)) fam <- sub("^quasi", "", fam)
    r <- M$morie_survey_glm(d, a$formula, family = fam)
    r$coefficients
  }
NATIVE[["r_calibrate"]] <- function(a, M) {
    d <- .tsm$design(a, M)
    X <- stats::model.matrix(a$formula, d$data)
    pop <- a$population
    if (!is.null(names(pop))) pop <- pop[colnames(X)]
    calfun <- a$calfun %||% "linear"
    w <- if (identical(calfun, "linear")) {
      M$morie_weights_greg(d$weights, X, as.numeric(pop))$weights
    } else if (identical(calfun, "raking")) {
      tot <- setNames(as.list(as.numeric(pop)), colnames(X))
      M$morie_weights_calibrate_to_totals(d$weights, as.data.frame(X, check.names = FALSE), tot,
                                          method = "raking")$weights
    } else stop("native calibration supports calfun = 'linear' or 'raking'.", call. = FALSE)
    data.frame(term = colnames(X), target = as.numeric(pop), calibrated_total = colSums(X * w),
               row.names = NULL) -> out
    attr(out, "weights") <- w
    out
  }
NATIVE[["r_rake"]] <- function(a, M) {
    d <- .tsm$design(a, M)
    sm <- a$sample.margins
    pm <- a$population.margins
    if (inherits(sm, "formula")) sm <- list(sm)
    if (is.data.frame(pm) || is.table(pm)) pm <- list(pm)
    margins <- list()
    for (i in seq_along(sm)) {
      v <- .tsm$fvars(sm[[i]])
      if (length(v) != 1L) stop("each sample margin must be one variable (~g).", call. = FALSE)
      p <- pm[[i]]
      margins[[v]] <- if (is.data.frame(p)) setNames(as.numeric(p[[ncol(p)]]), as.character(p[[v]]))
                      else setNames(as.numeric(p), names(p))
    }
    r <- M$morie_rake(d$data, margins, weights = d$weights, max_iter = 1000L, tol = 1e-10)
    out <- do.call(rbind, lapply(names(margins), function(v) {
      cur <- tapply(r$weights, factor(as.character(d$data[[v]]), levels = names(margins[[v]])), sum)
      data.frame(margin = v, level = names(margins[[v]]), target = unname(margins[[v]]),
                 raked_total = as.numeric(cur))
    }))
    attr(out, "weights") <- r$weights
    attr(out, "converged") <- r$converged
    out
  }
NATIVE[["r_boot"]] <- function(a, M) {
    if (!is.null(a$seed)) set.seed(a$seed)
    b <- M$morie_boot(a$data, .tsm$stat_fun(a$statistic), R = a$R %||% 1000)
    out <- data.frame(statistic = a$statistic, original = b$t0, bias = mean(b$t[, 1]) - b$t0,
                      std.error = stats::sd(b$t[, 1]), R = b$R)
    attr(out, "boot") <- b
    out
  }
NATIVE[["r_boot_ci"]] <- function(a, M) {
    if (!is.null(a$seed)) set.seed(a$seed)
    b <- M$morie_boot(a$data, .tsm$stat_fun(a$statistic), R = a$R %||% 1000)
    type <- a$type %||% "perc"
    if (identical(type, "all")) type <- c("norm", "basic", "perc", "bca")
    if ("stud" %in% type) stop("studentized intervals need bootstrap variances; not available.", call. = FALSE)
    ci <- M$morie_boot_ci(b, conf = a$conf %||% 0.95, type = type)
    data.frame(type = names(ci), conf = a$conf %||% 0.95, lower = vapply(ci, `[`, 0, 1),
               upper = vapply(ci, `[`, 0, 2), row.names = NULL)
  }
NATIVE[["r_metafor"]] <- function(a, M) {
    method <- a$method %||% "REML"
    se <- sqrt(a$vi)
    if (method %in% c("FE", "EE", "CE")) {
      r <- M$fixed_effects_meta(a$yi, se, confidence = a$level %||% 0.95)
      tau2 <- 0
    } else if (method %in% c("DL", "PM", "REML")) {
      r <- M$random_effects_meta(a$yi, se, confidence = a$level %||% 0.95, method = method)
      tau2 <- r$extra$tau_squared
    } else stop("native tau^2 estimators: DL, PM, REML (or FE/EE).", call. = FALSE)
    z <- r$estimate / r$se
    data.frame(method = method, estimate = r$estimate, se = r$se, zval = z,
               pval = 2 * stats::pnorm(-abs(z)), ci.lb = r$ci_lower, ci.ub = r$ci_upper,
               tau2 = tau2, Q = r$extra$Q, I2 = r$extra$I_squared %||% NA_real_)
  }
NATIVE[["r_meta_bin"]] <- function(a, M) {
    ee <- a$event.e; ne <- a$n.e; ec <- a$event.c; nc <- a$n.c
    sm <- a$sm %||% "RR"
    tau_m <- a$method.tau %||% "REML"
    if (sm == "RR") {
      common <- M$malab(ee, ne, ec, nc)$log_rr
      common_se <- NA_real_  # morie has no Greenland-Robins variance for the MH risk ratio
      st <- M$malrr(ee, ne - ee, ec, nc - ec)
    } else if (sm == "OR") {
      mh <- M$Mamh(ee, ne - ee, ec, nc - ec)
      common <- log(mh$estimate); common_se <- mh$se
      st <- M$malor(ee, ne - ee, ec, nc - ec)
    } else stop("native summary measures: sm = 'RR' or 'OR'.", call. = FALSE)
    re <- M$random_effects_meta(st$estimate, sqrt(st$variance), method = tau_m)
    data.frame(model = c("common (Mantel-Haenszel)", sprintf("random (%s)", tau_m)), sm = sm,
               log_estimate = c(common, re$estimate), se = c(common_se, re$se),
               estimate = exp(c(common, re$estimate)),
               tau2 = c(NA, re$extra$tau_squared), row.names = NULL)
  }
NATIVE[["r_ggplot"]] <- function(a, M) {
    d <- a$data; g <- a$geom %||% "point"
    geoms <- c("point", "line", "col", "bar", "histogram", "boxplot", "density", "smooth")
    if (!g %in% geoms) stop("geom must be one of: ", paste(geoms, collapse = ", "), call. = FALSE)
    file <- .tsm$open_png(a)
    on.exit(grDevices::dev.off())
    x <- d[[a$x]]; y <- if (is.null(a$y)) NULL else d[[a$y]]
    drawn <- switch(g,
      point = nrow(M$morie_eda_plot(d, a$x, a$y)),
      line = { o <- order(x); graphics::plot(x[o], y[o], type = "l", xlab = a$x, ylab = a$y); length(x) },
      col = { graphics::barplot(y, names.arg = as.character(x), xlab = a$x, ylab = a$y); length(y) },
      bar = { tb <- table(x); graphics::barplot(tb, xlab = a$x, ylab = "count"); length(tb) },
      histogram = { h <- graphics::hist(x, breaks = 30, main = "", xlab = a$x); sum(h$counts) },
      boxplot = {
        if (is.null(y)) { graphics::boxplot(x, ylab = a$x); 1L }
        else { b <- graphics::boxplot(y ~ x, xlab = a$x, ylab = a$y); ncol(b$stats) }
      },
      density = { de <- stats::density(x); graphics::plot(de, main = "", xlab = a$x); length(de$x) },
      smooth = {
        graphics::plot(x, y, xlab = a$x, ylab = a$y, pch = 19, col = "grey60")
        fit <- stats::loess(y ~ x); xs <- seq(min(x), max(x), length.out = 80)
        graphics::lines(xs, stats::predict(fit, data.frame(x = xs)), lwd = 2); 80L
      })
    cat("plot saved to", file, "\n")
    invisible(list(file = file, geom = g, drawn = drawn))
  }
NATIVE[["r_ggsurvplot"]] <- function(a, M) {
    p <- .tsm$km_parts(a$formula, a$data)
    lv <- levels(p$group)
    fits <- lapply(lv, function(l) {
      i <- p$group == l
      M$morie_kaplan_meier(p$time[i], p$event[i])
    })
    names(fits) <- lv
    file <- .tsm$open_png(a)
    on.exit(grDevices::dev.off())
    cols <- c("#0072B2", "#D55E00", "#009E73", "#CC79A7", "#E69F00", "#56B4E9", "#000000")
    graphics::plot(NA, xlim = c(0, max(p$time)), ylim = c(0, 1), xlab = "Time", ylab = "Survival probability")
    for (j in seq_along(fits)) {
      f <- fits[[j]]
      graphics::lines(c(0, f$time, max(p$time[p$group == lv[j]])), c(1, f$surv, utils::tail(c(1, f$surv), 1)),
                      type = "s", col = cols[(j - 1) %% length(cols) + 1], lwd = 2)
    }
    if (length(lv) > 1) graphics::legend("topright", legend = lv, col = cols[seq_along(lv)], lwd = 2, bty = "n")
    cat("plot saved to", file, "\n")
    invisible(list(file = file, strata = lv, km = fits))
  }
NATIVE[["r_forestplot"]] <- function(a, M) {
    x <- a$data
    lab <- as.character(x[[a$label %||% "label"]]); mn <- x[[a$mean %||% "mean"]]
    lo <- x[[a$lower %||% "lower"]]; hi <- x[[a$upper %||% "upper"]]
    k <- length(mn)
    file <- .tsm$open_png(a)
    on.exit(grDevices::dev.off())
    op <- graphics::par(mar = c(4, max(8, max(nchar(lab)) * 0.6), 1, 1)); on.exit(graphics::par(op), add = TRUE)
    yy <- rev(seq_len(k))
    ok <- is.finite(mn)
    graphics::plot(mn[ok], yy[ok], xlim = range(c(lo, hi), na.rm = TRUE), ylim = c(0.5, k + 0.5), pch = 15,
                   yaxt = "n", ylab = "", xlab = "estimate")
    graphics::segments(lo[ok], yy[ok], hi[ok], yy[ok])
    graphics::axis(2, at = yy, labels = lab, las = 1, tick = FALSE)
    graphics::abline(v = 0, lty = 2, col = "grey50")
    cat("plot saved to", file, "\n")
    invisible(list(file = file, rows = k, drawn = sum(ok), mean = mn, lower = lo, upper = hi))
  }

# ---- from tests_adapters.R
.tst_first <- function(a, names) {           # first non-NULL of the given arg names, else a[[1]]
  for (n in names) if (!is.null(a[[n]])) return(a[[n]])
  if (length(a)) a[[1]] else NULL
}
.tst_groups <- function(formula, data) {     # y ~ g  ->  list of numeric vectors, one per level
  mf <- stats::model.frame(formula, data = data)
  if (ncol(mf) != 2L) stop("expected a formula of the form y ~ group (one grouping factor)")
  g <- mf[[2]]
  if (!is.factor(g)) g <- factor(g)
  unname(split(as.numeric(mf[[1]]), droplevels(g)))
}
.tst_alt_two_sided <- function(a, what) {
  if (!is.null(a$alternative) && a$alternative != "two.sided")
    stop(sprintf("native %s is two-sided only (alternative = '%s' not supported)", what, a$alternative))
}
.tst_conf <- function(a) if (is.null(a$conf.level)) 0.95 else a$conf.level
NATIVE[["r_ttest"]] <- function(a, M) {
    .tst_alt_two_sided(a, "one_sample_ttest")
    M$one_sample_ttest(a$x, mu0 = if (is.null(a$mu)) 0 else a$mu, confidence = .tst_conf(a))
  }
NATIVE[["r_ttest2"]] <- function(a, M) {
    .tst_alt_two_sided(a, "two_sample_ttest")
    M$two_sample_ttest(a$x, a$y, equal_var = isTRUE(a$var.equal), confidence = .tst_conf(a))
  }
NATIVE[["r_paired_t"]] <- function(a, M) {
    .tst_alt_two_sided(a, "paired_ttest")
    M$paired_ttest(a$x, a$y, confidence = .tst_conf(a))
  }
NATIVE[["r_wilcox"]] <- function(a, M) {
    alt <- if (is.null(a$alternative)) "two.sided" else a$alternative
    mu <- if (is.null(a$mu)) 0 else a$mu
    if (is.null(a$y)) return(M$wilcoxon_signed_rank(a$x - mu, alternative = alt))
    if (isTRUE(a$paired)) return(M$wilcoxon_signed_rank(a$x - a$y - mu, alternative = alt))
    M$mann_whitney_u(a$x - mu, a$y, alternative = alt)
  }
NATIVE[["r_anova"]] <- function(a, M) {
    f <- .tst_first(a, c("formula", "y"))
    mf <- stats::model.frame(f, data = a$data)
    if (ncol(mf) == 2L) return(do.call(M$one_way_anova, .tst_groups(f, a$data)))
    if (ncol(mf) == 3L) {   # y ~ A + B / y ~ A * B: Type-II two-way (= aov's sequential SS when balanced)
      d <- data.frame(y = mf[[1]], A = factor(mf[[2]]), B = factor(mf[[3]]))
      names(d) <- names(mf)
      return(M$two_way_anova(d, names(mf)[1], names(mf)[2], names(mf)[3]))
    }
    stop("native ANOVA supports y ~ g (one-way) or y ~ A * B (two-way factorial) only")
  }
NATIVE[["r_kruskal"]] <- function(a, M) do.call(M$kruskal_wallis, .tst_groups(.tst_first(a, c("formula", "y")), a$data))
NATIVE[["r_chisq"]] <- function(a, M) {
    corr <- if (is.null(a$correct)) TRUE else a$correct
    x <- a$x
    if (is.matrix(x) || is.table(x) || is.data.frame(x)) return(M$chi2_independence(as.matrix(x), correction = corr))
    if (!is.null(a$y)) return(M$chi2_independence(table(x, a$y), correction = corr))
    M$chi2_goodness_of_fit(x, expected = a$p)
  }
NATIVE[["r_fisher"]] <- function(a, M) {
    tab <- if (is.null(a$y)) as.matrix(a$x) else table(a$x, a$y)
    # morie's exact test is for 2 x 2 tables; a larger table goes to R's own stats::fisher.test
    if (!identical(dim(tab), c(2L, 2L))) return(stats::fisher.test(tab))
    M$fisher_exact_test(tab, alternative = if (is.null(a$alternative)) "two.sided" else a$alternative)
  }
NATIVE[["r_shapiro"]] <- function(a, M) M$shapiro_wilk(a$x)
NATIVE[["r_ks"]] <- function(a, M) {
    if (is.numeric(a$y)) return(M$ks_test_two_sample(a$x, a$y))
    cdf <- if (is.null(a$y)) "pnorm" else as.character(a$y)
    extra <- a[setdiff(names(a), c("x", "y", ""))]
    M$ks_test_one_sample(a$x, cdf = cdf, args = extra)
  }
NATIVE[["r_cor"]] <- function(a, M) {
    .tst_alt_two_sided(a, "correlation")
    method <- if (is.null(a$method)) "pearson" else match.arg(a$method, c("pearson", "spearman", "kendall"))
    switch(method,
           pearson = M$pearson_correlation(a$x, a$y, confidence = .tst_conf(a)),
           spearman = M$spearman_correlation(a$x, a$y, confidence = .tst_conf(a)),
           kendall = M$kendall_correlation(a$x, a$y))
  }
NATIVE[["r_mcnemar"]] <- function(a, M) {
    tab <- if (is.null(a$y)) as.matrix(a$x) else table(a$x, a$y)
    if (identical(a$correct, FALSE)) stop("native mcnemar_test always applies the continuity correction (correct=TRUE)")
    M$mcnemar_test(tab)
  }
NATIVE[["r_bartlett"]] <- function(a, M) do.call(M$bartlett_test, .tst_groups(.tst_first(a, c("formula", "y")), a$data))
NATIVE[["r_levene"]] <- function(a, M) {
    center <- if (is.null(a$center)) "median" else as.character(a$center)
    do.call(M$levene_test, c(.tst_groups(.tst_first(a, c("y", "formula")), a$data), list(center = center)))
  }
NATIVE[["r_friedman"]] <- function(a, M) {
    obj <- .tst_first(a, c("*", "formula", "y"))
    if (inherits(obj, "formula")) {
      rhs <- obj[[3]]
      if (!(is.call(rhs) && identical(rhs[[1]], as.name("|"))))
        stop("formula must be y ~ treatment | block")
      f2 <- obj
      f2[[3]] <- call("+", rhs[[2]], rhs[[3]])
      mf <- stats::model.frame(f2, data = a$data)
      trt <- factor(mf[[2]]); blk <- factor(mf[[3]])
      if (any(table(blk, trt) > 1L)) stop("not an unreplicated complete block design")
      mat <- tapply(as.numeric(mf[[1]]), list(blk, trt), function(v) v[1])
    } else {
      mat <- as.matrix(obj)
    }
    mat <- mat[stats::complete.cases(mat), , drop = FALSE]   # friedman.test drops incomplete blocks
    do.call(M$friedman_test, lapply(seq_len(ncol(mat)), function(j) mat[, j]))
  }
