// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// morie_normal_pdf_cpp
NumericVector morie_normal_pdf_cpp(NumericVector x, double mean, double sd);
RcppExport SEXP _morie_morie_normal_pdf_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_normal_pdf_cpp(x, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// morie_mean_cpp
double morie_mean_cpp(NumericVector x);
RcppExport SEXP _morie_morie_mean_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_mean_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// morie_var_cpp
double morie_var_cpp(NumericVector x, int ddof);
RcppExport SEXP _morie_morie_var_cpp(SEXP xSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_var_cpp(x, ddof));
    return rcpp_result_gen;
END_RCPP
}
// morie_cor_pearson_cpp
double morie_cor_pearson_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _morie_morie_cor_pearson_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(morie_cor_pearson_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_morie_morie_normal_pdf_cpp", (DL_FUNC) &_morie_morie_normal_pdf_cpp, 3},
    {"_morie_morie_mean_cpp", (DL_FUNC) &_morie_morie_mean_cpp, 1},
    {"_morie_morie_var_cpp", (DL_FUNC) &_morie_morie_var_cpp, 2},
    {"_morie_morie_cor_pearson_cpp", (DL_FUNC) &_morie_morie_cor_pearson_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_morie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
