// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// morie_normal_pdf_cpp
NumericVector morie_normal_pdf_cpp(NumericVector x, double mean, double sd);
RcppExport SEXP _morie_morie_normal_pdf_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_normal_pdf_cpp(x, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// morie_mean_cpp
double morie_mean_cpp(NumericVector x);
RcppExport SEXP _morie_morie_mean_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_mean_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// morie_var_cpp
double morie_var_cpp(NumericVector x, int ddof);
RcppExport SEXP _morie_morie_var_cpp(SEXP xSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_var_cpp(x, ddof));
    return rcpp_result_gen;
END_RCPP
}
// morie_cor_pearson_cpp
double morie_cor_pearson_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _morie_morie_cor_pearson_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(morie_cor_pearson_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_exp_const_cpp
double morie_hawkes_ll_exp_const_cpp(NumericVector t, double T, double a0, double eta, double beta);
RcppExport SEXP _morie_morie_hawkes_ll_exp_const_cpp(SEXP tSEXP, SEXP TSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_exp_const_cpp(t, T, a0, eta, beta));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_weibull_const_cpp
double morie_hawkes_ll_weibull_const_cpp(NumericVector t, double T, double a0, double eta, double alpha, double lam);
RcppExport SEXP _morie_morie_hawkes_ll_weibull_const_cpp(SEXP tSEXP, SEXP TSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_weibull_const_cpp(t, T, a0, eta, alpha, lam));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_lomax_const_cpp
double morie_hawkes_ll_lomax_const_cpp(NumericVector t, double T, double a0, double eta, double alpha, double c);
RcppExport SEXP _morie_morie_hawkes_ll_lomax_const_cpp(SEXP tSEXP, SEXP TSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_lomax_const_cpp(t, T, a0, eta, alpha, c));
    return rcpp_result_gen;
END_RCPP
}
// morie_hawkes_ll_gamma_const_cpp
double morie_hawkes_ll_gamma_const_cpp(NumericVector t, double T, double a0, double eta, double alpha, double beta);
RcppExport SEXP _morie_morie_hawkes_ll_gamma_const_cpp(SEXP tSEXP, SEXP TSEXP, SEXP a0SEXP, SEXP etaSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(morie_hawkes_ll_gamma_const_cpp(t, T, a0, eta, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get
std::string siu_http_get(std::string url, int timeout_s);
RcppExport SEXP _morie_siu_http_get(SEXP urlSEXP, SEXP timeout_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get(url, timeout_s));
    return rcpp_result_gen;
END_RCPP
}
// siu_curl_version
std::string siu_curl_version();
RcppExport SEXP _morie_siu_curl_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(siu_curl_version());
    return rcpp_result_gen;
END_RCPP
}
// siu_http_get_many
Rcpp::CharacterVector siu_http_get_many(Rcpp::CharacterVector urls, int concurrency, int timeout_s);
RcppExport SEXP _morie_siu_http_get_many(SEXP urlsSEXP, SEXP concurrencySEXP, SEXP timeout_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type urls(urlsSEXP);
    Rcpp::traits::input_parameter< int >::type concurrency(concurrencySEXP);
    Rcpp::traits::input_parameter< int >::type timeout_s(timeout_sSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_http_get_many(urls, concurrency, timeout_s));
    return rcpp_result_gen;
END_RCPP
}
// siu_parse_report
Rcpp::CharacterVector siu_parse_report(std::string html, int drid, std::string url);
RcppExport SEXP _morie_siu_parse_report(SEXP htmlSEXP, SEXP dridSEXP, SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type html(htmlSEXP);
    Rcpp::traits::input_parameter< int >::type drid(dridSEXP);
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(siu_parse_report(html, drid, url));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_morie_morie_normal_pdf_cpp", (DL_FUNC) &_morie_morie_normal_pdf_cpp, 3},
    {"_morie_morie_mean_cpp", (DL_FUNC) &_morie_morie_mean_cpp, 1},
    {"_morie_morie_var_cpp", (DL_FUNC) &_morie_morie_var_cpp, 2},
    {"_morie_morie_cor_pearson_cpp", (DL_FUNC) &_morie_morie_cor_pearson_cpp, 2},
    {"_morie_morie_hawkes_ll_exp_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_exp_const_cpp, 5},
    {"_morie_morie_hawkes_ll_weibull_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_weibull_const_cpp, 6},
    {"_morie_morie_hawkes_ll_lomax_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_lomax_const_cpp, 6},
    {"_morie_morie_hawkes_ll_gamma_const_cpp", (DL_FUNC) &_morie_morie_hawkes_ll_gamma_const_cpp, 6},
    {"_morie_siu_http_get", (DL_FUNC) &_morie_siu_http_get, 2},
    {"_morie_siu_curl_version", (DL_FUNC) &_morie_siu_curl_version, 0},
    {"_morie_siu_http_get_many", (DL_FUNC) &_morie_siu_http_get_many, 3},
    {"_morie_siu_parse_report", (DL_FUNC) &_morie_siu_parse_report, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_morie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
