#!/usr/bin/env python3
"""Generate static-visibility artifacts for morie.fn from _lazy_map.json.

morie.fn hosts ~36k lazily-loaded single-callable modules resolved at runtime
via PEP-562 ``__getattr__`` (see fn/__init__.py). Runtime import stays ~0.05s
because nothing is imported until accessed. The tradeoff: static tools (IDEs,
type-checkers, import/dependency graphs, Sphinx autodoc) cannot see through the
dynamic ``__getattr__`` + ``_lazy_map.json`` indirection, so every callable
appears as an isolated node.

This script closes that gap at ZERO runtime cost by emitting:

  1. fn/__init__.pyi  -- a type stub declaring every callable as an attribute of
     ``morie.fn``. Stubs are never executed, so type-checkers/IDEs see all ~36k
     names with no import penalty.
  2. docs/source/api/fn-catalog.rst -- a browsable catalogue of every callable
     (name + hosting module), so users can discover the full surface and know it
     ships with the wheel.

Run from the repo root:  python scripts/gen_fn_stubs.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FN_DIR = REPO / "src" / "morie" / "fn"
MAP_PATH = FN_DIR / "_lazy_map.json"
PYI_PATH = FN_DIR / "__init__.pyi"
CATALOG_PATH = REPO / "docs" / "source" / "api" / "fn-catalog.rst"


def _load_map() -> dict[str, str]:
    with open(MAP_PATH) as fh:
        return json.load(fh)


def write_pyi(lazy: dict[str, str]) -> int:
    names = sorted(lazy)
    lines = [
        "# Auto-generated by scripts/gen_fn_stubs.py -- DO NOT EDIT BY HAND.",
        "# Type stub exposing every lazily-loaded morie.fn callable to static",
        "# tools (IDEs, mypy/pyright, import graphs) at zero runtime cost.",
        "# Regenerate after changing fn/_lazy_map.json.",
        "from typing import Any",
        "",
        "def __getattr__(name: str) -> Any: ...",
        "",
    ]
    for n in names:
        # Declaring each as a function makes it show as a callable in IDEs.
        lines.append(f"def {n}(*args: Any, **kwargs: Any) -> Any: ...")
    lines.append("")
    PYI_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(names)


def write_catalog(lazy: dict[str, str]) -> int:
    names = sorted(lazy)
    out = [
        ".. _fn-catalog:",
        "",
        "The morie.fn Function Catalogue",
        "===============================",
        "",
        f"``morie.fn`` ships **{len(names):,} single-purpose callables** -- every one",
        "is included in the wheel and importable straight after ``pip install morie``.",
        "They are stored as compact archives inside the package and resolved lazily,",
        "so ``import morie.fn`` stays ~0.05 s and costs ~28 MB regardless of how many",
        "you use.",
        "",
        "Accessing a callable",
        "--------------------",
        "",
        ".. code-block:: python",
        "",
        "    import morie.fn",
        "    f = morie.fn.autocorrelation      # lazily imported on first access",
        "    morie.fn.describe('autocorrelation')  # one-line description + signature",
        "",
        "Discovering the full surface",
        "----------------------------",
        "",
        ".. code-block:: python",
        "",
        "    import morie.fn",
        "    names = dir(morie.fn)             # all callable names",
        "    len(names)                        # the full count",
        "    morie.fn.load_all()               # opt-in: eagerly import every callable",
        "                                      # (~20 s, ~400 MB) for exploration or",
        "                                      # static-graph tooling",
        "",
        "Full list",
        "---------",
        "",
        ".. csv-table::",
        "   :header: \"Callable\", \"Module\"",
        "   :widths: 60, 40",
        "",
    ]
    for n in names:
        out.append(f'   "{n}", "{lazy[n]}"')
    out.append("")
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text("\n".join(out), encoding="utf-8")
    return len(names)


def main(argv: list[str] | None = None) -> int:
    lazy = _load_map()
    n_pyi = write_pyi(lazy)
    n_cat = write_catalog(lazy)
    print(f"wrote {PYI_PATH.relative_to(REPO)} ({n_pyi:,} stubs)")
    print(f"wrote {CATALOG_PATH.relative_to(REPO)} ({n_cat:,} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
