# SPDX-License-Identifier: AGPL-3.0-or-later
# Build src/morie/rscripts/bridge_natives.R from the parity files in tests/r_bridge_parity/.
#
# Each parity file defines ADAPTERS[["r_x"]] <- list(native, reference, compare, tol, args, note)
# plus helper functions and example data. Only the native adapters and the helper functions they
# use ship with morie: the reference packages and the example data stay in the tests. Run from the
# repository root:  Rscript scripts/r_bridge_natives.R
options(keep.source = TRUE)
files <- Sys.glob("tests/r_bridge_parity/*_adapters.R")
out <- c(
  "# SPDX-License-Identifier: AGPL-3.0-or-later",
  "# GENERATED by scripts/r_bridge_natives.R from tests/r_bridge_parity/*_adapters.R -- do not edit.",
  "# The R bridge's adapters: each NATIVE[[\"r_x\"]] calls morie's own R functions (M is the namespace",
  "# of rmorie or morie). No reference package is used here; tests/r_bridge_parity checks the numbers",
  "# against them.",
  "NATIVE <- list()",
  "`%||%` <- function(a, b) if (is.null(a)) b else a"
)
text_of <- function(f) {
  sr <- attr(f, "srcref")
  if (is.null(sr)) paste(deparse(f), collapse = "\n") else paste(as.character(sr), collapse = "\n")
}
ref_pkgs <- paste(c("car", "lmtest", "effectsize", "pwr", "lme4", "quantreg", "MatchIt", "ipw", "AIPW",
                    "DoubleML", "rdrobust", "ivreg", "Synth", "tableone", "stargazer", "mice", "Amelia",
                    "survey", "metafor", "meta", "ggplot2", "survminer", "forestplot", "mlr3",
                    "SuperLearner", "did", "gtsummary", "naniar", "nlme", "mgcv", "MASS"), collapse = "|")
is_helper <- function(v) {
  if (is.environment(v)) v <- as.list(v, all.names = TRUE)
  is.function(v) || (is.list(v) && any(vapply(v, is.function, logical(1))))
}
for (file in files) {
  env <- new.env(parent = globalenv())
  sys.source(file, envir = env, keep.source = TRUE)
  exprs <- parse(file, keep.source = TRUE)
  srcs <- attr(exprs, "srcref")
  objs <- setdiff(ls(env, all.names = TRUE), c("ADAPTERS", "%||%"))
  helpers <- objs[vapply(objs, function(n) is_helper(get(n, env)), logical(1))]
  data_names <- setdiff(objs, helpers)
  # only the helpers the natives use, followed through the helpers' own calls
  globals_of <- function(v) {
    if (is.environment(v)) v <- as.list(v, all.names = TRUE)
    if (is.function(v)) return(codetools::findGlobals(v, merge = TRUE))
    unique(unlist(lapply(Filter(is.function, v), codetools::findGlobals, merge = TRUE)))
  }
  shipped <- Filter(function(ad) !is.null(ad$native) && !identical(ad$ship, FALSE), env$ADAPTERS)
  natives <- lapply(shipped, `[[`, "native")
  need <- intersect(unique(unlist(lapply(natives, codetools::findGlobals, merge = TRUE))), helpers)
  repeat {
    more <- setdiff(intersect(unique(unlist(lapply(need, function(h) globals_of(get(h, env))))), helpers), need)
    if (!length(more)) break
    need <- c(need, more)
  }
  helpers_all <- helpers
  helpers <- need
  out <- c(out, "", sprintf("# ---- from %s", basename(file)))
  # helper definitions, by their source text: `name <- function(...)` or `name <- local({...})`
  for (i in seq_along(exprs)) {
    e <- exprs[[i]]
    if (!(is.call(e) && as.character(e[[1]]) %in% c("<-", "="))) next
    lhs <- e[[2]]
    keep <- (is.name(lhs) && as.character(lhs) %in% helpers) ||
      # a function added to a helper environment afterwards: `.helpers$name <- function(...)`
      (is.call(lhs) && identical(as.character(lhs[[1]]), "$") && is.name(lhs[[2]]) &&
         as.character(lhs[[2]]) %in% helpers && is.call(e[[3]]) &&
         identical(as.character(e[[3]][[1]]), "function"))
    if (keep) out <- c(out, paste(as.character(srcs[[i]]), collapse = "\n"))
  }
  for (cmd in names(env$ADAPTERS)) {
    f <- env$ADAPTERS[[cmd]]$native
    if (is.null(f) || identical(env$ADAPTERS[[cmd]]$ship, FALSE)) next
    uses <- codetools::findGlobals(f, merge = TRUE)
    bad <- intersect(uses, data_names)
    if (length(bad)) stop(sprintf("%s: native uses test data %s", cmd, paste(bad, collapse = ", ")))
    body_txt <- text_of(f)
    if (grepl(paste0("\\b(", ref_pkgs, ")::"), body_txt))
      stop(sprintf("%s: native calls a reference package", cmd))
    out <- c(out, sprintf("NATIVE[[\"%s\"]] <- %s", cmd, body_txt))
  }
}
if (any(grepl("\\beval\\(|\\bparse\\(", out))) stop("eval()/parse() must not ship in the bridge natives")
if (any(grepl(paste0("\\b(", ref_pkgs, ")::"), out))) {
  stop("a reference package is named in the shipped natives: ",
       paste(grep(paste0("\\b(", ref_pkgs, ")::"), out, value = TRUE), collapse = " | "))
}
writeLines(out, "src/morie/rscripts/bridge_natives.R")
cat("wrote src/morie/rscripts/bridge_natives.R with", sum(grepl("^NATIVE\\[\\[", out)), "adapters\n")
