# morie.fn -- slice s03 (rootcoder007/morie)
"""The self-play evaluation gate.

Source consulted (FETCHED): Silver, D. et al. (2018), arXiv:1712.01815,
which describes the gate and then its removal, verbatim: "In AlphaGo
Zero, self-play games were generated by the best player from all
previous iterations.  After each iteration of training, the performance
of the new player was measured against the best player; if it won by a
margin of 55% then it replaced the best player ...  In contrast,
AlphaZero simply maintains a single neural network that is updated
continually ... omitting the evaluation step and the selection of best
player."

So the 55% gate is AlphaGo Zero's (Silver et al., *Nature* 550,
354-359), not AlphaZero's, and this function implements AlphaGo Zero's
rule while saying so.  The score is the usual chess score, a win
counting one and a draw a half:

    score = (wins + draws / 2) / games

The exact binomial tail probability of reaching that score under a fair
match is returned as well, computed from the binomial CDF with p = 1/2
so that a 55% result out of ten games is not mistaken for evidence.
"""

from __future__ import annotations

import math

from . import _array_core as np  # noqa: F401

from ._richresult import RichResult

__all__ = ["alphazero_self_play_eval"]


def alphazero_self_play_eval(new_net, old_net=None, n_games=100, wins=None,
                             draws=0, threshold=0.55):
    """Decide whether a candidate network replaces the current best.

    Parameters
    ----------
    new_net, old_net : any
        Carried through untouched; the identifiers of the two players.
    n_games : int
        Number of evaluation games.
    wins : int
        Wins for ``new_net``.  When None, ``new_net`` is read as the win
        count itself and ``old_net`` as the loss count.
    draws : int
        Drawn games.
    threshold : float
        The replacement margin; AlphaGo Zero used 0.55.

    Returns
    -------
    RichResult with payload:
        estimate : the score of the candidate
        replace  : whether the gate opens
        p_value  : one-sided binomial tail at p = 1/2 for the win count
        wins, draws, losses, n
    """
    if wins is None:
        w = float(new_net)
        l = float(old_net) if old_net is not None else 0.0
        d = float(draws)
        n = w + l + d
    else:
        w = float(wins)
        d = float(draws)
        n = float(n_games)
        l = n - w - d
    score = (w + 0.5 * d) / n if n > 0.0 else float("nan")
    dec = int(round(w + l))
    kk = int(round(w))
    p = float("nan")
    if dec > 0:
        tail = 0.0
        for i in range(kk, dec + 1):
            tail += math.exp(
                math.lgamma(dec + 1.0) - math.lgamma(i + 1.0)
                - math.lgamma(dec - i + 1.0) - dec * math.log(2.0)
            )
        p = tail
    return RichResult(
        title="Self-play evaluation gate",
        summary_lines=[("score", score), ("threshold", threshold)],
        payload={
            "estimate": score,
            "score": score,
            "replace": score > float(threshold),
            "p_value": p,
            "wins": w,
            "draws": d,
            "losses": l,
            "n": n,
            "method": ("AlphaGo Zero self-play evaluation gate (55%); AlphaZero "
                       "itself omits this step and updates continually"),
        },
    )


def cheatsheet():
    return "agselp: AlphaZero self-play evaluation"
