"""AR-sieve bootstrap for stationary time series (Buhlmann 1997)."""

import math

from . import _array_core as np
from ._richresult import RichResult

__all__ = ["btarsv", "ar_sieve_bootstrap"]


def _yule_walker(xc, p):
    # Levinson-Durbin on sample autocovariances (Buhlmann Sec. 2:
    # "usually ... by the Yule-Walker estimates")
    n = len(xc)
    g = [sum(xc[t] * xc[t + k] for t in range(n - k)) / n
         for k in range(p + 1)]
    if g[0] <= 0:
        raise ValueError("degenerate series")
    phi = [0.0] * p
    prev = [0.0] * p
    v = g[0]
    for k in range(1, p + 1):
        acc = g[k] - sum(prev[j] * g[k - 1 - j] for j in range(k - 1))
        ref = acc / v
        phi[k - 1] = ref
        for j in range(k - 1):
            phi[j] = prev[j] - ref * prev[k - 2 - j]
        v *= (1.0 - ref * ref)
        prev = phi[:]
    return phi[:p], v


def btarsv(x, p=None, statistic=None, B=500, burn=100, seed=0,
           p_max=None):
    """
    Sieve bootstrap: AR(p) approximation + residual resampling.

    Buhlmann (1997), Sec. 2: subtract the sample mean; fit an
    autoregression of order p by the Yule-Walker estimates; form the
    residuals eps_t = sum_{j=0}^{p} phi_j (X_{t-j} - Xbar)
    (phi_0 = 1), t = p+1..n; CENTRE them; the bootstrap sample is
    generated by the fitted AR recursion driven by iid draws from
    the centred residuals' empirical cdf (with burn-in), plus Xbar.
    The order may grow with n (the sieve); when ``p`` is omitted it
    is chosen by AIC over 1..p_max as Buhlmann suggests ("using,
    for example, the AIC").

    Sources
    -------
    Buhlmann, P. (1997). Sieve bootstrap for time series.
    *Bernoulli*, 3(2), 123-148, Sec. 2 (definition) and Sec. 3
    (consistency) (local copy
    fetched-wave3/Sieve_bootstrap_for_time_series.pdf).

    Parameters
    ----------
    x : sequence of float
        Observed series.
    p : int, optional
        AR order (default AIC-selected).
    statistic : callable, optional
        statistic(series) -> float (default the mean).
    B : int
        Bootstrap replicates.
    burn : int
        Burn-in length for the AR regeneration.
    seed : int
        Native-RNG seed (SplitMix64; mirrored by .ghc_rng in R).
    p_max : int, optional
        AIC search bound (default 10 log10(n)).

    Returns
    -------
    RichResult
        Keys: estimate, se, replicates, phi (fitted coefficients),
        p, sigma2 (innovation variance), residual_mean (0 exactly).
    """
    xv = [float(v) for v in x]
    n = len(xv)
    if n < 20:
        raise ValueError("need at least 20 observations")
    if statistic is None:
        statistic = lambda s: sum(s) / len(s)
    xbar = sum(xv) / n
    xc = [v - xbar for v in xv]
    if p is None:
        pm = p_max if p_max is not None else max(1, int(10 * math.log10(n)))
        best = None
        for cand in range(1, min(pm, n // 3) + 1):
            _, v = _yule_walker(xc, cand)
            aic = n * math.log(max(v, 1e-300)) + 2.0 * cand
            if best is None or aic < best[0]:
                best = (aic, cand)
        p = best[1]
    p = int(p)
    if not (1 <= p < n // 2):
        raise ValueError("order p out of range")
    phi, sigma2 = _yule_walker(xc, p)
    resid = []
    for t in range(p, n):
        e = xc[t] - sum(phi[j] * xc[t - 1 - j] for j in range(p))
        resid.append(e)
    rbar = sum(resid) / len(resid)
    resid = [e - rbar for e in resid]                 # centred
    m = len(resid)
    rng = np.random.default_rng(seed)
    that = float(statistic(xv))
    reps = []
    for _b in range(int(B)):
        state = [0.0] * p
        series = []
        for t in range(burn + n):
            eps = resid[min(int(float(rng.uniform()) * m), m - 1)]
            val = sum(phi[j] * state[j] for j in range(p)) + eps
            state = [val] + state[:p - 1]
            if t >= burn:
                series.append(val + xbar)
        reps.append(float(statistic(series)))
    mu = sum(reps) / len(reps)
    se = math.sqrt(sum((r - mu) ** 2 for r in reps) / (len(reps) - 1))
    return RichResult(payload={
        "estimate": that,
        "se": se,
        "replicates": reps,
        "phi": phi,
        "p": p,
        "sigma2": sigma2,
        "residual_mean": sum(resid) / m,
        "B": int(B),
        "seed": int(seed),
        "method": "AR-sieve bootstrap (Buhlmann 1997, Sec. 2)",
    })


# long descriptive alias (stub-era name)
ar_sieve_bootstrap = btarsv


def cheatsheet():
    return "btarsv: YW AR(p) fit; resample centred residuals; regen AR + Xbar"
