# morie.fn -- wave 2 slice x_0_01 (rootcoder007/morie)
"""Sieve bootstrap: fit a growing parametric model, resample its innovations.

Buehlmann, P. (1997), "Sieve Bootstrap for Time Series", *Bernoulli*
3(2), 123-148, doi:10.2307/3318584 (verified against Crossref).

The block bootstrap keeps dependence by keeping data contiguous, which
costs it the ability to extrapolate beyond the observed sample paths.
The sieve bootstrap instead approximates the process by a sequence of
finite-dimensional models whose order grows with n -- Buehlmann's sieve
is the AR(p) family with p = p(n) -> infinity -- fits one, and resamples
the FITTED INNOVATIONS iid, which is legitimate precisely because a
correctly ordered linear sieve leaves white residuals.  The bootstrap
series is then regenerated by running the fitted recursion forward on
the resampled innovations, so it is a genuinely new path rather than a
rearrangement of the old one.

This module takes the general form of the procedure: ``fit_fn(x)``
returns a model, ``rvs_fn(model, resid, n, g)`` regenerates a series,
and ``stat`` is evaluated on each regenerated series.  The default sieve
is the AR(p) one with p chosen by AIC over 0..p_max, fitted by the
package's ridge-stabilised least squares on the lagged design, with a
burn-in of 100 discarded points so the regenerated path is not anchored
at the fitted starting values.

Anchors: with p_max = 0 the sieve is white noise, the "residuals" are
the centred data, and the procedure reduces to the ordinary iid
bootstrap; and on a series that is exactly an AR(1) with no noise
(x_t = rho x_{t-1}) the AIC order is 1, the fitted coefficient is rho to
machine precision, and the residuals are identically zero, so every
bootstrap path is identically zero after burn-in.
"""

from __future__ import annotations

import math

from . import _s03core as core

from ._richresult import RichResult

__all__ = ["boot_sieve_general"]

_BURN = 100


def ar_fit(x, p_max=None):
    """AR(p) sieve fit with AIC order selection.  Returns (phi, mu, resid, p, aic)."""
    n = len(x)
    if p_max is None:
        p_max = int(math.floor(10.0 * math.log10(float(n))))
    p_max = int(p_max)
    if p_max < 0:
        raise ValueError("boot_sieve_general: p_max must be non-negative")
    if p_max > n - 2:
        p_max = max(n - 2, 0)
    mu = core.mean(x)
    z = [u - mu for u in x]
    best = None
    for p in range(p_max + 1):
        # common sample so the AIC values are comparable across p
        m = n - p_max
        if m < 2:
            break
        y = [z[i] for i in range(p_max, n)]
        if p == 0:
            phi = []
            res = list(y)
        else:
            X = [[z[i - k - 1] for k in range(p)] for i in range(p_max, n)]
            phi = core.lstsq(X, y)
            res = [y[t] - sum(X[t][k] * phi[k] for k in range(p)) for t in range(m)]
        s2 = sum(u * u for u in res) / m
        if s2 <= 0.0:
            aic = -float("inf")
        else:
            aic = m * math.log(s2) + 2.0 * p
        if best is None or aic < best[4]:
            best = (phi, mu, res, p, aic)
    if best is None:
        raise ValueError("boot_sieve_general: series too short for the sieve")
    return best


def _ar_rvs(model, resid, n, g):
    phi, mu = model
    p = len(phi)
    m = len(resid)
    hist = [0.0] * max(p, 1)
    out = []
    for t in range(_BURN + n):
        j = int(g.unif() * m)
        if j >= m:
            j = m - 1
        v = resid[j]
        for k in range(p):
            v += phi[k] * hist[k]
        for k in range(len(hist) - 1, 0, -1):
            hist[k] = hist[k - 1]
        if hist:
            hist[0] = v
        if t >= _BURN:
            out.append(v + mu)
    return out


def boot_sieve_general(x, fit_fn=None, rvs_fn=None, stat=None, B=200, seed=1,
                       p_max=None, alpha=0.05):
    """Sieve bootstrap replicates.

    Parameters
    ----------
    x : array-like
        The series, in time order.
    fit_fn : callable, optional
        ``fit_fn(x)`` returning ``(model, resid)``.  Defaults to the
        AR(p) sieve with AIC order selection.
    rvs_fn : callable, optional
        ``rvs_fn(model, resid, n, g)`` regenerating a series.  Defaults
        to the AR recursion with a burn-in of 100.
    stat : callable, optional
        Statistic of a series.  Defaults to the mean.
    B : int
        Replicates.
    seed : int
        Seed for the shared deterministic stream.
    p_max : int, optional
        Maximum sieve order.  Defaults to ``floor(10 log10 n)``.
    alpha : float
        Two-sided error rate.

    Returns
    -------
    RichResult
        ``theta_b``, ``estimate``, ``se``, ``lo``/``hi``, ``order``
        (selected p), ``phi`` (fitted coefficients), ``sigma2``
        (innovation variance), ``aic``, ``n``, ``B``.
    """
    from . import _tail1core as C

    xx = core.vec(x)
    n = len(xx)
    if n < 4:
        raise ValueError("boot_sieve_general: need at least four observations")
    if int(B) < 2:
        raise ValueError("boot_sieve_general: need at least two replicates")
    a = float(alpha)
    if not (0.0 < a < 1.0):
        raise ValueError("boot_sieve_general: alpha must lie strictly between 0 and 1")
    f = core.mean if stat is None else stat
    if fit_fn is None:
        phi, mu, res, order, aic = ar_fit(xx, p_max)
        model = (phi, mu)
    else:
        model, res = fit_fn(xx)
        phi = []
        order = 0
        aic = float("nan")
    rb = core.mean(res)
    res = [u - rb for u in res]
    r = _ar_rvs if rvs_fn is None else rvs_fn
    g = C.Lcg(seed)
    theta = [float(f(r(model, res, n, g))) for _ in range(int(B))]
    return RichResult(
        title="Sieve bootstrap (Buehlmann 1997)",
        summary_lines=[("n", n), ("order", order), ("B", int(B))],
        payload={
            "theta_b": theta,
            "estimate": float(f(xx)),
            "se": core.sd(theta, 1),
            "lo": core.quantile7(theta, a / 2.0),
            "hi": core.quantile7(theta, 1.0 - a / 2.0),
            "order": order,
            "phi": phi,
            "sigma2": sum(u * u for u in res) / len(res),
            "aic": aic,
            "n": n,
            "B": int(B),
            "method": "Buehlmann (1997) Bernoulli 3(2):123-148, AR(p) sieve with AIC order",
        },
    )


def cheatsheet():
    return "btsieve: fit AR(p(n)), resample the WHITE residuals, regenerate; new paths, not rearranged old ones"
