# morie.fn -- function file (rootcoder007/morie)
"""Clayton copula bivariate survival for clustered event times."""

from . import _array_core as np

from ._richresult import RichResult

__all__ = ["clayton_copula_frailty"]


def _km(time, event):
    """Kaplan-Meier survival evaluated at the observed times."""
    order = np.argsort(time)
    t, e = time[order], event[order]
    n = t.size
    s = 1.0
    at_risk = n
    grid, vals = [0.0], [1.0]
    for i in range(n):
        if e[i] == 1:
            s *= 1 - 1 / max(at_risk, 1)
            grid.append(t[i])
            vals.append(s)
        at_risk -= 1
    return np.array(grid), np.array(vals)


def clayton_copula_frailty(time1, event1, time2, event2, theta=None):
    r"""Clayton (gamma-frailty) model for paired survival times.

    .. math:: S(t_1, t_2) = \big(S_1(t_1)^{-\theta}
              + S_2(t_2)^{-\theta} - 1\big)^{-1/\theta},

    the survival copula generated by a gamma frailty shared within
    the pair. The dependence maps to Kendall's tau by
    :math:`\tau = \theta/(\theta + 2)` (Czado Table 3.2), which is
    how ``theta`` is estimated when not supplied: from the sample
    tau of the observed pairs, inverted. Marginals are Kaplan-Meier,
    so the model is semiparametric.

    Parameters
    ----------
    time1, time2 : array-like, shape (n,)
        Observed times for the two members of each pair.
    event1, event2 : array-like of {0, 1}, shape (n,)
        Event indicators (0 = censored).
    theta : float, optional
        Clayton parameter; estimated from Kendall's tau if omitted.

    Returns
    -------
    RichResult
        keys: ``theta``, ``tau``, ``joint_survival`` (n, at each
        observed pair), ``s1``, ``s2``, ``n_pairs``, ``method``.

    References
    ----------
    Clayton, D. G. (1978). A model for association in bivariate life
    tables and its application in epidemiological studies of familial
    tendency in chronic disease incidence. *Biometrika*, 65(1),
    141-151.

    Czado, C. (2019). *Analyzing Dependent Data with Vine Copulas*.
    Springer. Table 3.2 p. 54 (tau = theta/(theta + 2)).
    """
    from . import _stats_core as _st

    t1 = np.asarray(time1, dtype=float).ravel()
    t2 = np.asarray(time2, dtype=float).ravel()
    e1 = np.asarray(event1, dtype=float).ravel()
    e2 = np.asarray(event2, dtype=float).ravel()
    n = t1.size
    if not (t2.size == n and e1.size == n and e2.size == n):
        raise ValueError("all four inputs must have the same length.")
    if np.any(t1 <= 0) or np.any(t2 <= 0):
        raise ValueError("times must be positive.")
    for e, nm in ((e1, "event1"), (e2, "event2")):
        if not np.all(np.isin(e, (0.0, 1.0))):
            raise ValueError(f"{nm} must be binary 0/1.")
    if n < 5:
        raise ValueError("need at least 5 pairs.")

    if theta is None:
        tau = float(_st.kendalltau(t1, t2).statistic)
        if not np.isfinite(tau) or tau <= 0:
            raise ValueError(
                "sample Kendall's tau is non-positive; Clayton admits only positive "
                "dependence -- supply theta explicitly or use a rotated family."
            )
        theta = 2.0 * tau / (1.0 - tau)
    theta = float(theta)
    if theta <= 0:
        raise ValueError(f"theta must be positive, got {theta}.")

    g1, v1 = _km(t1, e1)
    g2, v2 = _km(t2, e2)
    s1 = np.maximum(v1[np.searchsorted(g1, t1, side="right") - 1], 1e-8)
    s2 = np.maximum(v2[np.searchsorted(g2, t2, side="right") - 1], 1e-8)
    joint = (s1 ** (-theta) + s2 ** (-theta) - 1.0) ** (-1.0 / theta)

    return RichResult(
        payload={
            "theta": theta,
            "tau": float(theta / (theta + 2.0)),
            "joint_survival": joint,
            "s1": s1,
            "s2": s2,
            "n_pairs": int(n),
            "method": "Clayton survival copula with Kaplan-Meier margins",
        }
    )


def cheatsheet():
    return "clyfr: S(t1,t2) = (S1^-th + S2^-th - 1)^(-1/th); tau = th/(th+2)"
