# morie.fn -- function file (rootcoder007/morie)
"""Farey sequence of order n.

Classical number theory.  Triage confirmed this names no owning source; the
standard definition is implemented and no citation is manufactured.
"""


from ._richresult import RichResult, with_describe_pointer

__all__ = ["farey_seq"]


def farey_seq(n):
    """The Farey sequence F_n: every reduced fraction p/q in [0, 1]
    with q <= n, in ascending order.

    Generated by the neighbour recurrence rather than by enumerating
    and sorting: consecutive Farey fractions a/b and c/d satisfy
    bc - ad = 1, and the term after c/d is obtained from
    k = floor((n + b)/d) as (k c - a)/(k d - b).  That makes the walk
    linear in the length of the sequence and exact in integers.

    Parameters
    ----------
    n : int, the order; must be at least 1.

    Returns
    -------
    RichResult with keys estimate (the length |F_n|), terms (list of
    (numerator, denominator) pairs), values, n, method.
    """
    nn = int(n)
    if nn < 1:
        raise ValueError("order must be at least 1")
    a, b, c, d = 0, 1, 1, nn
    terms = [(a, b)]
    while c <= nn:
        terms.append((c, d))
        k = (nn + b) // d
        a, b, c, d = c, d, k * c - a, k * d - b
    return with_describe_pointer(RichResult(payload={
        "estimate": float(len(terms)), "terms": terms,
        "values": [p / float(q) for p, q in terms], "n": nn,
        "method": "Farey sequence of order n",
    }), "diopT")


def cheatsheet():
    return "diopT: Farey sequence enumeration"


# compact alias per ledger/NAMING.md
fareyseq = farey_seq
