# morie.fn -- function file (rootcoder007/morie)
r"""GRACE: contrastive graph learning at the node level.

Deep Graph InfoMax maximises mutual information between node
embeddings and a *global* summary obtained by a readout. GRACE's
objection is that the local-global framing depends heavily on that
readout being expressive, and that the injectivity it needs is not
guaranteed. Contrast **node against node** instead.

**Two views, corrupted two ways.** A view is generated by removing
edges and, separately, by masking feature dimensions -- topology and
attributes both. Doing both gives nodes genuinely different contexts
across the views, which is what the contrastive objective needs;
corrupting only one leaves the two views too similar to learn from.

**Three kinds of pair, and two of them are negatives.** For node
:math:`i` with embeddings :math:`u_i, v_i` in the two views, the pair
:math:`(u_i, v_i)` is positive. Every *other* node is a negative --
both in the other view (**inter-view**) and in the same view
(**intra-view**). Including the intra-view negatives is the part that
is easy to omit and matters: without them nothing pushes apart two
nodes that happen to sit in the same view.

.. math:: \ell(u_i, v_i) = \log
          \frac{e^{\theta(u_i,v_i)/\tau}}
               {\underbrace{e^{\theta(u_i,v_i)/\tau}}_{\text{positive}}
               + \underbrace{\sum_{k \ne i} e^{\theta(u_i,v_k)/\tau}}
                 _{\text{inter-view}}
               + \underbrace{\sum_{k \ne i} e^{\theta(u_i,u_k)/\tau}}
                 _{\text{intra-view}}},

with :math:`\theta` cosine similarity after a projection head and
:math:`\tau` a temperature. The overall objective averages
:math:`\ell(u_i,v_i)` and :math:`\ell(v_i,u_i)`, since the two views
are symmetric.

**No labels anywhere.** The method is unsupervised, and the paper
reports it beating supervised counterparts on transductive tasks.

References
----------
Zhu, Y., Xu, Y., Yu, F., Liu, Q., Wu, S. & Wang, L. (2020) "Deep Graph
Contrastive Representation Learning", *ICML Workshop on Graph
Representation Learning and Beyond*, arXiv:2006.04131. The abstract
and Sec. 1 (a node-level contrastive objective; two views generated by
corruption at both the topology and attribute levels -- removing edges
and masking features -- to give diverse node contexts; the criticism
that DGI's local-global MI maximisation depends on the readout; the
theoretical connection to mutual information and the triplet loss; and
that the unsupervised method surpasses supervised counterparts on
transductive tasks). Sec. 3 (the pairwise objective with positive,
inter-view negative and intra-view negative terms, and the symmetric
average over the two views).

Velickovic, P., Fedus, W., Hamilton, W. L., Lio, P., Bengio, Y. &
Hjelm, R. D. (2019) "Deep Graph Infomax", *ICLR 2019*,
arXiv:1809.10341. The local-global objective GRACE argues against.

Hjelm, R. D., Fedorov, A., Lavoie-Marchildon, S., Grewal, K.,
Bachman, P., Trischler, A. & Bengio, Y. (2019) "Learning deep
representations by mutual information estimation and maximization",
*ICLR 2019*, arXiv:1808.06670. Deep InfoMax; implemented in
:mod:`mienco`.
"""

import math

from . import _array_core as np
from . import _s03core as k
from ._richresult import RichResult

__all__ = ["drop_edges", "mask_features", "generate_view",
           "pair_loss", "grace_objective"]

_EPS = 1e-12


def drop_edges(edges, p, rng):
    r"""Topology-level corruption: remove each edge with probability
    :math:`p`."""
    pp = float(p)
    if not 0.0 <= pp < 1.0:
        raise ValueError("grace: the drop rate must lie in [0,1), got "
                         "%r" % (p,))
    return [e for e in edges if float(rng.uniform()) >= pp]


def mask_features(X, p, rng):
    r"""Attribute-level corruption: zero whole feature DIMENSIONS.

    Dimensions, not entries -- the mask is shared across nodes, which
    is what makes the view a different *view* rather than noise.
    """
    pp = float(p)
    if not 0.0 <= pp < 1.0:
        raise ValueError("grace: the mask rate must lie in [0,1), got "
                         "%r" % (p,))
    rows = [[float(v) for v in r] for r in k.mat(X)]
    d = len(rows[0])
    keep = [0.0 if float(rng.uniform()) < pp else 1.0
            for _ in range(d)]
    return {"X": [[rows[i][f] * keep[f] for f in range(d)]
                  for i in range(len(rows))],
            "kept": keep, "n_masked": int(d - sum(keep))}


def generate_view(X, edges, p_edge, p_feature, rng):
    r"""One view, corrupted on BOTH levels."""
    m = mask_features(X, p_feature, rng)
    return {"X": m["X"], "edges": drop_edges(edges, p_edge, rng),
            "n_masked_features": m["n_masked"]}


def _cos(a, b):
    na = math.sqrt(sum(v * v for v in a))
    nb = math.sqrt(sum(v * v for v in b))
    if na <= _EPS or nb <= _EPS:
        raise ValueError("grace: cosine similarity needs non-zero "
                         "vectors")
    return sum(a[i] * b[i] for i in range(len(a))) / (na * nb)


def pair_loss(U, V, i, tau=0.5, intra=True):
    r"""The per-pair objective.

    ``intra=False`` drops the same-view negatives, which is the term
    most often omitted.
    """
    t = float(tau)
    if t <= 0.0:
        raise ValueError("grace: the temperature must be positive")
    pos = math.exp(_cos(U[i], V[i]) / t)
    inter = sum(math.exp(_cos(U[i], V[j]) / t)
                for j in range(len(V)) if j != i)
    same = sum(math.exp(_cos(U[i], U[j]) / t)
               for j in range(len(U)) if j != i) if intra else 0.0
    return -math.log(pos / (pos + inter + same))


def grace_objective(U, V, tau=0.5, intra=True):
    r"""The symmetric average over both views."""
    n = len(U)
    if n != len(V):
        raise ValueError("grace: the views have %d and %d nodes"
                         % (n, len(V)))
    if n < 2:
        raise ValueError("grace: at least 2 nodes are needed for "
                         "negatives")
    tot = sum(pair_loss(U, V, i, tau, intra)
              + pair_loss(V, U, i, tau, intra) for i in range(n))
    return RichResult(payload={
        "estimate": tot / (2.0 * n), "loss": tot / (2.0 * n),
        "tau": float(tau), "intra_view_negatives": bool(intra),
        "n_nodes": n,
        "method": "node-level contrastive objective; Zhu et al. "
                  "(2020) Sec. 3",
        "note": "negatives come from BOTH views -- inter-view and "
                "intra-view; omitting the latter leaves same-view "
                "nodes unseparated",
    })


def cheatsheet():
    return ("grace: contrast NODE AGAINST NODE, not node against a "
            "global summary -- DGI's local-global objective leans on "
            "the readout being expressive. Two views by corrupting "
            "BOTH topology (drop edges) and attributes (mask feature "
            "DIMENSIONS). (u_i, v_i) is positive; every other node is "
            "a negative in the other view AND in the same view, and "
            "the INTRA-view term is the one people drop. InfoNCE with "
            "cosine similarity and temperature tau, averaged "
            "symmetrically. Fully unsupervised.")


# compact alias per ledger/NAMING.md
graphcontrastive = grace_objective
