# morie.fn -- function file (rootcoder007/morie)
r"""Buchberger's algorithm, and what a Gröbner basis is actually for.

**The problem the basis solves.** Division of one multivariate
polynomial by a *set* of polynomials is not well defined: the
remainder depends on the order the divisors are tried in. So
"is :math:`f` in the ideal generated by :math:`F`?" cannot be
answered by dividing by :math:`F` -- a zero remainder proves
membership, but a non-zero one proves nothing.

A Gröbner basis :math:`G` of that ideal fixes this. Dividing by
:math:`G` gives a remainder that does not depend on the order, and
that remainder is zero exactly when :math:`f` lies in the ideal.

**The criterion.** :math:`G` is a Gröbner basis when for every pair
:math:`g_i, g_j` the S-polynomial

.. math:: S(g_i, g_j) = \frac{L}{\mathrm{LT}(g_i)} g_i
                      - \frac{L}{\mathrm{LT}(g_j)} g_j,
          \qquad L = \mathrm{lcm}(\mathrm{LM}(g_i),
                                  \mathrm{LM}(g_j)),

reduces to zero over :math:`G`. The S-polynomial is built precisely
to cancel the two leading terms, exposing whatever leading term the
combination has underneath -- the leading terms that division cannot
otherwise see. Buchberger's algorithm is then the obvious loop: take
a pair, reduce its S-polynomial, and if the remainder is non-zero
adjoin it and start the new pairs it creates. It terminates because
the ideal of leading terms strictly grows, and Dickson's lemma
forbids an infinite strictly ascending chain.

**Everything depends on the monomial order.** ``lex``, ``grlex`` and
``grevlex`` are all offered, and they give genuinely different bases
for the same ideal: ``lex`` eliminates variables (so it solves
systems) but is expensive, ``grevlex`` is usually the cheapest. The
ideal, and therefore every membership answer, is the same in all of
them -- and the anchor checks exactly that rather than assuming it.

**Uniqueness.** The *reduced* basis -- monic, with no term of any
element divisible by the leading term of another -- is unique for a
given ideal and order. Two different generating sets of one ideal
must therefore produce the identical reduced basis, which is a check
that can fail and does if the reduction step is wrong.

**Coefficients are exact.** ``fractions.Fraction`` throughout: a
floating-point coefficient that should cancel to zero and instead
lands at 1e-17 turns a finite algorithm into a non-terminating one.

References
----------
Buchberger, B. (1965) *Ein Algorithmus zum Auffinden der
Basiselemente des Restklassenringes nach einem nulldimensionalen
Polynomideal*, PhD thesis, University of Innsbruck; translated by
M. P. Abramson as "Bruno Buchberger's PhD thesis 1965: An algorithm
for finding the basis elements of the residue class ring of a zero
dimensional polynomial ideal", *Journal of Symbolic Computation*
41(3-4), 475-511, doi:10.1016/j.jsc.2005.09.007. The S-polynomial,
the criterion that all S-polynomials reduce to zero, the completion
loop reproduced above, and the termination argument.

Buchberger, B. (1979) "A criterion for detecting unnecessary
reductions in the construction of Gröbner-bases", in *Symbolic and
Algebraic Computation (EUROSAM '79)*, Lecture Notes in Computer
Science 72, Springer, 3-21, doi:10.1007/3-540-09519-5_52, for the
first criterion used by ``prune=True``: a pair whose leading
monomials are coprime always reduces to zero and can be skipped.
"""

from fractions import Fraction

from ._richresult import RichResult

__all__ = ["poly", "monomials", "leading_term", "leading_monomial",
           "leading_coeff", "add", "sub", "mul", "spoly",
           "divide", "buchberger", "reduce_basis", "ideal_member",
           "groebner"]

ORDERS = ("lex", "grlex", "grevlex")


def _key(order):
    if order == "lex":
        return lambda e: tuple(e)
    if order == "grlex":
        return lambda e: (sum(e),) + tuple(e)
    if order == "grevlex":
        # total degree, then the NEGATED reversed exponents: a > b
        # when the rightmost non-zero entry of a - b is negative.
        return lambda e: (sum(e),) + tuple(-x for x in reversed(e))
    raise ValueError("groebn: order must be one of %s, got %r"
                     % (", ".join(ORDERS), order))


def poly(terms, nvars=None):
    r"""A polynomial as ``{exponent tuple: coefficient}``.

    Zero coefficients are dropped, so equality of the returned dicts
    is equality of polynomials.
    """
    if isinstance(terms, dict):
        items = terms.items()
    else:
        items = list(terms)
    out = {}
    n = None
    for e, cf in items:
        ev = tuple(int(x) for x in e)
        if any(x < 0 for x in ev):
            raise ValueError("groebn: negative exponent in %r" % (e,))
        if n is None:
            n = len(ev)
        elif len(ev) != n:
            raise ValueError("groebn: exponent vectors of differing "
                             "length, %d and %d" % (n, len(ev)))
        out[ev] = out.get(ev, Fraction(0)) + Fraction(cf)
    if nvars is not None:
        n = int(nvars) if n is None else n
        if out and n != int(nvars):
            raise ValueError("groebn: %d variables declared but the "
                             "exponents have %d" % (int(nvars), n))
    return {e: c for e, c in out.items() if c != 0}


def nvars(F):
    r"""The number of variables shared by a list of polynomials."""
    for f in F:
        for e in f:
            return len(e)
    return 0


def monomials(f, order="lex"):
    r"""The exponent vectors of ``f``, largest first in ``order``."""
    return sorted(f, key=_key(order), reverse=True)


def leading_monomial(f, order="lex"):
    r"""The largest exponent vector, or ``None`` for the zero
    polynomial."""
    return monomials(f, order)[0] if f else None


def leading_coeff(f, order="lex"):
    r"""The coefficient of the leading monomial."""
    lm = leading_monomial(f, order)
    return Fraction(0) if lm is None else f[lm]


def leading_term(f, order="lex"):
    r"""The leading term as a one-term polynomial."""
    lm = leading_monomial(f, order)
    return {} if lm is None else {lm: f[lm]}


def add(f, g):
    r"""Sum of two polynomials."""
    out = dict(f)
    for e, c in g.items():
        out[e] = out.get(e, Fraction(0)) + c
    return {e: c for e, c in out.items() if c != 0}


def sub(f, g):
    r"""Difference of two polynomials."""
    return add(f, {e: -c for e, c in g.items()})


def mul(f, g):
    r"""Product of two polynomials."""
    out = {}
    for e1, c1 in f.items():
        for e2, c2 in g.items():
            e = tuple(a + b for a, b in zip(e1, e2))
            out[e] = out.get(e, Fraction(0)) + c1 * c2
    return {e: c for e, c in out.items() if c != 0}


def scale(f, c):
    r"""Multiply by a scalar."""
    q = Fraction(c)
    return {} if q == 0 else {e: v * q for e, v in f.items()}


def _divides(a, b):
    return all(x <= y for x, y in zip(a, b))


def _lcm(a, b):
    return tuple(max(x, y) for x, y in zip(a, b))


def spoly(f, g, order="lex"):
    r"""The S-polynomial, built to cancel the two leading terms."""
    if not f or not g:
        raise ValueError("groebn: the S-polynomial of the zero "
                         "polynomial is not defined")
    lf, lg = leading_monomial(f, order), leading_monomial(g, order)
    L = _lcm(lf, lg)
    a = {tuple(x - y for x, y in zip(L, lf)):
         Fraction(1) / leading_coeff(f, order)}
    b = {tuple(x - y for x, y in zip(L, lg)):
         Fraction(1) / leading_coeff(g, order)}
    return sub(mul(a, f), mul(b, g))


def divide(f, G, order="lex"):
    r"""Multivariate division: :math:`f = \sum q_i g_i + r`.

    Returns the quotients and the remainder. The identity is exact
    and the anchor checks it.
    """
    Gs = [g for g in G if g]
    if not Gs:
        raise ValueError("groebn: division by an empty set")
    q = [{} for _ in Gs]
    r = {}
    p = dict(f)
    while p:
        lm = leading_monomial(p, order)
        lc = p[lm]
        for i, g in enumerate(Gs):
            lg = leading_monomial(g, order)
            if _divides(lg, lm):
                t = {tuple(x - y for x, y in zip(lm, lg)):
                     lc / leading_coeff(g, order)}
                q[i] = add(q[i], t)
                p = sub(p, mul(t, g))
                break
        else:
            r[lm] = lc
            del p[lm]
    return {"quotients": q, "remainder": r}


def normal_form(f, G, order="lex"):
    r"""The remainder of ``f`` on division by ``G``."""
    return divide(f, G, order)["remainder"]


def buchberger(F, order="lex", prune=True, reduced=True):
    r"""A Gröbner basis of the ideal generated by ``F``.

    ``prune`` applies Buchberger's first criterion; it changes the
    work done, never the reduced basis produced.
    """
    _key(order)
    G = [dict(f) for f in F if f]
    if not G:
        raise ValueError("groebn: no non-zero generators given")
    n = nvars(G)
    for g in G:
        for e in g:
            if len(e) != n:
                raise ValueError("groebn: generators in different "
                                 "numbers of variables")
    pairs = [(i, j) for i in range(len(G)) for j in range(i + 1, len(G))]
    n_pairs = n_skipped = n_reductions = 0
    while pairs:
        i, j = pairs.pop(0)
        n_pairs += 1
        li = leading_monomial(G[i], order)
        lj = leading_monomial(G[j], order)
        if prune and all(a == 0 or b == 0 for a, b in zip(li, lj)):
            # Coprime leading monomials: the S-polynomial always
            # reduces to zero (Buchberger 1979).
            n_skipped += 1
            continue
        n_reductions += 1
        r = normal_form(spoly(G[i], G[j], order), G, order)
        if r:
            G.append(r)
            pairs.extend((k, len(G) - 1) for k in range(len(G) - 1))
    basis = reduce_basis(G, order) if reduced else G
    return RichResult(payload={
        "estimate": basis, "basis": basis, "order": order,
        "size": len(basis), "reduced": bool(reduced),
        "n_pairs": n_pairs, "n_reductions": n_reductions,
        "n_skipped": n_skipped, "pruned": bool(prune),
        "method": "Buchberger (1965) completion"
                  + (" with the 1979 coprimality criterion"
                     if prune else ""),
    })


def reduce_basis(G, order="lex"):
    r"""The reduced basis: monic, and no term divisible by another's
    leading term. Unique for the ideal and the order.
    """
    H = [g for g in G if g]
    # Drop any element whose leading monomial another one divides.
    keep = []
    for i, g in enumerate(H):
        lg = leading_monomial(g, order)
        if not any(i != j and _divides(leading_monomial(h, order), lg)
                   for j, h in enumerate(H)
                   if not (j > i
                           and leading_monomial(h, order) == lg)):
            keep.append(g)
    out = []
    for i, g in enumerate(keep):
        rest = [h for j, h in enumerate(keep) if j != i] + out
        r = normal_form(g, rest, order) if rest else g
        if r:
            out.append(scale(r, Fraction(1)
                             / leading_coeff(r, order)))
    return sorted(out, key=lambda p: _key(order)(
        leading_monomial(p, order)), reverse=True)


def ideal_member(f, F, order="lex", basis=None):
    r"""Whether ``f`` lies in the ideal generated by ``F``.

    A zero remainder over a *Gröbner* basis is necessary and
    sufficient; over an arbitrary generating set it is only
    sufficient, which is the whole point of computing the basis.
    """
    G = basis if basis is not None else buchberger(F, order)["basis"]
    r = normal_form(f, G, order)
    return RichResult(payload={
        "estimate": not r, "member": not r, "remainder": r,
        "order": order, "basis": G,
        "method": "Buchberger (1965): zero normal form over a "
                  "Groebner basis is necessary and sufficient",
    })


def groebner(polys, order="lex", prune=True, reduced=True):
    r"""Entry point: the Gröbner basis of ``polys`` in ``order``."""
    return buchberger(polys, order=order, prune=prune,
                      reduced=reduced)
