# morie.fn -- function file (rootcoder007/morie)
r"""HAN: hierarchical attention on a heterogeneous graph.

A heterogeneous graph has several *types* of node and edge, and that
heterogeneity is intrinsic rather than incidental: in a film graph
with movies, actors and directors, the relation between two movies
depends on which **meta-path** connects them. Movie-Actor-Movie is a
co-actor relation; Movie-Director-Movie is a shared-director relation.
They are different semantics, and a homogeneous GNN cannot be applied
directly because it has no way to say which one it is following.

**Two attentions, in a hierarchy, answering different questions.**

* **Node-level attention** learns the importance of a node's
  meta-path-based *neighbours*: given that we are following
  Movie-Actor-Movie, which co-acted films matter for this one.
* **Semantic-level attention** learns the importance of the
  *meta-paths themselves*: whether co-actor or shared-director tells
  us more about this node.

Collapsing them into one attention loses the distinction, and the
anchor makes the point concrete -- a graph where one meta-path is pure
noise must receive near-zero semantic weight while its node-level
weights remain a perfectly ordinary distribution.

**Semantic weights are computed by importance, then shared.** Each
meta-path's embedding is projected, compared against a learned
semantic vector :math:`q`, averaged **over nodes**, and softmaxed. The
averaging is what makes the weight a property of the meta-path rather
than of any single node -- and it is why the weights are interpretable
as "this relation matters for this dataset".

**Interpretability is a stated benefit, not a by-product.** Both
levels of weight can be read directly, which is what the paper offers
for graph analysis alongside the accuracy.

References
----------
Wang, X., Ji, H., Shi, C., Wang, B., Cui, P., Yu, P. & Ye, Y. (2019)
"Heterogeneous Graph Attention Network", *Proceedings of The World
Wide Web Conference (WWW '19)*, 2022-2032,
doi:10.1145/3308558.3313562, arXiv:1903.07293. The abstract and
Sec. 1: a heterogeneous graph neural network based on hierarchical
attention, including NODE-LEVEL and SEMANTIC-LEVEL attentions; the
node-level attention learning the importance between a node and its
meta-path based neighbours, and the semantic-level attention learning
the importance of different meta-paths; node embeddings generated by
aggregating features from meta-path based neighbours hierarchically;
the IMDB example where Movie-Actor-Movie is the co-actor relation and
Movie-Director-Movie the shared-director relation, so the relation
between nodes has different semantics depending on the meta-path; the
statement that traditional graph neural networks cannot be applied
directly to a heterogeneous graph; and the demonstration of good
interpretability for graph analysis.

Velickovic, P., Cucurull, G., Casanova, A., Romero, A., Lio, P. &
Bengio, Y. (2018) "Graph Attention Networks", *ICLR 2018*,
arXiv:1710.10903. The node-level attention being extended.

Dong, Y., Chawla, N. V. & Swami, A. (2017) "metapath2vec: Scalable
Representation Learning for Heterogeneous Networks", *KDD '17*,
135-144, doi:10.1145/3097983.3098036. Meta-paths.
"""

import math

from . import _array_core as np
from . import _s03core as k
from ._richresult import RichResult

__all__ = ["metapath_neighbours", "node_attention",
           "semantic_attention", "han_forward"]

_EPS = 1e-12


def metapath_neighbours(edges, types, metapath):
    r"""Neighbours reachable by following one meta-path.

    ``metapath`` is a sequence of node types; a Movie-Actor-Movie path
    connects two movies through any shared actor.
    """
    mp = [str(v) for v in metapath]
    if len(mp) < 2:
        raise ValueError("hetgnn: a meta-path needs at least 2 types")
    nb = {}
    starts = [v for v in types if types[v] == mp[0]]
    for s in starts:
        frontier = {s}
        for step in range(1, len(mp)):
            nxt = set()
            for v in frontier:
                for w in edges.get(v, ()):
                    if types.get(w) == mp[step]:
                        nxt.add(w)
            frontier = nxt
        nb[s] = sorted(frontier - {s})
    return {"neighbours": nb, "metapath": mp,
            "note": "the relation between two nodes DEPENDS on the "
                    "meta-path followed"}


def node_attention(h_i, neighbours, H, a_vec, W, slope=0.2):
    r"""Which meta-path neighbours matter for this node.

    Within one meta-path, so the semantics are fixed and the question
    is only which neighbours.
    """
    def proj(x):
        v = [float(q) for q in k.vec(x)]
        return [sum(W[o][j] * v[j] for j in range(len(v)))
                for o in range(len(W))]

    hi = proj(h_i)
    if not neighbours:
        raise ValueError("hetgnn: the node has no meta-path "
                         "neighbours; the meta-path does not apply "
                         "here")
    sc = []
    for j in neighbours:
        hj = proj(H[j])
        z = hi + hj
        s = sum(float(a_vec[a]) * z[a] for a in range(len(z)))
        sc.append(s if s >= 0 else slope * s)
    m = max(sc)
    e = [math.exp(v - m) for v in sc]
    tot = sum(e)
    al = [v / tot for v in e]
    d = len(hi)
    z = [sum(al[t] * proj(H[neighbours[t]])[a]
             for t in range(len(neighbours))) for a in range(d)]
    return {"embedding": z, "alpha": al, "neighbours": neighbours}


def semantic_attention(Z_per_metapath, W, b, q):
    r"""Which meta-paths matter, averaged OVER NODES.

    The average is what makes the weight a property of the meta-path
    rather than of one node, and what makes it interpretable.
    """
    names = sorted(Z_per_metapath)
    if not names:
        raise ValueError("hetgnn: no meta-path embeddings given")
    w = []
    for nm in names:
        Z = [[float(v) for v in r] for r in k.mat(Z_per_metapath[nm])]
        acc = 0.0
        for i in range(len(Z)):
            proj = [math.tanh(b[o] + sum(W[o][j] * Z[i][j]
                                         for j in range(len(Z[i]))))
                    for o in range(len(W))]
            acc += sum(float(q[o]) * proj[o] for o in range(len(q)))
        w.append(acc / len(Z))
    m = max(w)
    e = [math.exp(v - m) for v in w]
    tot = sum(e)
    beta = [v / tot for v in e]
    return {"beta": dict(zip(names, beta)), "scores":
            dict(zip(names, w)), "metapaths": names,
            "note": "averaged over nodes, so the weight describes the "
                    "META-PATH, not a node"}


def han_forward(H, edges, types, metapaths, a_vec, W_node, W_sem,
                b_sem, q_sem, slope=0.2):
    r"""Node-level attention within each meta-path, then semantic
    attention across them."""
    feats = [[float(v) for v in r] for r in k.mat(H)]
    per = {}
    for name, mp in metapaths.items():
        nb = metapath_neighbours(edges, types, mp)["neighbours"]
        Z = []
        for i in range(len(feats)):
            n = nb.get(i, [])
            if not n:
                Z.append([0.0] * len(W_node))
                continue
            Z.append(node_attention(feats[i], n, feats, a_vec,
                                    W_node, slope)["embedding"])
        per[name] = Z
    sem = semantic_attention(per, W_sem, b_sem, q_sem)
    names = sem["metapaths"]
    d = len(per[names[0]][0])
    final = [[sum(sem["beta"][nm] * per[nm][i][a] for nm in names)
              for a in range(d)] for i in range(len(feats))]
    return RichResult(payload={
        "estimate": final, "embeddings": final,
        "semantic_weights": sem["beta"],
        "per_metapath": per,
        "method": "hierarchical attention on a heterogeneous graph; "
                  "Wang et al. (2019)",
        "note": "two attentions answering different questions: which "
                "NEIGHBOUR, and which META-PATH",
    })


def cheatsheet():
    return ("hetgnn: in a heterogeneous graph the relation between two "
            "nodes depends on the META-PATH -- Movie-Actor-Movie is "
            "co-actor, Movie-Director-Movie is shared-director, and a "
            "homogeneous GNN cannot say which it followed. TWO "
            "attentions in a hierarchy: NODE-level picks which "
            "meta-path neighbours matter, SEMANTIC-level picks which "
            "meta-paths matter, averaged OVER NODES so the weight "
            "describes the relation rather than a node. Collapsing "
            "them loses the distinction; keeping them makes both "
            "readable, which is the paper's interpretability claim.")


# compact alias per ledger/NAMING.md
heterogeneousattention = han_forward
