# morie.fn -- function file (rootcoder007/morie)
# SPDX-License-Identifier: AGPL-3.0-or-later
"""BERT: bidirectional encoder pretrained on MLM + NSP."""

from . import _array_core as np

from ._richresult import RichResult

__all__ = ["geron_bert"]


def _lcg(size, seed, scale=0.1):
    s = int(seed) % 2**32
    out = np.empty(int(size))
    for i in range(int(size)):
        s = (1664525 * s + 1013904223) % 2**32
        out[i] = (2.0 * ((s + 0.5) / 2**32) - 1.0) * scale
    return out


def _init(shape, seed, scale=0.1):
    return _lcg(int(np.prod(shape)), seed, scale).reshape(shape)


def _softmax(z, axis=-1):
    e = np.exp(z - np.max(z, axis=axis, keepdims=True))
    return e / np.sum(e, axis=axis, keepdims=True)


def _layernorm(x, eps=1e-5):
    mu = x.mean(axis=-1, keepdims=True)
    sd = np.sqrt(x.var(axis=-1, keepdims=True) + eps)
    return (x - mu) / sd


def _mha(X, W, n_heads):
    T, d = X.shape
    dh = d // n_heads
    Q, K, V = X @ W["Wq"], X @ W["Wk"], X @ W["Wv"]
    out = np.empty_like(Q)
    attn = np.empty((n_heads, T, T))
    for h in range(n_heads):
        sl = slice(h * dh, (h + 1) * dh)
        a = _softmax(Q[:, sl] @ K[:, sl].T / np.sqrt(dh), axis=-1)
        attn[h] = a
        out[:, sl] = a @ V[:, sl]
    return out @ W["Wo"], attn


def _encoder_block(X, W, n_heads):
    h, attn = _mha(X, W, n_heads)
    X = _layernorm(X + h)
    f = np.maximum(X @ W["W1"] + W["b1"], 0.0) @ W["W2"] + W["b2"]
    return _layernorm(X + f), attn


def _block_weights(d_model, d_ff, seed):
    return {
        "Wq": _init((d_model, d_model), seed + 1),
        "Wk": _init((d_model, d_model), seed + 2),
        "Wv": _init((d_model, d_model), seed + 3),
        "Wo": _init((d_model, d_model), seed + 4),
        "W1": _init((d_model, d_ff), seed + 5),
        "b1": np.zeros(d_ff),
        "W2": _init((d_ff, d_model), seed + 6),
        "b2": np.zeros(d_model),
    }


def geron_bert(X, n_layers=2, n_heads=2, d_model=8, vocab_size=None, d_ff=None, mask_prob=0.15, seed=0):
    """
    BERT: bidirectional encoder pretrained on MLM + NSP.

    Formula: encoder-only; mask 15% tokens, predict masked via MLM head

    Runs a real encoder-only forward pass: token + learned positional
    embeddings, `n_layers` distinct pre-projected multi-head self-attention
    blocks with post-layernorm residuals, an MLM head tied to the embedding
    matrix, and an NSP head on the pooled first position. Weights are
    generated by a fixed integer LCG, so the whole thing is reproducible and
    the masked-language-model loss is an actual cross-entropy on actual
    masked positions.

    Parameters
    ----------
    X : array-like of int
        Token ids, shape (T,) or (batch, T).
    n_layers, n_heads : int
        Depth and number of attention heads; d_model must divide by n_heads.
    d_model : int
        Hidden width.
    vocab_size : int, optional
        Defaults to max(X) + 1. One extra row is appended for [MASK].
    d_ff : int, optional
        Feed-forward width; defaults to 2 * d_model.
    mask_prob : float
        Fraction of positions masked, in (0, 1).
    seed : int
        LCG seed for the weights and the mask choice.

    Returns
    -------
    result : RichResult
        Keys: hidden, mlm_loss, masked_positions, nsp_logits, attentions,
        n_params, estimate, n, method.

    Examples
    --------
    >>> ids = [1, 2, 3, 4, 5, 6, 0, 2]
    >>> r = geron_bert(ids, n_layers=2, n_heads=2, d_model=8)
    >>> r["hidden"].shape
    (1, 8, 8)
    >>> len(r["masked_positions"][0])
    1

    Post-layernorm makes every output row zero-mean, which a stub cannot fake:

    >>> round(abs(float(r["hidden"][0, 0].mean())), 12)
    0.0
    >>> bool(np.allclose(geron_bert(ids)["hidden"], geron_bert(ids)["hidden"]))
    True

    Attention rows are distributions:

    >>> round(float(r["attentions"][0][0][0, 0].sum()), 12)
    1.0

    References
    ----------
    Géron Ch 15
    """
    ids = np.asarray(X)
    if ids.ndim == 1:
        ids = ids.reshape(1, -1)
    if ids.ndim != 2:
        raise ValueError(f"geron_bert: X must be 1-D or 2-D token ids, got ndim={ids.ndim}")
    if ids.size == 0:
        raise ValueError("geron_bert: X is empty")
    if not np.issubdtype(ids.dtype, np.integer):
        if not np.all(np.asarray(ids, dtype=float) == np.floor(np.asarray(ids, dtype=float))):
            raise ValueError("geron_bert: X must contain integer token ids")
        ids = ids.astype(int)
    if np.min(ids) < 0:
        raise ValueError("geron_bert: token ids must be non-negative")
    B, T = ids.shape
    L, H, d = int(n_layers), int(n_heads), int(d_model)
    if L < 1 or H < 1 or d < 1:
        raise ValueError("geron_bert: n_layers, n_heads and d_model must all be >= 1")
    if d % H:
        raise ValueError(f"geron_bert: d_model={d} is not divisible by n_heads={H}")
    Vsz = int(np.max(ids)) + 1 if vocab_size is None else int(vocab_size)
    if Vsz <= int(np.max(ids)):
        raise ValueError(f"geron_bert: vocab_size={Vsz} is too small for token id {int(np.max(ids))}")
    ff = 2 * d if d_ff is None else int(d_ff)
    if ff < 1:
        raise ValueError("geron_bert: d_ff must be >= 1")
    p = float(mask_prob)
    if not (0.0 < p < 1.0):
        raise ValueError(f"geron_bert: mask_prob must lie in (0, 1), got {p}")

    mask_id = Vsz
    E = _init((Vsz + 1, d), seed + 101)
    P = _init((T, d), seed + 202)
    blocks = [_block_weights(d, ff, seed + 1000 * (i + 1)) for i in range(L)]
    W_nsp = _init((d, 2), seed + 303)

    n_mask = max(1, int(round(p * T)))
    u = _lcg(B * T, seed + 404, scale=0.5) + 0.5
    hidden = np.empty((B, T, d))
    attentions = []
    masked_positions = []
    losses = []
    nsp = np.empty((B, 2))
    for b in range(B):
        order = np.argsort(u[b * T : (b + 1) * T], kind="mergesort")
        pos = np.sort(order[:n_mask])
        masked_positions.append(pos.tolist())
        toks = ids[b].copy()
        toks[pos] = mask_id
        Xh = E[toks] + P
        atts = []
        for W in blocks:
            Xh, a = _encoder_block(Xh, W, H)
            atts.append(a)
        hidden[b] = Xh
        attentions.append(atts)
        logits = Xh[pos] @ E.T
        probs = _softmax(logits, axis=-1)
        losses.append(float(-np.mean(np.log(np.clip(probs[np.arange(len(pos)), ids[b][pos]], 1e-15, None)))))
        nsp[b] = Xh[0] @ W_nsp

    n_params = int(
        (Vsz + 1) * d + T * d + L * (4 * d * d + d * ff + ff + ff * d + d) + d * 2
    )

    return RichResult(
        title="BERT encoder (MLM + NSP)",
        summary_lines=[("Layers", L), ("Heads", H), ("d_model", d), ("MLM loss", float(np.mean(losses)))],
        payload={
            "hidden": hidden,
            "mlm_loss": float(np.mean(losses)),
            "mlm_losses": np.asarray(losses),
            "masked_positions": masked_positions,
            "nsp_logits": nsp,
            "attentions": attentions,
            "embeddings": E,
            "n_params": n_params,
            "vocab_size": Vsz,
            "estimate": float(np.mean(losses)),
            "n": int(B * T),
            "method": f"BERT-style bidirectional encoder, {L} layers x {H} heads, MLM + NSP heads",
        },
    )


def cheatsheet():
    return "hmbert: BERT: bidirectional encoder pretrained on MLM + NSP"
