"""Johnson SU distribution: density, distribution function, quantile and random draws.

Johnson, N. L. (1949). Systems of frequency curves generated by methods of translation. Biometrika 36, 149-176.
"""

import math

from ._distcore import draws, out, vec
from ._richresult import RichResult
from ._rrng_core import pnorm, qnorm

__all__ = ["johnsonsu"]


def johnsonsu(x=None, gamma=0.0, delta=1.0, xi=0.0, lam=1.0, p=None, n=0, seed=0):
    r"""Johnson SU distribution: Z = gamma + delta asinh((x - xi)/lam) ~ N(0, 1).

    Returns the density (and its log), the distribution function at ``x``, the
    quantile function at ``p`` and ``n`` draws by inversion of morie's Philox
    uniforms (``seed``; identical in the R arm).

    Parameters
    ----------
    x : float or sequence, optional
        Evaluation points.
    gamma : float
        Parameter.
    delta : float
        Parameter.
    xi : float
        Parameter.
    lam : float
        Parameter.
    p : float or sequence, optional
        Probabilities for the quantile function.
    n : int
        Number of random draws.
    seed : int

    Returns
    -------
    RichResult
        Keys: pdf, logpdf, cdf (when x is given), quantile (when p is given), random.

    References
    ----------
    Johnson, N. L. (1949). Systems of frequency curves generated by methods of translation. Biometrika 36, 149-176.
    Matches ``gamlss.dist::dJSUo(x, mu = xi, sigma = lam, nu = gamma, tau = delta)``.

    Examples
    --------
    >>> round(johnsonsu(0.2, gamma=0.4, delta=1.3, xi=0.2, lam=1.5)["cdf"], 10)
    0.6554217416
    """
    if not (delta > 0 and lam > 0):
        raise ValueError("invalid parameters: need delta > 0 and lam > 0")

    def pdf(v):
        return (
            delta
            / (lam * math.sqrt(2 * math.pi) * math.sqrt(1 + ((v - xi) / lam) ** 2))
            * math.exp(-0.5 * (gamma + delta * math.asinh((v - xi) / lam)) ** 2)
        )

    def cdf(v):
        return pnorm(gamma + delta * math.asinh((v - xi) / lam))

    def qf(u):
        return xi + lam * math.sinh((qnorm(u) - gamma) / delta)

    payload = {}
    if x is not None:
        xs, sc = vec(x)
        dens = [pdf(v) for v in xs]
        payload["pdf"] = out(dens, sc)
        payload["logpdf"] = out([math.log(v) if v > 0 else -math.inf for v in dens], sc)
        payload["cdf"] = out([cdf(v) for v in xs], sc)
    if p is not None:
        ps, sc = vec(p)
        payload["quantile"] = out([qf(u) for u in ps], sc)
    if n:
        payload["random"] = draws(qf, n, seed)
    return RichResult(
        title="Johnson SU distribution",
        summary_lines=[(k, v) for k, v in payload.items() if not isinstance(v, list)],
        payload=payload,
    )


def cheatsheet():
    return "johnsonsu: Johnson SU distribution; pdf, cdf, quantile, Philox draws."
