# morie.fn -- function file (rootcoder007/morie)
"""Cox efficient score for beta."""

import numpy as np

from ._kosorok import cox_score
from ._richresult import RichResult

__all__ = ["kosorok_ch3_cox_efficient_score_beta"]


def kosorok_ch3_cox_efficient_score_beta(Z, Y=None, beta=None, Lambda=None,
                                         M=None, tau=None, time=None, event=None):
    r"""Efficient score for beta in the Cox model (Kosorok Ch. 3):

    .. math:: \tilde\ell_{\beta,\Lambda} = \int_0^\tau
              \Big\{ Z - \frac{P[Z Y(t) e^{\beta'Z}]}
                                {P[Y(t) e^{\beta'Z}]} \Big\}\, dM(t).

    The bracket subtracts the risk-set average of Z: that projection
    is exactly what makes the score EFFICIENT, i.e. orthogonal to the
    nuisance tangent space generated by the baseline hazard Lambda.
    Estimating Lambda therefore costs nothing asymptotically for beta,
    which is the chapter's headline.

    Computed as the empirical partial-likelihood score, whose
    information is the efficient information for beta.

    Parameters
    ----------
    Z : array-like, shape (n,) or (n, p)
        Covariates.
    time, event : array-like, shape (n,)
        Follow-up times and 0/1 event indicators. ``Y`` is accepted as
        an alias for ``time`` for interface compatibility.
    beta : array-like, optional
        Coefficient; zero vector if omitted.
    Lambda, M, tau : ignored
        Interface compatibility -- the baseline hazard is profiled out
        rather than supplied.

    Returns
    -------
    RichResult
        keys: ``score``, ``efficient_information``, ``loglik``,
        ``n_events``, ``n``, ``method``.
    References
    ----------
    Kosorok, M. R. (2008). *Introduction to Empirical Processes and
    Semiparametric Inference*. Springer. Ch. 3 (efficient scores; the Cox model example).
    """
    if time is None:
        time = Y
    if time is None or event is None:
        raise ValueError("supply time (or Y) and event.")
    Z = np.asarray(Z, dtype=float)
    if Z.ndim == 1:
        Z = Z[:, None]
    if beta is None:
        beta = np.zeros(Z.shape[1])
    out = cox_score(beta, Z, time, event)
    return RichResult(
        payload={"score": out["score"],
                 "efficient_information": out["information"],
                 "loglik": out["loglik"], "n_events": out["n_events"],
                 "n": out["n"],
                 "method": "Cox efficient score; risk-set centring gives orthogonality"}
    )


def cheatsheet():
    return "ksr063: Z minus risk-set mean = orthogonal to the Lambda tangent space"
