"""Hierarchical log-linear model for a three-way table by iterative proportional fitting."""

import itertools
import math

from ._richresult import RichResult
from ._stats_core import chi2

__all__ = ["loglinear_three_way"]


def loglinear_three_way(table, margins, tol=1e-12, max_iter=10000):
    r"""Fit the hierarchical log-linear model generated by ``margins`` to an I x J x K table.

    ``margins`` lists the fitted marginal configurations as 0-based axis
    tuples, e.g. ``[(0,), (1,), (2,)]`` for mutual independence
    :math:`\log n\pi_{ijk} = \mu + \lambda^X_i + \lambda^Y_j + \lambda^Z_k`
    (Hedderich, Sachs & Reynarowych 2023, sec. 8.5.5, eq 8.100) or
    ``[(0, 1), (0, 2), (1, 2)]`` for no three-factor interaction. IPF matches
    each margin in turn (``loglin``) until no fitted count moves by more than
    ``tol``. df = cells minus :math:`\sum_S \prod_{a \in S}(d_a - 1)` over
    every axis subset S contained in a margin (including the empty one).

    Parameters
    ----------
    table : I x J x K nested sequence of counts
    margins : sequence of tuples of axes in {0, 1, 2}
    tol : float
    max_iter : int

    Returns
    -------
    RichResult
        ``fit`` and ``residuals`` (Pearson, :math:`r_{ijk} = (y - \hat m)/\sqrt{\hat m}`, p. 855)
        as nested lists, ``lrt`` (:math:`G^2`), ``pearson``, ``df``,
        ``p_lrt``, ``p_pearson``.

    References
    ----------
    Bishop, Y. M. M., Fienberg, S. E. & Holland, P. W. (1975). Discrete
    Multivariate Analysis, ch. 3.
    """
    dims = (len(table), len(table[0]), len(table[0][0]))
    cells = list(itertools.product(*(range(d) for d in dims)))
    obs = {c: float(table[c[0]][c[1]][c[2]]) for c in cells}
    if min(obs.values()) < 0:
        raise ValueError("counts must be non-negative")
    ms = [tuple(sorted(set(int(a) for a in m))) for m in margins]
    if not ms or any(not m or not set(m) <= {0, 1, 2} for m in ms):
        raise ValueError("margins must be non-empty tuples of axes 0, 1, 2")
    fit = dict.fromkeys(cells, 1.0)
    for _ in range(max_iter):
        delta = 0.0
        for m in ms:
            ot, ft = {}, {}
            for c in cells:
                key = tuple(c[a] for a in m)
                ot[key] = ot.get(key, 0.0) + obs[c]
                ft[key] = ft.get(key, 0.0) + fit[c]
            for c in cells:
                key = tuple(c[a] for a in m)
                new = fit[c] * ot[key] / ft[key] if ft[key] > 0 else 0.0
                delta = max(delta, abs(new - fit[c]))
                fit[c] = new
        if delta < tol:
            break
    lrt = 2 * sum(obs[c] * math.log(obs[c] / fit[c]) for c in cells if obs[c] > 0)
    pearson = sum((obs[c] - fit[c]) ** 2 / fit[c] for c in cells if fit[c] > 0)
    subsets = {s for m in ms for k in range(len(m) + 1) for s in itertools.combinations(m, k)}
    npar = sum(math.prod(dims[a] - 1 for a in s) for s in subsets)
    df = len(cells) - npar

    def nest(f):
        return [[[f(i, j, k) for k in range(dims[2])] for j in range(dims[1])] for i in range(dims[0])]

    res = nest(
        lambda i, j, k: (obs[(i, j, k)] - fit[(i, j, k)]) / math.sqrt(fit[(i, j, k)]) if fit[(i, j, k)] > 0 else 0.0
    )
    return RichResult(
        title="Three-way log-linear model",
        summary_lines=[("lrt", lrt), ("df", df)],
        payload={
            "fit": nest(lambda i, j, k: fit[(i, j, k)]),
            "residuals": res,
            "lrt": lrt,
            "pearson": pearson,
            "df": df,
            "p_lrt": float(chi2.sf(lrt, df)) if df > 0 else 1.0,
            "p_pearson": float(chi2.sf(pearson, df)) if df > 0 else 1.0,
        },
    )


def cheatsheet():
    return "ll3way: IPF over the listed margins; G2 = 2 sum y log(y / m), df = cells - sum_S prod (d_a - 1)"
