"""Reinforcement learning for recommendation: judging a recommender you
have not deployed, from the logs of the one you did.

A recommender is not a classifier. It does not predict a label, it
takes an ACTION -- it puts an item in front of someone -- and that
action changes what happens next: what the user sees, what they click,
what state the session is in when the next recommendation is due. So
the objective is a return over a session, not an accuracy on a held-out
row, and the natural formalism is a Markov decision process whose state
is the interaction history, whose action is the item shown, and whose
reward is what the user did about it.

Which creates the problem this module is mostly about. You cannot
measure a new policy by replaying the log, because the log was
generated by a DIFFERENT policy: the items your new policy would have
shown mostly are not in it. Three published estimators correct for
that, and all three are here because they fail in different ways:

  ``ips``    inverse propensity scoring. Weight each logged reward by
             how much more likely the target policy was to take that
             action than the logging policy. Unbiased, and its variance
             explodes when the two policies disagree.
  ``snips``  the same, divided by the mean weight instead of by the
             sample size. Slightly biased, far steadier, and it cannot
             return a value outside the range of the rewards it saw,
             which the plain estimator can and does.
  ``dr``     doubly robust: a reward model plus the propensity
             correction applied to its residual. Right if EITHER the
             model or the propensities are right, which is why it is
             worth the extra argument.

THE SUPPORT CONDITION IS ENFORCED, NOT ASSUMED. If the log contains a
state where the target policy would take an action the logging policy
could never have taken, no reweighting of that log can estimate the
target's value there -- the data simply is not there. The module
refuses and names the state, rather than returning a number whose error
has no bound. That refusal is the single most important thing in here.

Also included, because a recommender is judged on a ranked slate and
not only on a return: precision at k, normalised discounted cumulative
gain at k, and the mean reciprocal rank, all by their textbook
definitions.

References
  Zhao, X., Zhang, L., Ding, Z., Xia, L., Tang, J. and Yin, D. (2018)
    "Recommendations with negative feedback via pairwise deep
    reinforcement learning." Proceedings of the 24th ACM SIGKDD
    International Conference on Knowledge Discovery and Data Mining,
    1040-1048. doi:10.1145/3219819.3219886. The session-MDP framing.
  Horvitz, D.G. and Thompson, D.J. (1952) "A generalization of sampling
    without replacement from a finite universe." Journal of the
    American Statistical Association 47(260), 663-685. Inverse
    propensity weighting.
  Swaminathan, A. and Joachims, T. (2015) "The self-normalized
    estimator for counterfactual learning." Advances in Neural
    Information Processing Systems 28, 3231-3239. The self-normalised
    form and the propensity overfitting it fixes.
  Dudik, M., Langford, J. and Li, L. (2011) "Doubly robust policy
    evaluation and learning." Proceedings of the 28th International
    Conference on Machine Learning, 1097-1104.
  Jarvelin, K. and Kekalainen, J. (2002) "Cumulated gain-based
    evaluation of IR techniques." ACM Transactions on Information
    Systems 20(4), 422-446. Discounted cumulative gain.
"""

import math

from . import _array_core as _core
from . import _w3num as _w
from ._richresult import RichResult

__all__ = ["rlhf_recommendation", "rollout", "off_policy_value",
           "precision_at_k", "ndcg_at_k", "mrr", "cheatsheet"]

_ESTIMATORS = ("ips", "snips", "dr")


def precision_at_k(relevance, k):
    """The share of the top k that were relevant."""
    k = int(k)
    if k < 1:
        raise ValueError("a cut-off below one ranks nothing")
    top = list(relevance)[:k]
    hit = 0
    for v in top:
        if v > 0:
            hit += 1
    return hit / float(k)


def ndcg_at_k(relevance, k):
    """Discounted cumulative gain over its own best possible value.

    The discount is one over the log base two of the rank plus one, so
    the first position is undiscounted and the tenth is worth about a
    third of it. Dividing by the ideal ordering's gain makes it one for
    a perfect ranking and comparable across queries with different
    numbers of relevant items -- which is the whole reason for the
    normalisation.

    A query with nothing relevant has an ideal gain of zero, so the
    ratio is undefined; it is reported as zero, and that is a choice,
    not an accident of the arithmetic.
    """
    k = int(k)
    if k < 1:
        raise ValueError("a cut-off below one ranks nothing")
    rel = [float(v) for v in relevance]

    def dcg(vals):
        terms = []
        for i in range(min(k, len(vals))):
            terms.append(vals[i] / math.log(i + 2.0, 2.0))
        return _w.csum(terms)

    ideal = dcg(sorted(rel, reverse=True))
    return (dcg(rel) / ideal) if ideal > 0.0 else 0.0


def mrr(relevance):
    """One over the rank of the first relevant item, or zero."""
    for i, v in enumerate(relevance):
        if v > 0:
            return 1.0 / (i + 1)
    return 0.0


def rollout(env, policy, n_episodes=20, horizon=10, gamma=0.9, seed=0):
    """Run the policy in a tabular session environment.

    ``env`` gives the states, the actions available, the transition
    probabilities and the expected reward of each state-action pair;
    ``policy`` gives the probability of each action in each state. Both
    are indexed by position, so the environment and the policy cannot
    silently disagree about which action is which.

    The return is discounted, because a session is not infinite and a
    click now is worth more than a click after the user has left.
    """
    P = env["transition"]
    R = env["reward"]
    n_s = len(P)
    n_a = len(P[0])
    if len(policy) != n_s or any(len(row) != n_a for row in policy):
        raise ValueError("the policy must give a distribution over the "
                         "environment's actions in every state")
    start = env.get("start", 0) if hasattr(env, "get") else 0
    rng = _core._SplitMix64(seed)
    rets = []
    visits = [[0 for _ in range(n_a)] for _ in range(n_s)]
    for _ in range(int(n_episodes)):
        s = int(start)
        g = 0.0
        d = 1.0
        for _ in range(int(horizon)):
            u = rng.uniform()
            acc = 0.0
            a = n_a - 1
            for j in range(n_a):
                acc += policy[s][j]
                if u < acc:
                    a = j
                    break
            visits[s][a] += 1
            g += d * R[s][a]
            d *= gamma
            u = rng.uniform()
            acc = 0.0
            nxt = n_s - 1
            for j in range(n_s):
                acc += P[s][a][j]
                if u < acc:
                    nxt = j
                    break
            s = nxt
        rets.append(g)
    mean = _w.csum(rets) / len(rets)
    if len(rets) > 1:
        var = _w.csum((v - mean) * (v - mean) for v in rets) \
            / (len(rets) - 1)
        se = math.sqrt(var / len(rets))
    else:
        se = float("nan")
    return rets, mean, se, visits


def off_policy_value(log, policy, behaviour, estimator="ips",
                     reward_model=None, clip=None):
    """Estimate a policy's value from another policy's log.

    ``log`` is a list of (state, action, reward) triples as they were
    actually observed. ``behaviour`` is the probability the logging
    policy assigned to the action it took -- the propensity -- and it
    has to come from the logging system, not be re-estimated here, or
    the correction corrects for the wrong thing.

    ``clip`` caps the importance weight. It trades the estimator's
    unbiasedness for a bounded variance and it is off by default,
    because a silently clipped estimate is a biased estimate that looks
    like an unbiased one; the number of weights it bit is reported.
    """
    if estimator not in _ESTIMATORS:
        raise ValueError("the estimator is ips, snips or dr")
    n = len(log)
    if n == 0:
        raise ValueError("an off-policy estimate needs a log")
    if len(behaviour) != n:
        raise ValueError("one propensity per logged decision")
    # The support condition. Without it the estimate has no bound on its
    # error, so it is refused rather than returned.
    for i in range(n):
        s, a, r = log[i]
        if behaviour[i] <= 0.0 and policy[s][a] > 0.0:
            raise ValueError(
                "the target policy takes action %d in state %d, which "
                "the logging policy never could: no reweighting of this "
                "log can estimate its value there" % (a, s))
    w = []
    clipped = 0
    for i in range(n):
        s, a, r = log[i]
        v = (policy[s][a] / behaviour[i]) if behaviour[i] > 0.0 else 0.0
        if clip is not None and v > clip:
            v = float(clip)
            clipped += 1
        w.append(v)
    rs = [float(t[2]) for t in log]
    if estimator == "ips":
        est = _w.csum(w[i] * rs[i] for i in range(n)) / n
    elif estimator == "snips":
        tot = _w.csum(w)
        est = (_w.csum(w[i] * rs[i] for i in range(n)) / tot) \
            if tot > 0.0 else 0.0
    else:
        if reward_model is None:
            raise ValueError("the doubly robust estimator needs a "
                             "reward model")
        terms = []
        for i in range(n):
            s, a, r = log[i]
            base = _w.csum(policy[s][j] * reward_model[s][j]
                           for j in range(len(policy[s])))
            terms.append(base + w[i] * (rs[i] - reward_model[s][a]))
        est = _w.csum(terms) / n
    ess = 0.0
    sw = _w.csum(w)
    sw2 = _w.csum(v * v for v in w)
    if sw2 > 0.0:
        ess = sw * sw / sw2
    return {"estimate": est, "weights": w, "n": n,
            "mean_weight": sw / n, "max_weight": max(w) if w else 0.0,
            "ess": ess, "n_clipped": clipped, "estimator": estimator}


def rlhf_recommendation(env, policy, n_episodes=20, horizon=10,
                        gamma=0.9, seed=0, estimator="ips",
                        reward_model=None, clip=None, relevance=None,
                        k=5):
    """Evaluate a recommendation policy, on-policy or from a log.

    An ``env`` carrying ``transition`` and ``reward`` is simulated. An
    ``env`` carrying ``log`` and ``behaviour`` is evaluated off-policy
    against those logged decisions. Both may be present, and then both
    are reported -- which is the useful case, because the gap between
    the simulated value and the off-policy estimate is the thing worth
    looking at.

    Returns
    -------
    RichResult
        The value estimate or estimates, the visitation, the ranking
        metrics if a relevance vector was supplied, and the diagnostics
        that say whether the off-policy number can be trusted.

    References
    ----------
    Zhao et al. (2018) KDD, 1040-1048; Swaminathan and Joachims (2015)
    NeurIPS 28, 3231-3239; Dudik et al. (2011) ICML, 1097-1104.
    """
    out = {"method": "session-MDP recommendation with off-policy "
                     "evaluation"}
    has_sim = "transition" in env and "reward" in env
    has_log = "log" in env and "behaviour" in env
    if not has_sim and not has_log:
        raise ValueError("an environment must carry either a "
                         "transition and reward model or a log and its "
                         "propensities")
    if has_sim:
        rets, mean, se, visits = rollout(env, policy, n_episodes,
                                         horizon, gamma, seed)
        out["returns"] = rets
        out["value"] = mean
        out["se"] = se
        out["ci_lower"] = mean - 1.959963984540054 * se if se == se \
            else float("nan")
        out["ci_upper"] = mean + 1.959963984540054 * se if se == se \
            else float("nan")
        out["visits"] = visits
        out["n_episodes"] = int(n_episodes)
        out["horizon"] = int(horizon)
    else:
        out["returns"] = []
        out["value"] = None
        out["se"] = None
        out["ci_lower"] = None
        out["ci_upper"] = None
        out["visits"] = []
        out["n_episodes"] = 0
        out["horizon"] = 0
    if has_log:
        r = off_policy_value(env["log"], policy, env["behaviour"],
                             estimator, reward_model, clip)
        out["off_policy"] = r["estimate"]
        out["weights"] = r["weights"]
        out["mean_weight"] = r["mean_weight"]
        out["max_weight"] = r["max_weight"]
        out["ess"] = r["ess"]
        out["n_clipped"] = r["n_clipped"]
        out["n_log"] = r["n"]
    else:
        out["off_policy"] = None
        out["weights"] = []
        out["mean_weight"] = None
        out["max_weight"] = None
        out["ess"] = None
        out["n_clipped"] = 0
        out["n_log"] = 0
    if relevance is not None:
        out["precision_at_k"] = precision_at_k(relevance, k)
        out["ndcg_at_k"] = ndcg_at_k(relevance, k)
        out["mrr"] = mrr(relevance)
    else:
        out["precision_at_k"] = None
        out["ndcg_at_k"] = None
        out["mrr"] = None
    out["gamma"] = float(gamma)
    out["k"] = int(k)
    out["estimator"] = estimator
    out["has_simulator"] = has_sim
    out["has_log"] = has_log
    return RichResult(payload=out)


def cheatsheet():
    return ("rlhfRS: recommendation as a session MDP. Discounted "
            "rollout plus IPS, self-normalised IPS or doubly robust "
            "off-policy value; the support condition is enforced")
