# morie.fn -- function file (rootcoder007/morie)
r"""SchNet: continuous-filter convolutions for atoms.

A convolution assumes a grid. Atoms have arbitrary positions, so a
discrete filter indexed by grid offsets has nothing to index. SchNet's
answer is a **continuous-filter convolutional layer**: the filter is a
*function* of the interatomic distance, evaluated wherever the atoms
happen to be,

.. math:: x_i^{l+1} = \sum_{j} x_j^l \circ W^l\big(r_i - r_j\big),

with :math:`W^l` generated by a small network from the distance rather
than stored as weights per offset.

**Two symmetries, and they are different.** Energy must be
**rotationally invariant** -- turning the molecule cannot change it --
while forces must be **rotationally equivariant**, turning with it.
SchNet gets both from one design decision: the filter sees only
:math:`\|r_i - r_j\|`, so everything built from it is invariant, and
forces are then obtained as
:math:`F_i = -\partial E/\partial r_i`, which is equivariant
automatically because the derivative of an invariant scalar with
respect to a position is a vector. Predicting forces by a separate
head would lose that, and would also permit a non-conservative force
field.

**The distance expansion is what makes the filter smooth.** A raw
distance fed to a network gives a filter that varies too sharply; the
distance is expanded in a basis of Gaussians on a grid of centres,
:math:`e_k(r) = \exp(-\gamma(r - \mu_k)^2)`, which decorrelates the
input and makes the learned filter smooth in :math:`r`. A smooth filter
matters physically: energies and forces must be smooth in the atomic
positions or the model cannot be used for molecular dynamics at all.

**A cosine cutoff** ensures that an atom entering the neighbourhood
does so continuously rather than by a step.

References
----------
Schutt, K. T., Kindermans, P.-J., Sauceda, H. E., Chmiela, S.,
Tkatchenko, A. & Muller, K.-R. (2017) "SchNet: A continuous-filter
convolutional neural network for modeling quantum interactions",
*Advances in Neural Information Processing Systems 30 (NeurIPS 2017)*,
991-1001, arXiv:1706.08566. The key contributions as stated: the
continuous-filter convolutional (cfconv) layer as a means to move
beyond grid-bound data such as images or audio towards objects with
arbitrary positions such as atoms in molecules and materials; and
SchNet as a network designed to respect essential quantum-chemical
constraints, using cfconv layers in R^3 to model interactions of atoms
at arbitrary positions, delivering rotationally INVARIANT energy
predictions and rotationally EQUIVARIANT force predictions.

Gilmer, J., Schoenholz, S. S., Riley, P. F., Vinyals, O. & Dahl, G. E.
(2017) "Neural Message Passing for Quantum Chemistry", *ICML 2017*,
PMLR 70, 1263-1272, arXiv:1704.01212. The framework this instantiates;
implemented in :mod:`mpfn`.
"""

import math

from . import _array_core as np
from . import _s03core as k
from ._richresult import RichResult

__all__ = ["gaussian_expansion", "cosine_cutoff", "cfconv",
           "forces_from_energy", "invariance_error"]

_EPS = 1e-12


def gaussian_expansion(r, mu_min=0.0, mu_max=6.0, n_gaussians=25,
                       gamma=None):
    r"""Expand a distance in a basis of Gaussians.

    A raw distance makes the learned filter vary too sharply; the
    expansion decorrelates the input so the filter is smooth in
    :math:`r`, which is required for usable forces.
    """
    n = int(n_gaussians)
    if n < 2:
        raise ValueError("schN: at least 2 Gaussians are needed")
    lo, hi = float(mu_min), float(mu_max)
    if hi <= lo:
        raise ValueError("schN: mu_max must exceed mu_min")
    step = (hi - lo) / (n - 1)
    g = float(gamma) if gamma is not None else 1.0 / (2.0 * step ** 2)
    mus = [lo + step * i for i in range(n)]
    return [math.exp(-g * (float(r) - m) ** 2) for m in mus]


def cosine_cutoff(r, cutoff=5.0):
    r"""Smoothly switch an interaction off at the cutoff.

    :math:`f_c(r) = \tfrac12(\cos(\pi r/r_c)+1)` for
    :math:`r < r_c`, zero beyond -- so an atom crossing the boundary
    does not cause a discontinuity in the energy.
    """
    rc = float(cutoff)
    if rc <= 0.0:
        raise ValueError("schN: the cutoff must be positive")
    v = float(r)
    return 0.5 * (math.cos(math.pi * v / rc) + 1.0) if v < rc else 0.0


def cfconv(X, R, filter_net, cutoff=5.0, **kw):
    r"""The continuous-filter convolution.

    ``filter_net(expansion)`` maps the expanded distance to a filter
    vector; positions enter ONLY through the distance, which is what
    makes the output invariant.
    """
    feats = [[float(v) for v in r] for r in k.mat(X)]
    pos = [[float(v) for v in r] for r in k.mat(R)]
    n, d = len(feats), len(feats[0])
    if len(pos) != n:
        raise ValueError("schN: %d feature rows but %d positions"
                         % (n, len(pos)))
    out = []
    for i in range(n):
        acc = [0.0] * d
        for j in range(n):
            if i == j:
                continue
            r = math.sqrt(sum((pos[i][a] - pos[j][a]) ** 2
                              for a in range(len(pos[i]))))
            w = filter_net(gaussian_expansion(r, **kw))
            fc = cosine_cutoff(r, cutoff)
            if len(w) != d:
                raise ValueError("schN: the filter is %d-dimensional "
                                 "but the features are %d"
                                 % (len(w), d))
            for a in range(d):
                acc[a] += feats[j][a] * float(w[a]) * fc
        out.append(acc)
    return out


def forces_from_energy(energy_fn, R, h=1e-5):
    r""":math:`F_i = -\partial E/\partial r_i`.

    Taking forces as the gradient of the energy makes them equivariant
    without a second head, and guarantees the field is conservative --
    a separate force head would give neither.
    """
    pos = [[float(v) for v in r] for r in k.mat(R)]
    n, d = len(pos), len(pos[0])
    F = []
    for i in range(n):
        row = []
        for a in range(d):
            up = [list(p) for p in pos]
            dn = [list(p) for p in pos]
            up[i][a] += h
            dn[i][a] -= h
            row.append(-(float(energy_fn(up))
                         - float(energy_fn(dn))) / (2.0 * h))
        F.append(row)
    return RichResult(payload={
        "estimate": F, "forces": F,
        "net_force": [sum(F[i][a] for i in range(n))
                      for a in range(d)],
        "method": "forces as the negative gradient of the energy; "
                  "Schutt et al. (2017)",
        "note": "conservative and equivariant by construction; a "
                "separate force head would be neither",
    })


def invariance_error(energy_fn, R, Q, g=None):
    r"""Rotate and translate, and check the energy does not move.

    Invariance of the energy and equivariance of the forces are
    different properties; this checks the first directly.
    """
    pos = [[float(v) for v in r] for r in k.mat(R)]
    d = len(pos[0])
    gv = [0.0] * d if g is None else [float(v) for v in k.vec(g)]
    rot = [[sum(Q[a][b] * pos[i][b] for b in range(d)) + gv[a]
            for a in range(d)] for i in range(len(pos))]
    e0, e1 = float(energy_fn(pos)), float(energy_fn(rot))
    F0 = forces_from_energy(energy_fn, pos)["forces"]
    F1 = forces_from_energy(energy_fn, rot)["forces"]
    want = [[sum(Q[a][b] * F0[i][b] for b in range(d))
             for a in range(d)] for i in range(len(pos))]
    fe = max(abs(F1[i][a] - want[i][a])
             for i in range(len(pos)) for a in range(d))
    return {"energy_error": abs(e1 - e0), "force_error": fe,
            "energy_invariant": abs(e1 - e0) < 1e-8,
            "forces_equivariant": fe < 1e-5,
            "note": "energy INVARIANT, forces EQUIVARIANT -- two "
                    "different properties from one design choice"}


def cheatsheet():
    return ("schN: a convolution needs a grid and atoms have none, so "
            "make the filter a FUNCTION of interatomic distance -- a "
            "continuous-filter convolution, generated by a small "
            "network from the distance. Positions enter only as "
            "||r_i - r_j||, so the energy is rotationally INVARIANT; "
            "forces come from -dE/dr, so they are EQUIVARIANT and the "
            "field is conservative, which a separate force head would "
            "not be. Expand the distance in GAUSSIANS or the filter "
            "varies too sharply for molecular dynamics; a cosine "
            "cutoff keeps neighbourhood changes continuous.")


# compact alias per ledger/NAMING.md
schnet = cfconv
