# morie.fn -- function file (rootcoder007/morie)
"""Space-time cokriging of two variables under a separable intrinsic coregionalisation, and the
space-time covariance generated by diffusion of a Gaussian random field."""

from __future__ import annotations

import math

from . import _array_core as np
from ._qpcore import solve
from ._richresult import RichResult

__all__ = ["st_cokriging", "diffusion_st_covariance"]


def _mat(X):
    return [[float(v) for v in r] for r in np.asarray(X, dtype=float).tolist()]


def diffusion_st_covariance(h, u, sigma2=1.0, xi=1.0, diffusivity=1.0, dim=2):
    r"""Space-time covariance of a field evolving by the diffusion (heat) equation.

    A Gaussian-covariance field ``sigma2 exp(-h^2 / xi^2)`` propagated by
    ``d Z / dt = D laplacian Z`` has, between locations ``h`` apart and times
    ``u`` apart, ``C(h, u) = sigma2 (xi^2 / (xi^2 + 4 D |u|))^{d/2} exp(-h^2 /
    (xi^2 + 4 D |u|))`` (the convolution of the initial covariance with the heat
    kernel ``N(0, 2 D |u| I)``); it is non-separable and of the Gneiting class.

    References
    ----------
    Kolovos, A., Christakos, G., Hristopulos, D. T. and Serre, M. L. (2004).
    Methods for generating non-separable spatiotemporal covariance models with
    potential environmental applications. *Advances in Water Resources* 27,
    815-830.

    Examples
    --------
    >>> round(diffusion_st_covariance(1.0, 0.5, 2.0, 1.0, 0.5), 12)
    0.606530659713
    """

    def one(hh, uu):
        s = xi * xi + 4.0 * diffusivity * abs(uu)
        return sigma2 * (xi * xi / s) ** (dim / 2.0) * math.exp(-hh * hh / s)

    if isinstance(h, (int, float)) and isinstance(u, (int, float)):
        return one(float(h), float(u))
    hv = [float(v) for v in np.asarray(h, dtype=float).ravel().tolist()]
    uv = [float(v) for v in np.asarray(u, dtype=float).ravel().tolist()]
    return [one(a, b) for a, b in zip(hv, uv)]


def st_cokriging(coords, times, variable, values, targets, target_times, coreg, range_s, range_t, nugget=(0.0, 0.0)):
    r"""Ordinary space-time cokriging of variable 0 from two variables.

    Covariances ``C_ab(h, u) = B_ab exp(-h / a_s) exp(-|u| / a_t)`` (separable
    intrinsic coregionalisation, ``B`` = ``coreg`` 2 x 2 positive
    semidefinite) plus a nugget ``c0_a`` for identical observations of the
    same variable. Weights minimise the error variance subject to ``sum_{var 0}
    lambda = 1`` and ``sum_{var 1} lambda = 0``. ``variable`` gives 0 or 1 per
    observation. Returns estimates and cokriging variances.

    References
    ----------
    De Iaco, S., Myers, D. E. and Posa, D. (2005). Space-time variograms and a
    functional form for total air pollution measurements. *Computational
    Statistics and Data Analysis* 41, 311-328.

    Wackernagel, H. (2003). *Multivariate Geostatistics*, 3rd edn. Springer,
    chapter 24.

    Examples
    --------
    >>> r = st_cokriging([[0, 0], [1, 0], [0, 0], [1, 1]], [0, 0, 1, 1], [0, 0, 1, 1], [1.0, 2.0, 0.5, 0.8],
    ...                  [[0.5, 0.2]], [0.5], [[1.0, 0.5], [0.5, 1.0]], 2.0, 3.0)
    >>> round(r.estimate[0], 12)
    1.502246825473
    """
    P = _mat(coords)
    tv = [float(v) for v in np.asarray(times, dtype=float).ravel().tolist()]
    var = [int(v) for v in np.asarray(variable, dtype=float).ravel().tolist()]
    z = [float(v) for v in np.asarray(values, dtype=float).ravel().tolist()]
    B = _mat(coreg)
    n = len(z)

    def cov(i_pt, i_t, i_v, j_pt, j_t, j_v, same):
        c = B[i_v][j_v] * math.exp(-math.dist(i_pt, j_pt) / range_s) * math.exp(-abs(i_t - j_t) / range_t)
        return c + (nugget[i_v] if same else 0.0)

    m = n + 2
    K = [[0.0] * m for _ in range(m)]
    for i in range(n):
        for j in range(n):
            K[i][j] = cov(P[i], tv[i], var[i], P[j], tv[j], var[j], i == j)
        K[i][n + var[i]] = K[n + var[i]][i] = 1.0
    est, kv = [], []
    for t, tt in zip(_mat(targets), [float(v) for v in np.asarray(target_times, dtype=float).ravel().tolist()]):
        rhs = [cov(P[i], tv[i], var[i], t, tt, 0, False) for i in range(n)] + [1.0, 0.0]
        w = solve(K, rhs)
        est.append(sum(w[i] * z[i] for i in range(n)))
        kv.append(B[0][0] + nugget[0] - sum(w[i] * rhs[i] for i in range(n)) - w[n])
    return RichResult(payload={"estimate": est, "variance": kv})


def cheatsheet() -> str:
    return "st_cokriging / diffusion_st_covariance -> space-time cokriging."
