# morie.fn -- function file (rootcoder007/morie)
"""TransE: translation-based embeddings for a knowledge graph."""

import math

from . import _tail1core as C

from ._richresult import RichResult

__all__ = ["transe"]


def transe(triples, dim, epochs=50, lr=0.05, margin=1.0, seed=1):
    """Learn entity and relation vectors with ``h + r ~ t``.

    The whole model is one sentence: a relation is a TRANSLATION in
    embedding space, so a true triple should satisfy
    ``h + r ~ t`` and a corrupted one should not.  That is why TransE
    handles 1-to-1 relations well and 1-to-many badly -- if
    ``(h, r, t1)`` and ``(h, r, t2)`` are both true, the model is forced
    to put ``t1`` and ``t2`` at the same point.

    Training is the margin-based ranking loss of the original paper,
    ``sum max(0, margin + d(h + r, t) - d(h' + r, t'))`` with ``d`` the
    L2 norm, negatives generated by corrupting the head or the tail, and
    entity vectors renormalised to the unit sphere after every epoch
    (relations are not renormalised, exactly as published).

    Determinism: initialisation and corruption both come from the shared
    Lehmer minstd stream, so the two language arms produce bit-identical
    embeddings, and the epoch/learning-rate schedule is fixed rather
    than tuned by early stopping.

    Parameters
    ----------
    triples : array-like, shape (m, 3)
        Rows ``(head_id, relation_id, tail_id)`` with 0-based integer
        ids.
    dim : int
        Embedding dimension.
    epochs : int
        Full passes over the triple list.
    lr : float
        Learning rate for plain SGD.
    margin : float
        Ranking margin.
    seed : int
        Seed for the shared minstd stream.

    Returns
    -------
    RichResult
        ``loss`` (mean margin loss on the last epoch), ``mean_dist``
        (mean ``||h + r - t||`` over the true triples), ``hits_at_1``,
        ``dim``, ``n_entities``, ``n_relations``, ``n_triples``.

    References
    ----------
    Bordes, A., Usunier, N., Garcia-Duran, A., Weston, J. & Yakhnenko,
    O. (2013).  Translating embeddings for modeling multi-relational
    data.  Advances in Neural Information Processing Systems 26,
    2787-2795.
    """
    T = C.mat(triples)
    m = len(T)
    if m == 0:
        raise ValueError("transe: need at least one triple")
    dim = int(dim)
    if dim < 1:
        raise ValueError("transe: dim must be at least 1")
    hs = [int(r[0]) for r in T]
    rs = [int(r[1]) for r in T]
    ts = [int(r[2]) for r in T]
    if min(hs + ts) < 0 or min(rs) < 0:
        raise ValueError("transe: entity and relation ids must be non-negative")
    ne = max(hs + ts) + 1
    nr = max(rs) + 1
    rng = C.Lcg(seed)
    bound = 6.0 / math.sqrt(dim)
    E = [[(rng.unif() * 2.0 - 1.0) * bound for _ in range(dim)] for _ in range(ne)]
    R = [[(rng.unif() * 2.0 - 1.0) * bound for _ in range(dim)] for _ in range(nr)]

    def unit(v):
        nrm = math.sqrt(sum(x * x for x in v))
        return [x / nrm for x in v] if nrm > 0.0 else v

    R = [unit(v) for v in R]
    E = [unit(v) for v in E]

    def dist(h, r, t):
        return math.sqrt(sum((E[h][d] + R[r][d] - E[t][d]) ** 2 for d in range(dim)))

    loss = 0.0
    for ep in range(int(epochs)):
        loss = 0.0
        for j in range(m):
            h, r, t = hs[j], rs[j], ts[j]
            corrupt_tail = rng.unif() < 0.5
            other = int(rng.unif() * ne) % ne
            hn, tn = (h, other) if corrupt_tail else (other, t)
            dp = dist(h, r, t)
            dn = dist(hn, r, tn)
            gap = margin + dp - dn
            if gap <= 0.0:
                continue
            loss += gap
            for d in range(dim):
                gp = (E[h][d] + R[r][d] - E[t][d]) / dp if dp > 0.0 else 0.0
                gn = (E[hn][d] + R[r][d] - E[tn][d]) / dn if dn > 0.0 else 0.0
                E[h][d] -= lr * gp
                E[t][d] += lr * gp
                R[r][d] -= lr * (gp - gn)
                E[hn][d] += lr * gn
                E[tn][d] -= lr * gn
        E = [unit(v) for v in E]
    loss /= m
    dists = [dist(hs[j], rs[j], ts[j]) for j in range(m)]
    mean_dist = sum(dists) / m
    hits = 0
    for j in range(m):
        d0 = dists[j]
        better = sum(1 for e in range(ne)
                     if e != ts[j] and dist(hs[j], rs[j], e) < d0)
        if better == 0:
            hits += 1
    return RichResult(payload={
        "loss": loss, "mean_dist": mean_dist, "hits_at_1": hits / float(m),
        "dim": float(dim), "n_entities": float(ne), "n_relations": float(nr),
        "n_triples": float(m),
        "method": "TransE translation embeddings, margin ranking loss"})


def cheatsheet():
    return "transE(triples, dim): TransE knowledge-graph embeddings."
